<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'contractor_doc_id',
'contractor_email',
'contractor_email_mincit',
'contractor_name',
'contractor_lname',
'contractor_image',
'enlace_sigep',
'contractor_id',
'active',
'groupid',
'sys_user',
'sys_date',
'sys_update',
'contractor_decljur',
'contractor_medicinapre_file',
'contractor_dependientes',
'dem_profesion',
'contractor_arl',
'contractor_cajacompensacion',
'emergencia',
'dem_discapacidad',
'contractor_fondopensiones',
'contractor_eps',
'iva_regimen',
'bank_cta_number',
'bank_cta_type',
'bank_name',
'contractor_dependencia',
'contractor_sup_jerarquico',
'contractor_phone',
'contractor_mobile',
'ubica_extension',
'contractor_city',
'contractor_address',
'ct_nacionalidad',
'dem_genero',
'ct_fecha_nacimiento',
'contractor_type',
'sys_level',
'sys_status',
'ct_fecha_nacimiento_mun',
'factura',
'actividad_economica',
'responsabilidades',
'reset_token',
'reset_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'contractor_doc_id' => array( 'integrated_edit_field1' ),
'contractor_email' => array( 'integrated_edit_field9' ),
'contractor_email_mincit' => array( 'integrated_edit_field10' ),
'contractor_name' => array( 'integrated_edit_field5' ),
'contractor_lname' => array( 'integrated_edit_field6' ),
'contractor_image' => array( 'integrated_edit_field4',
'edit_field_tooltip' ),
'enlace_sigep' => array( 'integrated_edit_field8' ),
'contractor_id' => array( 'integrated_edit_field55' ),
'active' => array( 'integrated_edit_field28' ),
'groupid' => array( 'integrated_edit_field27' ),
'sys_user' => array( 'integrated_edit_field20' ),
'sys_date' => array( 'integrated_edit_field21' ),
'sys_update' => array( 'integrated_edit_field19' ),
'contractor_decljur' => array( 'integrated_edit_field34' ),
'contractor_medicinapre_file' => array( 'integrated_edit_field32' ),
'contractor_dependientes' => array( 'integrated_edit_field31' ),
'dem_profesion' => array( 'integrated_edit_field2' ),
'contractor_arl' => array( 'integrated_edit_field40' ),
'contractor_cajacompensacion' => array( 'integrated_edit_field39' ),
'emergencia' => array( 'integrated_edit_field51' ),
'dem_discapacidad' => array( 'integrated_edit_field50' ),
'contractor_fondopensiones' => array( 'integrated_edit_field38' ),
'contractor_eps' => array( 'integrated_edit_field37' ),
'iva_regimen' => array( 'integrated_edit_field18' ),
'bank_cta_number' => array( 'integrated_edit_field17' ),
'bank_cta_type' => array( 'integrated_edit_field16' ),
'bank_name' => array( 'integrated_edit_field15' ),
'contractor_dependencia' => array( 'integrated_edit_field7' ),
'contractor_sup_jerarquico' => array( 'integrated_edit_field3' ),
'contractor_phone' => array( 'integrated_edit_field12' ),
'contractor_mobile' => array( 'integrated_edit_field13' ),
'ubica_extension' => array( 'integrated_edit_field42' ),
'contractor_city' => array( 'integrated_edit_field14' ),
'contractor_address' => array( 'integrated_edit_field11' ),
'ct_nacionalidad' => array( 'integrated_edit_field46' ),
'dem_genero' => array( 'integrated_edit_field43' ),
'ct_fecha_nacimiento' => array( 'integrated_edit_field45' ),
'contractor_type' => array( 'integrated_edit_field' ),
'sys_level' => array( 'integrated_edit_field23' ),
'sys_status' => array( 'integrated_edit_field24' ),
'ct_fecha_nacimiento_mun' => array( 'integrated_edit_field22' ),
'factura' => array( 'integrated_edit_field25' ),
'actividad_economica' => array( 'integrated_edit_field26' ),
'responsabilidades' => array( 'integrated_edit_field29' ),
'reset_token' => array( 'integrated_edit_field30' ),
'reset_date' => array( 'integrated_edit_field33' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'tabs',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field33' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field4',
'edit_field_tooltip',
'integrated_edit_field8',
'integrated_edit_field45',
'integrated_edit_field43',
'integrated_edit_field46',
'text' ),
'section1' => array( 'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field42',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field3',
'integrated_edit_field7' ),
'section3' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field18' ),
'section6' => array( 'integrated_edit_field37',
'integrated_edit_field38',
'integrated_edit_field50',
'integrated_edit_field51',
'integrated_edit_field39',
'integrated_edit_field40',
'integrated_edit_field2',
'integrated_edit_field31' ),
'section2' => array( 'integrated_edit_field32',
'integrated_edit_field34' ),
'section5' => array( 'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field55',
'integrated_edit_field23',
'integrated_edit_field24' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field22' => 'grid',
'integrated_edit_field25' => 'grid',
'integrated_edit_field26' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field33' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field6' => 'section',
'integrated_edit_field4' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field45' => 'section',
'integrated_edit_field43' => 'section',
'integrated_edit_field46' => 'section',
'text' => 'section',
'integrated_edit_field11' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field42' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field15' => 'section3',
'integrated_edit_field16' => 'section3',
'integrated_edit_field17' => 'section3',
'integrated_edit_field18' => 'section3',
'integrated_edit_field37' => 'section6',
'integrated_edit_field38' => 'section6',
'integrated_edit_field50' => 'section6',
'integrated_edit_field51' => 'section6',
'integrated_edit_field39' => 'section6',
'integrated_edit_field40' => 'section6',
'integrated_edit_field2' => 'section6',
'integrated_edit_field31' => 'section6',
'integrated_edit_field32' => 'section2',
'integrated_edit_field34' => 'section2',
'integrated_edit_field19' => 'section5',
'integrated_edit_field21' => 'section5',
'integrated_edit_field20' => 'section5',
'integrated_edit_field27' => 'section5',
'integrated_edit_field28' => 'section5',
'integrated_edit_field55' => 'section5',
'integrated_edit_field23' => 'section5',
'integrated_edit_field24' => 'section5' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field26' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field33' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c6' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field45' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field43' => array( 'location' => 'section',
'cellId' => 'c10' ),
'integrated_edit_field46' => array( 'location' => 'section',
'cellId' => 'c11' ),
'text' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field42' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field15' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field18' => array( 'location' => 'section3',
'cellId' => 'c3' ),
'integrated_edit_field37' => array( 'location' => 'section6',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section6',
'cellId' => 'c' ),
'integrated_edit_field50' => array( 'location' => 'section6',
'cellId' => 'c2' ),
'integrated_edit_field51' => array( 'location' => 'section6',
'cellId' => 'c3' ),
'integrated_edit_field39' => array( 'location' => 'section6',
'cellId' => 'c4' ),
'integrated_edit_field40' => array( 'location' => 'section6',
'cellId' => 'c5' ),
'integrated_edit_field2' => array( 'location' => 'section6',
'cellId' => 'c6' ),
'integrated_edit_field31' => array( 'location' => 'section6',
'cellId' => 'c7' ),
'integrated_edit_field32' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field34' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field19' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'section5',
'cellId' => 'c2' ),
'integrated_edit_field27' => array( 'location' => 'section5',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'section5',
'cellId' => 'c4' ),
'integrated_edit_field55' => array( 'location' => 'section5',
'cellId' => 'c5' ),
'integrated_edit_field23' => array( 'location' => 'section5',
'cellId' => 'c6' ),
'integrated_edit_field24' => array( 'location' => 'section5',
'cellId' => 'c7' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'integrated_edit_field' => array( 'integrated_edit_field1',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field55',
'integrated_edit_field28',
'integrated_edit_field27',
'integrated_edit_field20',
'integrated_edit_field21',
'integrated_edit_field19',
'integrated_edit_field34',
'integrated_edit_field32',
'integrated_edit_field31',
'integrated_edit_field2',
'integrated_edit_field40',
'integrated_edit_field39',
'integrated_edit_field51',
'integrated_edit_field50',
'integrated_edit_field38',
'integrated_edit_field37',
'integrated_edit_field18',
'integrated_edit_field17',
'integrated_edit_field16',
'integrated_edit_field15',
'integrated_edit_field7',
'integrated_edit_field3',
'integrated_edit_field12',
'integrated_edit_field13',
'integrated_edit_field42',
'integrated_edit_field14',
'integrated_edit_field11',
'integrated_edit_field46',
'integrated_edit_field43',
'integrated_edit_field45',
'integrated_edit_field',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field33' ),
'edit_field' => array( 'integrated_edit_field4' ),
'edit_field_tooltip' => array( 'edit_field_tooltip' ),
'text' => array( 'text' ),
'tabs' => array( 'tabs' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field33' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0,
1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 8 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section6' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field31' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field37' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field39' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field32' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field34' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'tabs',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field26',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field33' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c11' ),
array( 'cell' => 'c12' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field4',
'edit_field_tooltip' ) ),
'c7' => array( 'model' => 'c1',
'items' => array(  ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ),
'useFullWidth' => true ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field45' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ) ),
'c11' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field46' ) ),
'c12' => array( 'model' => 'c1',
'items' => array(  ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c14' => array( 'model' => 'c1',
'items' => array(  ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section6' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field37' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field50' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field51' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field39' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field31' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field32' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field34' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array(  ) ),
'integrated_edit_field1' => array( 'field' => 'contractor_doc_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'contractor_email',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'contractor_email_mincit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'contractor_name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'contractor_lname',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'contractor_image',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'contractor_image',
'separated' => true,
'tooltip' => array( 'field' => 'contractor_image',
'table' => 'contractor_master',
'type' => 4 ) ),
'integrated_edit_field8' => array( 'field' => 'enlace_sigep',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field55' => array( 'field' => 'contractor_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field28' => array( 'field' => 'active',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'groupid',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field19' => array( 'field' => 'sys_update',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field34' => array( 'field' => 'contractor_decljur',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field32' => array( 'field' => 'contractor_medicinapre_file',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field31' => array( 'field' => 'contractor_dependientes',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'dem_profesion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field40' => array( 'field' => 'contractor_arl',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field39' => array( 'field' => 'contractor_cajacompensacion',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field51' => array( 'field' => 'emergencia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'placeholder' => array( 'field' => 'emergencia',
'table' => null,
'type' => 5 ),
'tooltip' => array( 'field' => 'emergencia',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field50' => array( 'field' => 'dem_discapacidad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field38' => array( 'field' => 'contractor_fondopensiones',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field37' => array( 'field' => 'contractor_eps',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'iva_regimen',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field17' => array( 'field' => 'bank_cta_number',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field16' => array( 'field' => 'bank_cta_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field15' => array( 'field' => 'bank_name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'contractor_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field12' => array( 'field' => 'contractor_phone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'contractor_mobile',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field42' => array( 'field' => 'ubica_extension',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'contractor_city',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'contractor_address',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-info">
  <a href="https://www.funcionpublica.gov.co/web/sigep/hojas-de-vida" class="alert-link" target="_blank">Clic para ir a la página de función pública</a>
</div>',
'type' => 0 ) ),
'integrated_edit_field46' => array( 'field' => 'ct_nacionalidad',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field43' => array( 'field' => 'dem_genero',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field45' => array( 'field' => 'ct_fecha_nacimiento',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field' => array( 'field' => 'contractor_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Datos personales',
'type' => 0 ),
array( 'text' => 'Información de ubicación',
'type' => 0 ),
array( 'text' => 'Información financiera',
'type' => 0 ),
array( 'text' => 'Caracterización',
'type' => 0 ),
array( 'text' => 'Anexos',
'type' => 0 ),
array( 'text' => '.',
'type' => 0 ) ),
'locations' => array( 'section',
'section1',
'section3',
'section6',
'section2',
'section5' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field23' => array( 'field' => 'sys_level',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'sys_status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field22' => array( 'field' => 'ct_fecha_nacimiento_mun',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'factura',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field26' => array( 'field' => 'actividad_economica',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'responsabilidades',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'reset_token',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field33' => array( 'field' => 'reset_date',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>