<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'q_consulta_op' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'contrato_attached' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'fields' => array( 'gridFields' => array( 'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'cont_secop_proceso',
'cont_secop_enlace' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'prenumero' => array( 'integrated_edit_field5' ),
'numregistro' => array( 'integrated_edit_field6' ),
'pre_contnumero' => array( 'integrated_edit_field7' ),
'contnumero' => array( 'integrated_edit_field8' ),
'cont_ano' => array( 'integrated_edit_field11' ),
'cont_codrubro' => array( 'integrated_edit_field12' ),
'cont_catalogo_presupuestal' => array( 'integrated_edit_field15' ),
'cont_fecha_inicio' => array( 'integrated_edit_field19' ),
'cont_fechafinal' => array( 'integrated_edit_field20' ),
'cont_periodicidad' => array( 'integrated_edit_field24' ),
'cont_valorinicial' => array( 'integrated_edit_field29' ),
'cont_valormensual' => array( 'integrated_edit_field30' ),
'cont_objeto' => array( 'integrated_edit_field55' ),
'cont_obligaciones' => array( 'integrated_edit_field56' ),
'cont_plazo' => array( 'integrated_edit_field57' ),
'cont_secop_proceso' => array( 'integrated_edit_field60' ),
'cont_secop_enlace' => array( 'integrated_edit_field61' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'view_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'grid' => array( 'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field20',
'integrated_edit_field29',
'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field61',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field19',
'integrated_edit_field24',
'integrated_edit_field30',
'integrated_edit_field56',
'integrated_edit_field60' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_header' => 'top',
'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'integrated_edit_field5' => 'grid',
'integrated_edit_field7' => 'grid',
'integrated_edit_field11' => 'grid',
'integrated_edit_field15' => 'grid',
'integrated_edit_field20' => 'grid',
'integrated_edit_field29' => 'grid',
'integrated_edit_field55' => 'grid',
'integrated_edit_field57' => 'grid',
'integrated_edit_field61' => 'grid',
'integrated_edit_field6' => 'grid',
'integrated_edit_field8' => 'grid',
'integrated_edit_field12' => 'grid',
'integrated_edit_field19' => 'grid',
'integrated_edit_field24' => 'grid',
'integrated_edit_field30' => 'grid',
'integrated_edit_field56' => 'grid',
'integrated_edit_field60' => 'grid' ),
'itemLocations' => array( 'integrated_edit_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field12' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field24' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field30' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field56' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field60' => array( 'location' => 'grid',
'cellId' => 'c' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'integrated_edit_field' => array( 'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field11',
'integrated_edit_field12',
'integrated_edit_field15',
'integrated_edit_field19',
'integrated_edit_field20',
'integrated_edit_field24',
'integrated_edit_field29',
'integrated_edit_field30',
'integrated_edit_field55',
'integrated_edit_field56',
'integrated_edit_field57',
'integrated_edit_field60',
'integrated_edit_field61' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field20',
'integrated_edit_field29',
'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field61' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field19',
'integrated_edit_field24',
'integrated_edit_field30',
'integrated_edit_field56',
'integrated_edit_field60' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field5',
'integrated_edit_field7',
'integrated_edit_field11',
'integrated_edit_field15',
'integrated_edit_field20',
'integrated_edit_field29',
'integrated_edit_field55',
'integrated_edit_field57',
'integrated_edit_field61' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field12',
'integrated_edit_field19',
'integrated_edit_field24',
'integrated_edit_field30',
'integrated_edit_field56',
'integrated_edit_field60' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 2,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header' ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field5' => array( 'field' => 'prenumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'numregistro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'pre_contnumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'contnumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'cont_ano',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'cont_codrubro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'cont_fecha_inicio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'cont_fechafinal',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'cont_periodicidad',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'cont_valorinicial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'cont_valormensual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field55' => array( 'field' => 'cont_objeto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field56' => array( 'field' => 'cont_obligaciones',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field57' => array( 'field' => 'cont_plazo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field60' => array( 'field' => 'cont_secop_proceso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field61' => array( 'field' => 'cont_secop_enlace',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>