<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'terms_acepta',
'terms_msj',
'contractor_doc_id',
'contractor_doc_dv',
'contractor_email',
'contractor_email_mincit',
'contractor_name',
'contractor_lname',
'contractor_image',
'contractor_type',
'contractor_address',
'contractor_city',
'contractor_mobile',
'contractor_phone',
'contractor_sup_jerarquico',
'contractor_dependencia',
'actividad_economica',
'responsabilidades',
'factura',
'iva_regimen',
'bank_name',
'bank_cta_type',
'bank_cta_number',
'sys_update',
'sys_date',
'sys_user',
'groupid',
'active',
'contractor_id',
'sys_level',
'sys_status' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'terms_acepta' => array( 'integrated_edit_field54' ),
'terms_msj' => array( 'integrated_edit_field53' ),
'contractor_doc_id' => array( 'integrated_edit_field1' ),
'contractor_doc_dv' => array( 'integrated_edit_field2' ),
'contractor_email' => array( 'integrated_edit_field9' ),
'contractor_email_mincit' => array( 'integrated_edit_field10' ),
'contractor_name' => array( 'integrated_edit_field5' ),
'contractor_lname' => array( 'integrated_edit_field6' ),
'contractor_image' => array( 'edit_field_label',
'integrated_edit_field4',
'edit_field_tooltip' ),
'contractor_type' => array( 'integrated_edit_field' ),
'contractor_address' => array( 'integrated_edit_field11' ),
'contractor_city' => array( 'integrated_edit_field14' ),
'contractor_mobile' => array( 'integrated_edit_field13' ),
'contractor_phone' => array( 'integrated_edit_field12' ),
'contractor_sup_jerarquico' => array( 'integrated_edit_field3' ),
'contractor_dependencia' => array( 'integrated_edit_field7' ),
'actividad_economica' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field8' ),
'responsabilidades' => array( 'edit_field_label2',
'edit_field_tooltip2',
'integrated_edit_field22' ),
'factura' => array( 'integrated_edit_field25' ),
'iva_regimen' => array( 'integrated_edit_field18' ),
'bank_name' => array( 'integrated_edit_field15' ),
'bank_cta_type' => array( 'integrated_edit_field16' ),
'bank_cta_number' => array( 'integrated_edit_field17' ),
'sys_update' => array( 'integrated_edit_field19' ),
'sys_date' => array( 'integrated_edit_field21' ),
'sys_user' => array( 'integrated_edit_field20' ),
'groupid' => array( 'integrated_edit_field27' ),
'active' => array( 'integrated_edit_field28' ),
'contractor_id' => array( 'integrated_edit_field55' ),
'sys_level' => array( 'integrated_edit_field23' ),
'sys_status' => array( 'integrated_edit_field24' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'view_header' ),
'grid' => array( 'tabs' ),
'section4' => array( 'integrated_edit_field54',
'integrated_edit_field53' ),
'section' => array( 'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field5',
'integrated_edit_field6',
'edit_field_label',
'integrated_edit_field4',
'edit_field_tooltip',
'integrated_edit_field' ),
'section1' => array( 'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field3',
'integrated_edit_field7' ),
'section2' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field8',
'edit_field_label2',
'edit_field_tooltip2',
'integrated_edit_field22',
'integrated_edit_field25',
'integrated_edit_field18' ),
'section3' => array( 'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17' ),
'section5' => array( 'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field55',
'integrated_edit_field23',
'integrated_edit_field24' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'view_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field54' => 'section4',
'integrated_edit_field53' => 'section4',
'integrated_edit_field1' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field6' => 'section',
'edit_field_label' => 'section',
'integrated_edit_field4' => 'section',
'edit_field_tooltip' => 'section',
'integrated_edit_field' => 'section',
'integrated_edit_field11' => 'section1',
'integrated_edit_field14' => 'section1',
'integrated_edit_field13' => 'section1',
'integrated_edit_field12' => 'section1',
'integrated_edit_field3' => 'section1',
'integrated_edit_field7' => 'section1',
'edit_field_label1' => 'section2',
'edit_field_tooltip1' => 'section2',
'integrated_edit_field8' => 'section2',
'edit_field_label2' => 'section2',
'edit_field_tooltip2' => 'section2',
'integrated_edit_field22' => 'section2',
'integrated_edit_field25' => 'section2',
'integrated_edit_field18' => 'section2',
'integrated_edit_field15' => 'section3',
'integrated_edit_field16' => 'section3',
'integrated_edit_field17' => 'section3',
'integrated_edit_field19' => 'section5',
'integrated_edit_field21' => 'section5',
'integrated_edit_field20' => 'section5',
'integrated_edit_field27' => 'section5',
'integrated_edit_field28' => 'section5',
'integrated_edit_field55' => 'section5',
'integrated_edit_field23' => 'section5',
'integrated_edit_field24' => 'section5' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c' ),
'integrated_edit_field54' => array( 'location' => 'section4',
'cellId' => 'c1' ),
'integrated_edit_field53' => array( 'location' => 'section4',
'cellId' => 'c' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field6' => array( 'location' => 'section',
'cellId' => 'c5' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c6' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field14' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field13' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field3' => array( 'location' => 'section1',
'cellId' => 'c8' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'edit_field_label1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'edit_field_tooltip1' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field8' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'edit_field_label2' => array( 'location' => 'section2',
'cellId' => 'c' ),
'edit_field_tooltip2' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field22' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field25' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field15' => array( 'location' => 'section3',
'cellId' => 'c1' ),
'integrated_edit_field16' => array( 'location' => 'section3',
'cellId' => 'c' ),
'integrated_edit_field17' => array( 'location' => 'section3',
'cellId' => 'c2' ),
'integrated_edit_field19' => array( 'location' => 'section5',
'cellId' => 'c1' ),
'integrated_edit_field21' => array( 'location' => 'section5',
'cellId' => 'c' ),
'integrated_edit_field20' => array( 'location' => 'section5',
'cellId' => 'c2' ),
'integrated_edit_field27' => array( 'location' => 'section5',
'cellId' => 'c3' ),
'integrated_edit_field28' => array( 'location' => 'section5',
'cellId' => 'c4' ),
'integrated_edit_field55' => array( 'location' => 'section5',
'cellId' => 'c5' ),
'integrated_edit_field23' => array( 'location' => 'section5',
'cellId' => 'c6' ),
'integrated_edit_field24' => array( 'location' => 'section5',
'cellId' => 'c7' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'view_header' => array( 'view_header' ),
'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'tabs' => array( 'tabs' ),
'integrated_edit_field' => array( 'integrated_edit_field54',
'integrated_edit_field53',
'integrated_edit_field1',
'integrated_edit_field2',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field',
'integrated_edit_field11',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field12',
'integrated_edit_field3',
'integrated_edit_field7',
'integrated_edit_field25',
'integrated_edit_field18',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field21',
'integrated_edit_field20',
'integrated_edit_field27',
'integrated_edit_field28',
'integrated_edit_field55',
'integrated_edit_field23',
'integrated_edit_field24' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2' ),
'edit_field' => array( 'integrated_edit_field4',
'integrated_edit_field8',
'integrated_edit_field22' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field54' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 2 ),
'section' => array( 'cells' => array( 'c6' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field4',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 4 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0,
1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'edit_field_tooltip2',
'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section3' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 3 ),
'section5' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field27' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field55' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field54' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0,
'useFullWidth' => true ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field53' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7',
'colspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c',
'colspan' => 1 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5',
'colspan' => 1 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c6' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field4',
'edit_field_tooltip' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'edit_field_tooltip1',
'integrated_edit_field8' ),
'useFullWidth' => true ),
'c' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'edit_field_tooltip2',
'integrated_edit_field22' ),
'useFullWidth' => true ),
'c2' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field25' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_edit_field18' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section3' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ),
'c4' => array( 'model' => 'c1',
'items' => array(  ) ),
'c5' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section5' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field27' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field55' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_header' => array( 'type' => 'view_header',
'title' => array( 'page' => 'view',
'table' => 'contractor_master_jur',
'type' => 7 ) ),
'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Protección de datos',
'type' => 0 ),
array( 'text' => 'Datos personales',
'type' => 0 ),
array( 'text' => 'Información de ubicación',
'type' => 0 ),
array( 'text' => 'Información DIAN',
'type' => 0 ),
array( 'text' => 'Información financiera',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section4',
'section',
'section1',
'section2',
'section3',
'section5' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'integrated_edit_field54' => array( 'field' => 'terms_acepta',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field53' => array( 'field' => 'terms_msj',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'contractor_doc_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field2' => array( 'field' => 'contractor_doc_dv',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'contractor_email',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'contractor_email_mincit',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'contractor_name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'contractor_lname',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'contractor_image',
'separated' => true ),
'integrated_edit_field4' => array( 'field' => 'contractor_image',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'contractor_image',
'separated' => true ),
'integrated_edit_field' => array( 'field' => 'contractor_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'contractor_address',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field14' => array( 'field' => 'contractor_city',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field13' => array( 'field' => 'contractor_mobile',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field12' => array( 'field' => 'contractor_phone',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'contractor_dependencia',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'actividad_economica',
'separated' => true,
'label' => array( 'field' => 'actividad_economica',
'table' => null,
'type' => 3 ) ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'actividad_economica',
'separated' => true,
'tooltip' => array( 'field' => 'actividad_economica',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field8' => array( 'field' => 'actividad_economica',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'responsabilidades',
'separated' => true,
'label' => array( 'field' => 'responsabilidades',
'table' => 'contractor_master_jur',
'type' => 3 ) ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'responsabilidades',
'separated' => true,
'tooltip' => array( 'field' => 'responsabilidades',
'table' => null,
'type' => 4 ) ),
'integrated_edit_field22' => array( 'field' => 'responsabilidades',
'type' => 'edit_field',
'orientation' => 0,
'joined' => false,
'separated' => true,
'updateOnEdit' => false ),
'integrated_edit_field25' => array( 'field' => 'factura',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'factura',
'table' => 'contractor_master',
'type' => 3 ),
'updateOnEdit' => false ),
'integrated_edit_field18' => array( 'field' => 'iva_regimen',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field15' => array( 'field' => 'bank_name',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field16' => array( 'field' => 'bank_cta_type',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field17' => array( 'field' => 'bank_cta_number',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field19' => array( 'field' => 'sys_update',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field21' => array( 'field' => 'sys_date',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field20' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field27' => array( 'field' => 'groupid',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field28' => array( 'field' => 'active',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field55' => array( 'field' => 'contractor_id',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'sys_level',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field24' => array( 'field' => 'sys_status',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>