<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'hideNumberOfRecords' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'q_consulta_op' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'contrato_attached' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_reg_sigep' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_plazoi' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_otrosi' => array( 'totalsType' => '' ),
'cont_otrosi_type' => array( 'totalsType' => '' ),
'cont_valorant' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_valorvigente' => array( 'totalsType' => '' ),
'cont_valors' => array( 'totalsType' => '' ),
'cont_lugar' => array( 'totalsType' => '' ),
'cont_region' => array( 'totalsType' => '' ),
'cont_requactaliq' => array( 'totalsType' => '' ),
'cont_plazol' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_formapago' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_funcion' => array( 'totalsType' => '' ),
'cesion_estado' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_afilia_arl' => array( 'totalsType' => '' ),
'cont_excluir_notificacion' => array( 'totalsType' => '' ),
'cont_depsup' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'cont_lugar_prestacion' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'cont_tipo_regimen' => array( 'totalsType' => '' ),
'cont_fecha_firma' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_sigep' => array( 'totalsType' => '' ),
'cont_vigencias_futuras' => array( 'totalsType' => '' ),
'vf_num_autorizacion' => array( 'totalsType' => '' ),
'vf_fecha' => array( 'totalsType' => '' ),
'vf_valor' => array( 'totalsType' => '' ),
'cont_fechasistema' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'pre_contnumero',
'numregistro',
'cont_codrubro',
'cont_fecha_inicio',
'cont_valorinicial',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_objeto',
'contnumero',
'prenumero',
'cont_catalogo_presupuestal',
'cont_fechafinal',
'cont_valormensual',
'cont_ano' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'prenumero',
'pre_contnumero',
'numregistro',
'contnumero',
'cont_valormensual',
'cont_valorinicial',
'cont_secop_proceso',
'cont_secop_enlace',
'cont_plazo',
'cont_periodicidad',
'cont_obligaciones',
'cont_objeto',
'cont_fechafinal',
'cont_fecha_inicio',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_ano' ),
'filterFields' => array(  ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'cont_secop_enlace' => array( 'simple_grid_field61',
'simple_grid_field64' ),
'cont_secop_proceso' => array( 'simple_grid_field60',
'simple_grid_field63' ),
'cont_objeto' => array( 'simple_grid_field55',
'simple_grid_field58' ),
'cont_valormensual' => array( 'simple_grid_field30',
'simple_grid_field32' ),
'cont_valorinicial' => array( 'simple_grid_field29',
'simple_grid_field31' ),
'cont_fechafinal' => array( 'simple_grid_field20',
'simple_grid_field22' ),
'cont_fecha_inicio' => array( 'simple_grid_field19',
'simple_grid_field21' ),
'cont_catalogo_presupuestal' => array( 'simple_grid_field15',
'simple_grid_field17' ),
'cont_codrubro' => array( 'simple_grid_field12',
'simple_grid_field16' ),
'cont_ano' => array( 'simple_grid_field11' ),
'contnumero' => array( 'simple_grid_field8',
'simple_grid_field13' ),
'pre_contnumero' => array( 'simple_grid_field7',
'simple_grid_field10' ),
'numregistro' => array( 'simple_grid_field6',
'simple_grid_field9' ),
'prenumero' => array( 'simple_grid_field5',
'simple_grid_field' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'grid_checkbox',
'grid_edit',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1',
'simple_grid_field16',
'simple_grid_field12',
'simple_grid_field17',
'simple_grid_field15',
'simple_grid_field10',
'simple_grid_field7',
'simple_grid_field13',
'simple_grid_field9',
'simple_grid_field6',
'simple_grid_field',
'simple_grid_field5',
'simple_grid_field21',
'simple_grid_field19',
'simple_grid_field22',
'simple_grid_field20',
'simple_grid_field31',
'simple_grid_field29',
'simple_grid_field32',
'simple_grid_field30',
'simple_grid_field58',
'simple_grid_field55',
'simple_grid_field64',
'simple_grid_field61',
'simple_grid_field8',
'simple_grid_field11',
'simple_grid_field63',
'simple_grid_field60',
'details_preview',
'details_preview1' ),
'top' => array(  ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link' => 'grid',
'grid_details_link1' => 'grid',
'simple_grid_field16' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field17' => 'grid',
'simple_grid_field15' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field13' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field21' => 'grid',
'simple_grid_field19' => 'grid',
'simple_grid_field22' => 'grid',
'simple_grid_field20' => 'grid',
'simple_grid_field31' => 'grid',
'simple_grid_field29' => 'grid',
'simple_grid_field32' => 'grid',
'simple_grid_field30' => 'grid',
'simple_grid_field58' => 'grid',
'simple_grid_field55' => 'grid',
'simple_grid_field64' => 'grid',
'simple_grid_field61' => 'grid',
'simple_grid_field8' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field63' => 'grid',
'simple_grid_field60' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid' ),
'itemLocations' => array( 'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'grid_details_link1' => array( 'location' => 'grid',
'cellId' => 'cell_top' ),
'simple_grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field17' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'simple_grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field18' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field19' ),
'simple_grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field21' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field22' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field23' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field24' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field25' ),
'simple_grid_field21' => array( 'location' => 'grid',
'cellId' => 'cell_label18' ),
'simple_grid_field19' => array( 'location' => 'grid',
'cellId' => 'cell_label19' ),
'simple_grid_field22' => array( 'location' => 'grid',
'cellId' => 'cell_label20' ),
'simple_grid_field20' => array( 'location' => 'grid',
'cellId' => 'cell_label21' ),
'simple_grid_field31' => array( 'location' => 'grid',
'cellId' => 'cell_label22' ),
'simple_grid_field29' => array( 'location' => 'grid',
'cellId' => 'cell_label23' ),
'simple_grid_field32' => array( 'location' => 'grid',
'cellId' => 'cell_label24' ),
'simple_grid_field30' => array( 'location' => 'grid',
'cellId' => 'cell_label25' ),
'simple_grid_field58' => array( 'location' => 'grid',
'cellId' => 'cell_label30' ),
'simple_grid_field55' => array( 'location' => 'grid',
'cellId' => 'cell_label31' ),
'simple_grid_field64' => array( 'location' => 'grid',
'cellId' => 'cell_label32' ),
'simple_grid_field61' => array( 'location' => 'grid',
'cellId' => 'cell_label33' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field26' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field27' ),
'simple_grid_field63' => array( 'location' => 'grid',
'cellId' => 'cell_label34' ),
'simple_grid_field60' => array( 'location' => 'grid',
'cellId' => 'cell_label35' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'grid_field' => array( 'simple_grid_field61',
'simple_grid_field60',
'simple_grid_field55',
'simple_grid_field30',
'simple_grid_field29',
'simple_grid_field20',
'simple_grid_field19',
'simple_grid_field15',
'simple_grid_field12',
'simple_grid_field11',
'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field6',
'simple_grid_field5' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'grid_field_label' => array( 'simple_grid_field',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field13',
'simple_grid_field16',
'simple_grid_field17',
'simple_grid_field21',
'simple_grid_field22',
'simple_grid_field31',
'simple_grid_field32',
'simple_grid_field58',
'simple_grid_field63',
'simple_grid_field64' ),
'search_panel_field' => array( 'search_panel_field3',
'search_panel_field4',
'search_panel_field7',
'search_panel_field14',
'search_panel_field16',
'search_panel_field27',
'search_panel_field28',
'search_panel_field32',
'search_panel_field33',
'search_panel_field39',
'search_panel_field40',
'search_panel_field52',
'search_panel_field53',
'search_panel_field61',
'search_panel_field63',
'search_panel_field64',
'search_panel_field65' ),
'logo' => array( 'logo1' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview',
'details_preview1' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3,
4 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'grid_checkbox',
'grid_edit',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field18' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'pre_contnumero_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field19' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'pre_contnumero_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field21' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'contnumero_fieldheadercolumn' ),
'items' => array( 'simple_grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field26' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'contnumero_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field27' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field22' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'numregistro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field23' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'numregistro_fieldcolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field24' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'prenumero_fieldheadercolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field25' => array( 'cols' => array( 3,
4 ),
'rows' => array( 2 ),
'tags' => array( 'prenumero_fieldcolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'cont_codrubro_fieldheadercolumn' ),
'items' => array( 'simple_grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'cont_codrubro_fieldcolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'cont_catalogo_presupuestal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field17' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3,
4 ),
'rows' => array( 3 ),
'tags' => array( 'cont_catalogo_presupuestal_fieldcolumn' ),
'items' => array( 'simple_grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label18' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'simple_grid_field21' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label19' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'simple_grid_field19' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label20' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field22' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label21' => array( 'cols' => array( 3,
4 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'simple_grid_field20' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label22' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'simple_grid_field31' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label23' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'simple_grid_field29' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label24' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'simple_grid_field32' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label25' => array( 'cols' => array( 3,
4 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'simple_grid_field30' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label34' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_proceso_fieldheadercolumn' ),
'items' => array( 'simple_grid_field63' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label35' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'cont_secop_proceso_fieldcolumn' ),
'items' => array( 'simple_grid_field60' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label36' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label37' => array( 'cols' => array( 3,
4 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label32' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'simple_grid_field64' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label33' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 7 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'simple_grid_field61' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label30' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'simple_grid_field58' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label31' => array( 'cols' => array( 1,
2,
3,
4 ),
'rows' => array( 8 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'simple_grid_field55' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 5,
'height' => 10 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 5 ) ),
'section' => 'head' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field18' ),
array( 'cell' => 'cell_field19' ),
array( 'cell' => 'cell_field21' ),
array( 'cell' => 'cell_field26' ),
array( 'cell' => 'cell_field27',
'colspan' => 1 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_field22' ),
array( 'cell' => 'cell_field23' ),
array( 'cell' => 'cell_field24' ),
array( 'cell' => 'cell_field25',
'colspan' => 2 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1',
'colspan' => 2 ) ),
'section' => 'body' ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label18' ),
array( 'cell' => 'cell_label19' ),
array( 'cell' => 'cell_label20' ),
array( 'cell' => 'cell_label21',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label22' ),
array( 'cell' => 'cell_label23' ),
array( 'cell' => 'cell_label24' ),
array( 'cell' => 'cell_label25',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label34' ),
array( 'cell' => 'cell_label35' ),
array( 'cell' => 'cell_label36' ),
array( 'cell' => 'cell_label37',
'colspan' => 2 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label32' ),
array( 'cell' => 'cell_label33',
'colspan' => 4 ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_label30' ),
array( 'cell' => 'cell_label31',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 8 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array( 'grid_checkbox',
'grid_edit',
'grid_view',
'grid_alldetails_link',
'grid_details_link',
'grid_details_link1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field16' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field17' ),
'field' => 'cont_catalogo_presupuestal',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field15' ),
'field' => 'cont_catalogo_presupuestal',
'columnName' => 'field' ),
'cell_field18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field10' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field13' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field9' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field24' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_field25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_label18' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field21' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label19' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field19' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label20' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field22' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label21' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field20' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label22' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field31' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label23' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field29' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label24' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field32' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label25' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field30' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label30' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field58' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_label31' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field55' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_label32' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field64' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_label33' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field61' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field26' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field27' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_label34' => array( 'model' => 'cell_label',
'items' => array( 'simple_grid_field63' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_label35' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field60' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_label36' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_label37' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array( 'grid_checkbox_head' ),
'buildType' => 2,
'columnCount' => 2 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export' ) ),
'simple_grid_field61' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field60' => array( 'field' => 'cont_secop_proceso',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field55' => array( 'field' => 'cont_objeto',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field30' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field29' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field20' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field19' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field15' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field12' => array( 'field' => 'cont_codrubro',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field11' => array( 'field' => 'cont_ano',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field8' => array( 'field' => 'contnumero',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field7' => array( 'field' => 'pre_contnumero',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'field' => 'numregistro',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'field' => 'prenumero',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add' ),
'grid_edit' => array( 'type' => 'grid_edit' ),
'grid_view' => array( 'type' => 'grid_view' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field65',
'search_panel_field64',
'search_panel_field63',
'search_panel_field61',
'search_panel_field53',
'search_panel_field52',
'search_panel_field40',
'search_panel_field39',
'search_panel_field33',
'search_panel_field32',
'search_panel_field28',
'search_panel_field27',
'search_panel_field16',
'search_panel_field14',
'search_panel_field7',
'search_panel_field4',
'search_panel_field3' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'simple_grid_field' => array( 'type' => 'grid_field_label',
'field' => 'prenumero' ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'numregistro' ),
'search_panel_field3' => array( 'field' => 'cont_ano',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'pre_contnumero' ),
'simple_grid_field13' => array( 'type' => 'grid_field_label',
'field' => 'contnumero' ),
'search_panel_field7' => array( 'field' => 'cont_codrubro',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field16' => array( 'type' => 'grid_field_label',
'field' => 'cont_codrubro' ),
'simple_grid_field17' => array( 'type' => 'grid_field_label',
'field' => 'cont_catalogo_presupuestal' ),
'simple_grid_field21' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'simple_grid_field22' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'search_panel_field14' => array( 'field' => 'cont_fecha_inicio',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field31' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'search_panel_field16' => array( 'field' => 'cont_fechafinal',
'type' => 'search_panel_field',
'required' => false ),
'simple_grid_field32' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'simple_grid_field58' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'simple_grid_field63' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_proceso' ),
'simple_grid_field64' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'search_panel_field27' => array( 'field' => 'cont_objeto',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field28' => array( 'field' => 'cont_obligaciones',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field32' => array( 'field' => 'cont_periodicidad',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field33' => array( 'field' => 'cont_plazo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'cont_secop_enlace',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field40' => array( 'field' => 'cont_secop_proceso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'cont_valorinicial',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'cont_valormensual',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'contnumero',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field63' => array( 'field' => 'numregistro',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field64' => array( 'field' => 'pre_contnumero',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field65' => array( 'field' => 'prenumero',
'type' => 'search_panel_field',
'required' => false ),
'logo1' => array( 'type' => 'logo' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link',
'text' => array( 'type' => 0,
'text' => '' ),
'icon' => array( 'glyph' => 'th-list' ) ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'q_consulta_op' => true,
'contrato_attached' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'q_consulta_op',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'q_consulta_op',
'badge' => true,
'showCount' => true,
'hideIfNone' => false,
'text' => array( 'text' => 'Pagos',
'type' => 0 ),
'icon' => array( 'fa' => 'usd' ) ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'contrato_attached',
'items' => array(  ),
'popup' => false,
'proceedLink' => true,
'hideEmptyPreview' => false,
'pageId' => 'list' ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'contrato_attached',
'badge' => true,
'showCount' => true,
'hideIfNone' => false,
'text' => array( 'text' => 'Anexos',
'type' => 0 ),
'icon' => array( 'fa' => 'files-o' ) ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>