<?php
			$optionsArray = array( 'totals' => array( 'contractor_id' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'contractor_doc_id' => array( 'totalsType' => '' ),
'contractor_doc_dv' => array( 'totalsType' => '' ),
'contractor_pwd' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_image' => array( 'totalsType' => '' ),
'enlace_sigep' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_address' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'contractor_city' => array( 'totalsType' => '' ),
'contractor_sup_jerarquico' => array( 'totalsType' => '' ),
'contractor_dependencia' => array( 'totalsType' => '' ),
'bank_name' => array( 'totalsType' => '' ),
'bank_cta_type' => array( 'totalsType' => '' ),
'bank_cta_number' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'factura' => array( 'totalsType' => '' ),
'actividad_economica' => array( 'totalsType' => '' ),
'responsabilidades' => array( 'totalsType' => '' ),
'sys_update' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_level' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'sys_last_upd' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'contractor_dependientes' => array( 'totalsType' => '' ),
'contractor_medicinapre_file' => array( 'totalsType' => '' ),
'contractor_picmonetaria_file' => array( 'totalsType' => '' ),
'contractor_decljur' => array( 'totalsType' => '' ),
'contractor_eps' => array( 'totalsType' => '' ),
'contractor_fondopensiones' => array( 'totalsType' => '' ),
'contractor_cajacompensacion' => array( 'totalsType' => '' ),
'contractor_arl' => array( 'totalsType' => '' ),
'ubica_dep' => array( 'totalsType' => '' ),
'ubica_extension' => array( 'totalsType' => '' ),
'dem_genero' => array( 'totalsType' => '' ),
'dem_ocupacion' => array( 'totalsType' => '' ),
'dem_profesion' => array( 'totalsType' => '' ),
'ct_fecha_nacimiento' => array( 'totalsType' => '' ),
'ct_fecha_nacimiento_mun' => array( 'totalsType' => '' ),
'ct_nacionalidad' => array( 'totalsType' => '' ),
'dem_edad' => array( 'totalsType' => '' ),
'dem_educacion' => array( 'totalsType' => '' ),
'dem_discapacidad' => array( 'totalsType' => '' ),
'emergencia' => array( 'totalsType' => '' ),
'terms_msj' => array( 'totalsType' => '' ),
'terms_acepta' => array( 'totalsType' => '' ),
'signature' => array( 'totalsType' => '' ),
'pin' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'contractor_id',
'contractor_type',
'contractor_doc_id',
'contractor_doc_dv',
'contractor_pwd',
'contractor_image',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'enlace_sigep',
'contractor_email',
'contractor_email_mincit',
'contractor_address',
'contractor_phone',
'contractor_mobile',
'contractor_city',
'bank_name',
'bank_cta_type',
'bank_cta_number',
'iva_regimen',
'sys_update',
'sys_user',
'sys_date',
'sys_level',
'sys_status',
'sys_last_upd',
'groupid',
'active',
'contractor_dependientes',
'contractor_medicinapre_file',
'contractor_picmonetaria_file',
'contractor_decljur',
'contractor_eps',
'contractor_fondopensiones',
'contractor_cajacompensacion',
'contractor_arl',
'ubica_dep',
'ubica_extension',
'dem_genero',
'dem_ocupacion',
'ct_fecha_nacimiento',
'ct_nacionalidad',
'dem_edad',
'dem_educacion',
'dem_discapacidad',
'emergencia',
'terms_msj',
'terms_acepta',
'contractor_sup_jerarquico',
'contractor_dependencia',
'dem_profesion',
'signature',
'pin',
'ct_fecha_nacimiento_mun',
'factura',
'actividad_economica',
'responsabilidades',
'reset_token',
'reset_date' ),
'exportFields' => array( 'contractor_id',
'contractor_type',
'contractor_doc_id',
'contractor_doc_dv',
'contractor_pwd',
'contractor_image',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'enlace_sigep',
'contractor_email',
'contractor_email_mincit',
'contractor_address',
'contractor_phone',
'contractor_mobile',
'contractor_city',
'bank_name',
'bank_cta_type',
'bank_cta_number',
'iva_regimen',
'sys_update',
'sys_user',
'sys_date',
'sys_level',
'sys_status',
'sys_last_upd',
'groupid',
'active',
'contractor_dependientes',
'contractor_medicinapre_file',
'contractor_picmonetaria_file',
'contractor_decljur',
'contractor_eps',
'contractor_fondopensiones',
'contractor_cajacompensacion',
'contractor_arl',
'ubica_dep',
'ubica_extension',
'dem_genero',
'dem_ocupacion',
'ct_fecha_nacimiento',
'ct_nacionalidad',
'dem_edad',
'dem_educacion',
'dem_discapacidad',
'emergencia',
'terms_msj',
'terms_acepta',
'contractor_sup_jerarquico',
'contractor_dependencia',
'dem_profesion',
'signature',
'pin',
'ct_fecha_nacimiento_mun',
'factura',
'actividad_economica',
'responsabilidades',
'reset_token',
'reset_date' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'contractor_id' => array( 'export_field' ),
'contractor_type' => array( 'export_field1' ),
'contractor_doc_id' => array( 'export_field2' ),
'contractor_doc_dv' => array( 'export_field3' ),
'contractor_pwd' => array( 'export_field4' ),
'contractor_image' => array( 'export_field5' ),
'contractor_name' => array( 'export_field6' ),
'contractor_lname' => array( 'export_field7' ),
'contractor_nombresfull' => array( 'export_field8' ),
'enlace_sigep' => array( 'export_field9' ),
'contractor_email' => array( 'export_field10' ),
'contractor_email_mincit' => array( 'export_field11' ),
'contractor_address' => array( 'export_field12' ),
'contractor_phone' => array( 'export_field13' ),
'contractor_mobile' => array( 'export_field14' ),
'contractor_city' => array( 'export_field15' ),
'bank_name' => array( 'export_field16' ),
'bank_cta_type' => array( 'export_field17' ),
'bank_cta_number' => array( 'export_field18' ),
'iva_regimen' => array( 'export_field19' ),
'sys_update' => array( 'export_field20' ),
'sys_user' => array( 'export_field21' ),
'sys_date' => array( 'export_field22' ),
'sys_level' => array( 'export_field24' ),
'sys_status' => array( 'export_field25' ),
'sys_last_upd' => array( 'export_field27' ),
'groupid' => array( 'export_field28' ),
'active' => array( 'export_field29' ),
'contractor_dependientes' => array( 'export_field32' ),
'contractor_medicinapre_file' => array( 'export_field33' ),
'contractor_picmonetaria_file' => array( 'export_field34' ),
'contractor_decljur' => array( 'export_field35' ),
'contractor_eps' => array( 'export_field38' ),
'contractor_fondopensiones' => array( 'export_field39' ),
'contractor_cajacompensacion' => array( 'export_field40' ),
'contractor_arl' => array( 'export_field41' ),
'ubica_dep' => array( 'export_field42' ),
'ubica_extension' => array( 'export_field43' ),
'dem_genero' => array( 'export_field44' ),
'dem_ocupacion' => array( 'export_field45' ),
'ct_fecha_nacimiento' => array( 'export_field46' ),
'ct_nacionalidad' => array( 'export_field47' ),
'dem_edad' => array( 'export_field49' ),
'dem_educacion' => array( 'export_field50' ),
'dem_discapacidad' => array( 'export_field51' ),
'emergencia' => array( 'export_field52' ),
'terms_msj' => array( 'export_field54' ),
'terms_acepta' => array( 'export_field55' ),
'contractor_sup_jerarquico' => array( 'export_field23' ),
'contractor_dependencia' => array( 'export_field26' ),
'dem_profesion' => array( 'export_field30' ),
'signature' => array( 'export_field31' ),
'pin' => array( 'export_field36' ),
'ct_fecha_nacimiento_mun' => array( 'export_field37' ),
'factura' => array( 'export_field48' ),
'actividad_economica' => array( 'export_field53' ),
'responsabilidades' => array( 'export_field56' ),
'reset_token' => array( 'export_field57' ),
'reset_date' => array( 'export_field58' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field27',
'export_field28',
'export_field29',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field54',
'export_field55',
'export_field23',
'export_field26',
'export_field30',
'export_field31',
'export_field36',
'export_field37',
'export_field48',
'export_field53',
'export_field56',
'export_field57',
'export_field58' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field23' => 'grid',
'export_field26' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field48' => 'grid',
'export_field53' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field27',
'export_field28',
'export_field29',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field54',
'export_field55',
'export_field23',
'export_field26',
'export_field30',
'export_field31',
'export_field36',
'export_field37',
'export_field48',
'export_field53',
'export_field56',
'export_field57',
'export_field58' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field24',
'export_field25',
'export_field27',
'export_field28',
'export_field29',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field54',
'export_field55',
'export_field23',
'export_field26',
'export_field30',
'export_field31',
'export_field36',
'export_field37',
'export_field48',
'export_field53',
'export_field56',
'export_field57',
'export_field58' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'contractor_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'contractor_type',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'contractor_doc_id',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'contractor_doc_dv',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'contractor_pwd',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'contractor_image',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'contractor_name',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'contractor_lname',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'enlace_sigep',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'contractor_email_mincit',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'contractor_address',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'contractor_phone',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'contractor_mobile',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'contractor_city',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'bank_name',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'bank_cta_type',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'bank_cta_number',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'iva_regimen',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'sys_update',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'sys_date',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'sys_level',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'sys_status',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'sys_last_upd',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'groupid',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'active',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'contractor_dependientes',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'contractor_medicinapre_file',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'contractor_picmonetaria_file',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'contractor_decljur',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'contractor_eps',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'contractor_fondopensiones',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'contractor_cajacompensacion',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'contractor_arl',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'ubica_dep',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'ubica_extension',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'dem_genero',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'dem_ocupacion',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'ct_fecha_nacimiento',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'ct_nacionalidad',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'dem_edad',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'dem_educacion',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'dem_discapacidad',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'emergencia',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'terms_msj',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'terms_acepta',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'contractor_sup_jerarquico',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'contractor_dependencia',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'dem_profesion',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'signature',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'pin',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'ct_fecha_nacimiento_mun',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'factura',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'actividad_economica',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'responsabilidades',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'reset_token',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'reset_date',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>