<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'details' => array( 'q_consulta_op' => array( 'displayPreview' => 1 ),
'contrato_attached' => array( 'displayPreview' => 1 ) ),
'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_reg_sigep' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_plazoi' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_otrosi' => array( 'totalsType' => '' ),
'cont_otrosi_type' => array( 'totalsType' => '' ),
'cont_valorant' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_valorvigente' => array( 'totalsType' => '' ),
'cont_valors' => array( 'totalsType' => '' ),
'cont_lugar' => array( 'totalsType' => '' ),
'cont_region' => array( 'totalsType' => '' ),
'cont_requactaliq' => array( 'totalsType' => '' ),
'cont_plazol' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_formapago' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_funcion' => array( 'totalsType' => '' ),
'cesion_estado' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_afilia_arl' => array( 'totalsType' => '' ),
'cont_excluir_notificacion' => array( 'totalsType' => '' ),
'cont_depsup' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'cont_lugar_prestacion' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'cont_tipo_regimen' => array( 'totalsType' => '' ),
'cont_fecha_firma' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_sigep' => array( 'totalsType' => '' ),
'cont_vigencias_futuras' => array( 'totalsType' => '' ),
'vf_num_autorizacion' => array( 'totalsType' => '' ),
'vf_fecha' => array( 'totalsType' => '' ),
'vf_valor' => array( 'totalsType' => '' ),
'cont_fechasistema' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'cont_plazo',
'cont_fechafinal',
'cont_obligaciones',
'prenumero',
'cont_secop_enlace',
'cont_valormensual',
'cont_ano',
'cont_fecha_inicio',
'numregistro',
'cont_periodicidad',
'contnumero',
'cont_catalogo_presupuestal',
'cont_codrubro',
'cont_objeto',
'pre_contnumero',
'cont_valorinicial',
'cont_secop_proceso' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'cont_plazo' => array( 'grid_field13',
'grid_field_label13' ),
'cont_obligaciones' => array( 'grid_field_label1',
'grid_field1' ),
'prenumero' => array( 'grid_field_label5',
'grid_field5' ),
'cont_fechafinal' => array( 'grid_field9',
'grid_field_label9' ),
'cont_secop_enlace' => array( 'grid_field_label14',
'grid_field14' ),
'cont_periodicidad' => array( 'grid_field_label10',
'grid_field10' ),
'contnumero' => array( 'grid_field_label3',
'grid_field3' ),
'cont_catalogo_presupuestal' => array( 'grid_field_label7',
'grid_field7' ),
'cont_valormensual' => array( 'grid_field11',
'grid_field_label11' ),
'cont_ano' => array( 'grid_field15',
'grid_field_label15' ),
'cont_fecha_inicio' => array( 'grid_field6',
'grid_field_label6' ),
'numregistro' => array( 'grid_field2',
'grid_field_label2' ),
'cont_objeto' => array( 'grid_field_label16',
'grid_field16' ),
'cont_codrubro' => array( 'grid_field4',
'grid_field_label4' ),
'cont_secop_proceso' => array( 'grid_field_label12',
'grid_field12' ),
'pre_contnumero' => array( 'grid_field',
'grid_field_label' ),
'cont_valorinicial' => array( 'grid_field8',
'grid_field_label8' ) ),
'hideEmptyFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'print_header',
'print_subheader' ),
'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'grid' => array( 'grid_field_label',
'grid_field',
'grid_field_label1',
'grid_field1',
'grid_field_label2',
'grid_field2',
'grid_field_label3',
'grid_field3',
'grid_field_label4',
'grid_field4',
'grid_field_label5',
'grid_field5',
'grid_field_label6',
'grid_field6',
'grid_field_label7',
'grid_field7',
'grid_field_label8',
'grid_field8',
'grid_field_label9',
'grid_field9',
'grid_field_label10',
'grid_field10',
'grid_field_label11',
'grid_field11',
'grid_field_label12',
'grid_field12',
'grid_field_label13',
'grid_field13',
'grid_field_label14',
'grid_field14',
'grid_field_label15',
'grid_field15',
'grid_field_label16',
'grid_field16',
'details_preview',
'details_preview1' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_header' => 'top',
'print_subheader' => 'top',
'print_pages' => 'above-grid',
'grid_field_label' => 'grid',
'grid_field' => 'grid',
'grid_field_label1' => 'grid',
'grid_field1' => 'grid',
'grid_field_label2' => 'grid',
'grid_field2' => 'grid',
'grid_field_label3' => 'grid',
'grid_field3' => 'grid',
'grid_field_label4' => 'grid',
'grid_field4' => 'grid',
'grid_field_label5' => 'grid',
'grid_field5' => 'grid',
'grid_field_label6' => 'grid',
'grid_field6' => 'grid',
'grid_field_label7' => 'grid',
'grid_field7' => 'grid',
'grid_field_label8' => 'grid',
'grid_field8' => 'grid',
'grid_field_label9' => 'grid',
'grid_field9' => 'grid',
'grid_field_label10' => 'grid',
'grid_field10' => 'grid',
'grid_field_label11' => 'grid',
'grid_field11' => 'grid',
'grid_field_label12' => 'grid',
'grid_field12' => 'grid',
'grid_field_label13' => 'grid',
'grid_field13' => 'grid',
'grid_field_label14' => 'grid',
'grid_field14' => 'grid',
'grid_field_label15' => 'grid',
'grid_field15' => 'grid',
'grid_field_label16' => 'grid',
'grid_field16' => 'grid',
'details_preview' => 'grid',
'details_preview1' => 'grid' ),
'itemLocations' => array( 'grid_field_label' => array( 'location' => 'grid',
'cellId' => 'cell_label' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'grid_field_label1' => array( 'location' => 'grid',
'cellId' => 'cell_label1' ),
'grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'grid_field_label2' => array( 'location' => 'grid',
'cellId' => 'cell_label2' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'grid_field_label3' => array( 'location' => 'grid',
'cellId' => 'cell_label3' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field_label4' => array( 'location' => 'grid',
'cellId' => 'cell_label4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field_label5' => array( 'location' => 'grid',
'cellId' => 'cell_label5' ),
'grid_field5' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_field_label6' => array( 'location' => 'grid',
'cellId' => 'cell_label6' ),
'grid_field6' => array( 'location' => 'grid',
'cellId' => 'cell_field6' ),
'grid_field_label7' => array( 'location' => 'grid',
'cellId' => 'cell_label7' ),
'grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field7' ),
'grid_field_label8' => array( 'location' => 'grid',
'cellId' => 'cell_label8' ),
'grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'grid_field_label9' => array( 'location' => 'grid',
'cellId' => 'cell_label9' ),
'grid_field9' => array( 'location' => 'grid',
'cellId' => 'cell_field9' ),
'grid_field_label10' => array( 'location' => 'grid',
'cellId' => 'cell_label10' ),
'grid_field10' => array( 'location' => 'grid',
'cellId' => 'cell_field10' ),
'grid_field_label11' => array( 'location' => 'grid',
'cellId' => 'cell_label11' ),
'grid_field11' => array( 'location' => 'grid',
'cellId' => 'cell_field11' ),
'grid_field_label12' => array( 'location' => 'grid',
'cellId' => 'cell_label12' ),
'grid_field12' => array( 'location' => 'grid',
'cellId' => 'cell_field12' ),
'grid_field_label13' => array( 'location' => 'grid',
'cellId' => 'cell_label13' ),
'grid_field13' => array( 'location' => 'grid',
'cellId' => 'cell_field13' ),
'grid_field_label14' => array( 'location' => 'grid',
'cellId' => 'cell_label14' ),
'grid_field14' => array( 'location' => 'grid',
'cellId' => 'cell_field14' ),
'grid_field_label15' => array( 'location' => 'grid',
'cellId' => 'cell_label15' ),
'grid_field15' => array( 'location' => 'grid',
'cellId' => 'cell_field15' ),
'grid_field_label16' => array( 'location' => 'grid',
'cellId' => 'cell_label16' ),
'grid_field16' => array( 'location' => 'grid',
'cellId' => 'cell_field16' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'grid_field' => array( 'grid_field13',
'grid_field9',
'grid_field1',
'grid_field5',
'grid_field14',
'grid_field11',
'grid_field15',
'grid_field6',
'grid_field2',
'grid_field10',
'grid_field3',
'grid_field7',
'grid_field4',
'grid_field16',
'grid_field',
'grid_field8',
'grid_field12' ),
'grid_field_label' => array( 'grid_field_label1',
'grid_field_label5',
'grid_field_label14',
'grid_field_label10',
'grid_field_label3',
'grid_field_label7',
'grid_field_label11',
'grid_field_label15',
'grid_field_label6',
'grid_field_label2',
'grid_field_label16',
'grid_field_label9',
'grid_field_label12',
'grid_field_label13',
'grid_field_label4',
'grid_field_label',
'grid_field_label8' ),
'details_preview' => array( 'details_preview',
'details_preview1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'cell_top' => array( 'cols' => array( 0,
1,
2,
3 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'pre_contnumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'pre_contnumero_fieldcolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'cont_obligaciones_fieldheadercolumn' ),
'items' => array( 'grid_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'cont_obligaciones_fieldcolumn' ),
'items' => array( 'grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'numregistro_fieldheadercolumn' ),
'items' => array( 'grid_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array( 'numregistro_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label3' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array( 'contnumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array( 'contnumero_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label4' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array( 'cont_codrubro_fieldheadercolumn' ),
'items' => array( 'grid_field_label4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array( 'cont_codrubro_fieldcolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label5' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array( 'prenumero_fieldheadercolumn' ),
'items' => array( 'grid_field_label5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array( 'prenumero_fieldcolumn' ),
'items' => array( 'grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldheadercolumn' ),
'items' => array( 'grid_field_label6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field6' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array( 'cont_fecha_inicio_fieldcolumn' ),
'items' => array( 'grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label7' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array( 'cont_catalogo_presupuestal_fieldheadercolumn' ),
'items' => array( 'grid_field_label7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field7' => array( 'cols' => array( 3 ),
'rows' => array( 4 ),
'tags' => array( 'cont_catalogo_presupuestal_fieldcolumn' ),
'items' => array( 'grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label8' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldheadercolumn' ),
'items' => array( 'grid_field_label8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array( 'cont_valorinicial_fieldcolumn' ),
'items' => array( 'grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label9' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array( 'cont_fechafinal_fieldheadercolumn' ),
'items' => array( 'grid_field_label9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field9' => array( 'cols' => array( 3 ),
'rows' => array( 5 ),
'tags' => array( 'cont_fechafinal_fieldcolumn' ),
'items' => array( 'grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label10' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array( 'cont_periodicidad_fieldheadercolumn' ),
'items' => array( 'grid_field_label10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field10' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array( 'cont_periodicidad_fieldcolumn' ),
'items' => array( 'grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label11' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array( 'cont_valormensual_fieldheadercolumn' ),
'items' => array( 'grid_field_label11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field11' => array( 'cols' => array( 3 ),
'rows' => array( 6 ),
'tags' => array( 'cont_valormensual_fieldcolumn' ),
'items' => array( 'grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label12' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array( 'cont_secop_proceso_fieldheadercolumn' ),
'items' => array( 'grid_field_label12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field12' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array( 'cont_secop_proceso_fieldcolumn' ),
'items' => array( 'grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label13' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array( 'cont_plazo_fieldheadercolumn' ),
'items' => array( 'grid_field_label13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field13' => array( 'cols' => array( 3 ),
'rows' => array( 7 ),
'tags' => array( 'cont_plazo_fieldcolumn' ),
'items' => array( 'grid_field13' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label14' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array( 'cont_secop_enlace_fieldheadercolumn' ),
'items' => array( 'grid_field_label14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field14' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array( 'cont_secop_enlace_fieldcolumn' ),
'items' => array( 'grid_field14' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label15' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array( 'cont_ano_fieldheadercolumn' ),
'items' => array( 'grid_field_label15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field15' => array( 'cols' => array( 3 ),
'rows' => array( 8 ),
'tags' => array( 'cont_ano_fieldcolumn' ),
'items' => array( 'grid_field15' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label16' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array( 'cont_objeto_fieldheadercolumn' ),
'items' => array( 'grid_field_label16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field16' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array( 'cont_objeto_fieldcolumn' ),
'items' => array( 'grid_field16' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_label17' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field17' => array( 'cols' => array( 3 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5 ),
'rows' => array( 10 ),
'tags' => array(  ),
'items' => array( 'details_preview',
'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 4,
'height' => 11 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'gridType' => 2,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'print',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'print',
'type' => 'print',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'columns-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_top',
'colspan' => 4 ) ),
'section' => 'head' ),
array( 'cells' => array( array( 'cell' => 'cell_label' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_label1' ),
array( 'cell' => 'cell_field1' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label2' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_label3' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label4' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_label5' ),
array( 'cell' => 'cell_field5' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label6' ),
array( 'cell' => 'cell_field6' ),
array( 'cell' => 'cell_label7' ),
array( 'cell' => 'cell_field7' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label8' ),
array( 'cell' => 'cell_field8' ),
array( 'cell' => 'cell_label9' ),
array( 'cell' => 'cell_field9' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label10' ),
array( 'cell' => 'cell_field10' ),
array( 'cell' => 'cell_label11' ),
array( 'cell' => 'cell_field11' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label12' ),
array( 'cell' => 'cell_field12' ),
array( 'cell' => 'cell_label13' ),
array( 'cell' => 'cell_field13' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label14' ),
array( 'cell' => 'cell_field14' ),
array( 'cell' => 'cell_label15' ),
array( 'cell' => 'cell_field15' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_label16' ),
array( 'cell' => 'cell_field16' ),
array( 'cell' => 'cell_label17' ),
array( 'cell' => 'cell_field17' ) ),
'section' => 'body' ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 6 ) ),
'section' => 'foot' ) ),
'cells' => array( 'cell_top' => array( 'model' => 'cell_top',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'cell_label' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'grid_field' ),
'field' => 'pre_contnumero',
'columnName' => 'field' ),
'cell_label1' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label1' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'grid_field1' ),
'field' => 'cont_obligaciones',
'columnName' => 'field' ),
'cell_label2' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label2' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'numregistro',
'columnName' => 'field' ),
'cell_label3' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label3' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'contnumero',
'columnName' => 'field' ),
'cell_label4' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label4' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field4' ),
'field' => 'cont_codrubro',
'columnName' => 'field' ),
'cell_label5' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label5' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field5' ),
'field' => 'prenumero',
'columnName' => 'field' ),
'cell_label6' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label6' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_field6' => array( 'model' => 'cell_field',
'items' => array( 'grid_field6' ),
'field' => 'cont_fecha_inicio',
'columnName' => 'field' ),
'cell_label7' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label7' ),
'field' => 'cont_catalogo_presupuestal',
'columnName' => 'field' ),
'cell_field7' => array( 'model' => 'cell_field',
'items' => array( 'grid_field7' ),
'field' => 'cont_catalogo_presupuestal',
'columnName' => 'field' ),
'cell_label8' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label8' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'grid_field8' ),
'field' => 'cont_valorinicial',
'columnName' => 'field' ),
'cell_label9' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label9' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_field9' => array( 'model' => 'cell_field',
'items' => array( 'grid_field9' ),
'field' => 'cont_fechafinal',
'columnName' => 'field' ),
'cell_label10' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label10' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_field10' => array( 'model' => 'cell_field',
'items' => array( 'grid_field10' ),
'field' => 'cont_periodicidad',
'columnName' => 'field' ),
'cell_label11' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label11' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_field11' => array( 'model' => 'cell_field',
'items' => array( 'grid_field11' ),
'field' => 'cont_valormensual',
'columnName' => 'field' ),
'cell_label12' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label12' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_field12' => array( 'model' => 'cell_field',
'items' => array( 'grid_field12' ),
'field' => 'cont_secop_proceso',
'columnName' => 'field' ),
'cell_label13' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label13' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'cell_field13' => array( 'model' => 'cell_field',
'items' => array( 'grid_field13' ),
'field' => 'cont_plazo',
'columnName' => 'field' ),
'cell_label14' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label14' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_field14' => array( 'model' => 'cell_field',
'items' => array( 'grid_field14' ),
'field' => 'cont_secop_enlace',
'columnName' => 'field' ),
'cell_label15' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label15' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_field15' => array( 'model' => 'cell_field',
'items' => array( 'grid_field15' ),
'field' => 'cont_ano',
'columnName' => 'field' ),
'cell_label16' => array( 'model' => 'cell_label',
'items' => array( 'grid_field_label16' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_field16' => array( 'model' => 'cell_field',
'items' => array( 'grid_field16' ),
'field' => 'cont_objeto',
'columnName' => 'field' ),
'cell_label17' => array( 'model' => 'cell_label',
'items' => array(  ) ),
'cell_field17' => array( 'model' => 'cell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview',
'details_preview1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'buildType' => 2,
'columnCount' => 2 ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'grid_field13' => array( 'field' => 'cont_plazo',
'type' => 'grid_field' ),
'grid_field_label1' => array( 'type' => 'grid_field_label',
'field' => 'cont_obligaciones' ),
'grid_field_label5' => array( 'type' => 'grid_field_label',
'field' => 'prenumero' ),
'grid_field9' => array( 'field' => 'cont_fechafinal',
'type' => 'grid_field' ),
'grid_field_label14' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_enlace' ),
'grid_field1' => array( 'field' => 'cont_obligaciones',
'type' => 'grid_field' ),
'grid_field5' => array( 'field' => 'prenumero',
'type' => 'grid_field' ),
'grid_field_label10' => array( 'type' => 'grid_field_label',
'field' => 'cont_periodicidad' ),
'grid_field14' => array( 'field' => 'cont_secop_enlace',
'type' => 'grid_field' ),
'grid_field_label3' => array( 'type' => 'grid_field_label',
'field' => 'contnumero' ),
'grid_field_label7' => array( 'type' => 'grid_field_label',
'field' => 'cont_catalogo_presupuestal' ),
'grid_field11' => array( 'field' => 'cont_valormensual',
'type' => 'grid_field' ),
'grid_field15' => array( 'field' => 'cont_ano',
'type' => 'grid_field' ),
'grid_field_label11' => array( 'type' => 'grid_field_label',
'field' => 'cont_valormensual' ),
'grid_field6' => array( 'field' => 'cont_fecha_inicio',
'type' => 'grid_field' ),
'grid_field2' => array( 'field' => 'numregistro',
'type' => 'grid_field' ),
'grid_field_label15' => array( 'type' => 'grid_field_label',
'field' => 'cont_ano' ),
'grid_field10' => array( 'field' => 'cont_periodicidad',
'type' => 'grid_field' ),
'grid_field_label6' => array( 'type' => 'grid_field_label',
'field' => 'cont_fecha_inicio' ),
'grid_field_label2' => array( 'type' => 'grid_field_label',
'field' => 'numregistro' ),
'grid_field_label16' => array( 'type' => 'grid_field_label',
'field' => 'cont_objeto' ),
'grid_field3' => array( 'field' => 'contnumero',
'type' => 'grid_field' ),
'grid_field7' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'grid_field' ),
'grid_field_label9' => array( 'type' => 'grid_field_label',
'field' => 'cont_fechafinal' ),
'grid_field4' => array( 'field' => 'cont_codrubro',
'type' => 'grid_field' ),
'grid_field_label12' => array( 'type' => 'grid_field_label',
'field' => 'cont_secop_proceso' ),
'grid_field16' => array( 'field' => 'cont_objeto',
'type' => 'grid_field' ),
'grid_field' => array( 'field' => 'pre_contnumero',
'type' => 'grid_field' ),
'grid_field_label13' => array( 'type' => 'grid_field_label',
'field' => 'cont_plazo' ),
'grid_field8' => array( 'field' => 'cont_valorinicial',
'type' => 'grid_field' ),
'grid_field_label4' => array( 'type' => 'grid_field_label',
'field' => 'cont_codrubro' ),
'grid_field_label' => array( 'type' => 'grid_field_label',
'field' => 'pre_contnumero' ),
'grid_field12' => array( 'field' => 'cont_secop_proceso',
'type' => 'grid_field' ),
'grid_field_label8' => array( 'type' => 'grid_field_label',
'field' => 'cont_valorinicial' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'q_consulta_op',
'items' => array(  ),
'popup' => false ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'contrato_attached',
'items' => array(  ),
'popup' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>