<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_nit_contra_ta' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'prenumero' => array( 'totalsType' => '' ),
'numregistro' => array( 'totalsType' => '' ),
'pre_contnumero' => array( 'totalsType' => '' ),
'contnumero' => array( 'totalsType' => '' ),
'cont_unspsc' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'cont_ano' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipo_rubro' => array( 'totalsType' => '' ),
'cont_reg_sigep' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'cont_plazoi' => array( 'totalsType' => '' ),
'cont_fecha_inicio' => array( 'totalsType' => '' ),
'cont_fechafinal' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'cont_otrosi' => array( 'totalsType' => '' ),
'cont_otrosi_type' => array( 'totalsType' => '' ),
'cont_valorant' => array( 'totalsType' => '' ),
'cont_valorinicial' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'cont_valorvigente' => array( 'totalsType' => '' ),
'cont_valors' => array( 'totalsType' => '' ),
'cont_lugar' => array( 'totalsType' => '' ),
'cont_region' => array( 'totalsType' => '' ),
'cont_requactaliq' => array( 'totalsType' => '' ),
'cont_plazol' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_formapago' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'cont_funcion' => array( 'totalsType' => '' ),
'cesion_estado' => array( 'totalsType' => '' ),
'cont_acta_liquidacion' => array( 'totalsType' => '' ),
'cont_fecha_aprobgarantia' => array( 'totalsType' => '' ),
'cont_afilia_arl' => array( 'totalsType' => '' ),
'cont_excluir_notificacion' => array( 'totalsType' => '' ),
'cont_depsup' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ),
'cont_lugar_prestacion' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_obligaciones' => array( 'totalsType' => '' ),
'cont_plazo' => array( 'totalsType' => '' ),
'cont_tipo_regimen' => array( 'totalsType' => '' ),
'cont_fecha_firma' => array( 'totalsType' => '' ),
'cont_secop_proceso' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_sigep' => array( 'totalsType' => '' ),
'cont_vigencias_futuras' => array( 'totalsType' => '' ),
'vf_num_autorizacion' => array( 'totalsType' => '' ),
'vf_fecha' => array( 'totalsType' => '' ),
'vf_valor' => array( 'totalsType' => '' ),
'cont_fechasistema' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'cont_secop_proceso',
'cont_secop_enlace' ),
'exportFields' => array( 'prenumero',
'numregistro',
'pre_contnumero',
'contnumero',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_fecha_inicio',
'cont_fechafinal',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'cont_secop_proceso',
'cont_secop_enlace' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'prenumero' => array( 'export_field5' ),
'numregistro' => array( 'export_field6' ),
'pre_contnumero' => array( 'export_field7' ),
'contnumero' => array( 'export_field8' ),
'cont_ano' => array( 'export_field11' ),
'cont_codrubro' => array( 'export_field12' ),
'cont_catalogo_presupuestal' => array( 'export_field15' ),
'cont_fecha_inicio' => array( 'export_field19' ),
'cont_fechafinal' => array( 'export_field20' ),
'cont_periodicidad' => array( 'export_field24' ),
'cont_valorinicial' => array( 'export_field29' ),
'cont_valormensual' => array( 'export_field30' ),
'cont_objeto' => array( 'export_field55' ),
'cont_obligaciones' => array( 'export_field56' ),
'cont_plazo' => array( 'export_field57' ),
'cont_secop_proceso' => array( 'export_field60' ),
'cont_secop_enlace' => array( 'export_field61' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field12',
'export_field15',
'export_field19',
'export_field20',
'export_field24',
'export_field29',
'export_field30',
'export_field55',
'export_field56',
'export_field57',
'export_field60',
'export_field61' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field15' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field24' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field12',
'export_field15',
'export_field19',
'export_field20',
'export_field24',
'export_field29',
'export_field30',
'export_field55',
'export_field56',
'export_field57',
'export_field60',
'export_field61' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field11',
'export_field12',
'export_field15',
'export_field19',
'export_field20',
'export_field24',
'export_field29',
'export_field30',
'export_field55',
'export_field56',
'export_field57',
'export_field60',
'export_field61' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field5' => array( 'field' => 'prenumero',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'numregistro',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'pre_contnumero',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'contnumero',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cont_ano',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cont_codrubro',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'cont_fecha_inicio',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'cont_fechafinal',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'cont_periodicidad',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'cont_valorinicial',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'cont_valormensual',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'cont_objeto',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'cont_obligaciones',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'cont_plazo',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'cont_secop_proceso',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'cont_secop_enlace',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>