<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'username_button' ),
'top' => array(  ),
'grid' => array( 'contractor_master_chart_eps_chart',
'contractor_master_chart_fondopension_chart',
'contractor_master_chart_genero_chart',
'contractor_master_view_list' ) ),
'formXtTags' => array( 'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'username_button' => 'supertop',
'contractor_master_chart_eps_chart' => 'grid',
'contractor_master_chart_fondopension_chart' => 'grid',
'contractor_master_chart_genero_chart' => 'grid',
'contractor_master_view_list' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'list_options' => array( 'list_options' ),
'advsearch_link' => array( 'advsearch_link' ),
'logo' => array( 'logo1' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'userinfo_link' => array( 'userinfo_link' ),
'dashboard-item' => array( 'contractor_master_chart_eps_chart',
'contractor_master_chart_fondopension_chart',
'contractor_master_chart_genero_chart',
'contractor_master_view_list' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_chart_eps',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_eps_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'tag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'elementName' => 'contractor_master_chart_eps_chart',
'table' => 'contractor_master_chart_eps',
'pageName' => '',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_chart_fondopension',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_fondopension_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'elementName' => 'contractor_master_chart_fondopension_chart',
'table' => 'contractor_master_chart_fondopension',
'pageName' => '',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_Chart_genero',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_genero_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'hand-right' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'elementName' => 'contractor_master_chart_genero_chart',
'table' => 'contractor_master_Chart_genero',
'pageName' => '',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_view',
'dashType' => 0,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_view_list',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'send' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'addRecord' => false,
'editRecord' => false,
'viewRecord' => false,
'inlineAdd' => false,
'inlineEdit' => false,
'copyRecord' => false,
'deleteRecords' => false,
'updateSelected' => false ),
'elementName' => 'contractor_master_view_list',
'table' => 'contractor_master_view',
'pageName' => '',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'inlineAdd' => false,
'inlineEdit' => false,
'deleteRecord' => false,
'copy' => false,
'popupAdd' => false,
'popupEdit' => false,
'popupView' => false,
'updateSelected' => false,
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'contractor_master_chart_eps_contractor_eps' => array( array( 'field' => 'contractor_eps',
'table' => 'contractor_master_chart_eps' ) ),
'contractor_master_chart_eps_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_chart_eps' ) ),
'contractor_master_chart_fondopension_contractor_fondopensiones' => array( array( 'field' => 'contractor_fondopensiones',
'table' => 'contractor_master_chart_fondopension' ) ),
'contractor_master_chart_fondopension_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_chart_fondopension' ) ),
'contractor_master_Chart_genero_dem_genero' => array( array( 'field' => 'dem_genero',
'table' => 'contractor_master_Chart_genero' ) ),
'contractor_master_Chart_genero_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_Chart_genero' ) ),
'contractor_master_view_contractor_id' => array( array( 'field' => 'contractor_id',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_type' => array( array( 'field' => 'contractor_type',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_doc_id' => array( array( 'field' => 'contractor_doc_id',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_doc_dv' => array( array( 'field' => 'contractor_doc_dv',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_pwd' => array( array( 'field' => 'contractor_pwd',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_image' => array( array( 'field' => 'contractor_image',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_name' => array( array( 'field' => 'contractor_name',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_lname' => array( array( 'field' => 'contractor_lname',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_nombresfull' => array( array( 'field' => 'contractor_nombresfull',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_enlace_sigep' => array( array( 'field' => 'enlace_sigep',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_email' => array( array( 'field' => 'contractor_email',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_email_mincit' => array( array( 'field' => 'contractor_email_mincit',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_address' => array( array( 'field' => 'contractor_address',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_phone' => array( array( 'field' => 'contractor_phone',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_mobile' => array( array( 'field' => 'contractor_mobile',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_city' => array( array( 'field' => 'contractor_city',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_sup_jerarquico' => array( array( 'field' => 'contractor_sup_jerarquico',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_dependencia' => array( array( 'field' => 'contractor_dependencia',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_name' => array( array( 'field' => 'bank_name',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_cta_type' => array( array( 'field' => 'bank_cta_type',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_cta_number' => array( array( 'field' => 'bank_cta_number',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_iva_regimen' => array( array( 'field' => 'iva_regimen',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_update' => array( array( 'field' => 'sys_update',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_user' => array( array( 'field' => 'sys_user',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_date' => array( array( 'field' => 'sys_date',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_level' => array( array( 'field' => 'sys_level',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_status' => array( array( 'field' => 'sys_status',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_last_upd' => array( array( 'field' => 'sys_last_upd',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_groupid' => array( array( 'field' => 'groupid',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_active' => array( array( 'field' => 'active',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_dependientes' => array( array( 'field' => 'contractor_dependientes',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_medicinapre_file' => array( array( 'field' => 'contractor_medicinapre_file',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_picmonetaria_file' => array( array( 'field' => 'contractor_picmonetaria_file',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_decljur' => array( array( 'field' => 'contractor_decljur',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_eps' => array( array( 'field' => 'contractor_eps',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_fondopensiones' => array( array( 'field' => 'contractor_fondopensiones',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_cajacompensacion' => array( array( 'field' => 'contractor_cajacompensacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_arl' => array( array( 'field' => 'contractor_arl',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ubica_dep' => array( array( 'field' => 'ubica_dep',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ubica_extension' => array( array( 'field' => 'ubica_extension',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_genero' => array( array( 'field' => 'dem_genero',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_ocupacion' => array( array( 'field' => 'dem_ocupacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_profesion' => array( array( 'field' => 'dem_profesion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ct_fecha_nacimiento' => array( array( 'field' => 'ct_fecha_nacimiento',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ct_nacionalidad' => array( array( 'field' => 'ct_nacionalidad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_edad' => array( array( 'field' => 'dem_edad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_educacion' => array( array( 'field' => 'dem_educacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_discapacidad' => array( array( 'field' => 'dem_discapacidad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_emergencia' => array( array( 'field' => 'emergencia',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_terms_msj' => array( array( 'field' => 'terms_msj',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_terms_acepta' => array( array( 'field' => 'terms_acepta',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_signature' => array( array( 'field' => 'signature',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_pin' => array( array( 'field' => 'pin',
'table' => 'contractor_master_view' ) ) ),
'allSearchFields' => array( 'contractor_master_chart_eps_contractor_eps',
'contractor_master_chart_eps_qtygen',
'contractor_master_chart_fondopension_contractor_fondopensiones',
'contractor_master_chart_fondopension_qtygen',
'contractor_master_Chart_genero_dem_genero',
'contractor_master_Chart_genero_qtygen',
'contractor_master_view_contractor_id',
'contractor_master_view_contractor_type',
'contractor_master_view_contractor_doc_id',
'contractor_master_view_contractor_doc_dv',
'contractor_master_view_contractor_pwd',
'contractor_master_view_contractor_image',
'contractor_master_view_contractor_name',
'contractor_master_view_contractor_lname',
'contractor_master_view_contractor_nombresfull',
'contractor_master_view_enlace_sigep',
'contractor_master_view_contractor_email',
'contractor_master_view_contractor_email_mincit',
'contractor_master_view_contractor_address',
'contractor_master_view_contractor_phone',
'contractor_master_view_contractor_mobile',
'contractor_master_view_contractor_city',
'contractor_master_view_contractor_sup_jerarquico',
'contractor_master_view_contractor_dependencia',
'contractor_master_view_bank_name',
'contractor_master_view_bank_cta_type',
'contractor_master_view_bank_cta_number',
'contractor_master_view_iva_regimen',
'contractor_master_view_sys_update',
'contractor_master_view_sys_user',
'contractor_master_view_sys_date',
'contractor_master_view_sys_level',
'contractor_master_view_sys_status',
'contractor_master_view_sys_last_upd',
'contractor_master_view_groupid',
'contractor_master_view_active',
'contractor_master_view_contractor_dependientes',
'contractor_master_view_contractor_medicinapre_file',
'contractor_master_view_contractor_picmonetaria_file',
'contractor_master_view_contractor_decljur',
'contractor_master_view_contractor_eps',
'contractor_master_view_contractor_fondopensiones',
'contractor_master_view_contractor_cajacompensacion',
'contractor_master_view_contractor_arl',
'contractor_master_view_ubica_dep',
'contractor_master_view_ubica_extension',
'contractor_master_view_dem_genero',
'contractor_master_view_dem_ocupacion',
'contractor_master_view_dem_profesion',
'contractor_master_view_ct_fecha_nacimiento',
'contractor_master_view_ct_nacionalidad',
'contractor_master_view_dem_edad',
'contractor_master_view_dem_educacion',
'contractor_master_view_dem_discapacidad',
'contractor_master_view_emergencia',
'contractor_master_view_terms_msj',
'contractor_master_view_terms_acepta',
'contractor_master_view_signature',
'contractor_master_view_pin' ),
'googleLikeFields' => array( 'contractor_master_chart_eps_contractor_eps',
'contractor_master_chart_eps_qtygen',
'contractor_master_chart_fondopension_contractor_fondopensiones',
'contractor_master_chart_fondopension_qtygen',
'contractor_master_Chart_genero_dem_genero',
'contractor_master_Chart_genero_qtygen',
'contractor_master_view_contractor_id',
'contractor_master_view_contractor_type',
'contractor_master_view_contractor_doc_id',
'contractor_master_view_contractor_doc_dv',
'contractor_master_view_contractor_pwd',
'contractor_master_view_contractor_image',
'contractor_master_view_contractor_name',
'contractor_master_view_contractor_lname',
'contractor_master_view_contractor_nombresfull',
'contractor_master_view_enlace_sigep',
'contractor_master_view_contractor_email',
'contractor_master_view_contractor_email_mincit',
'contractor_master_view_contractor_address',
'contractor_master_view_contractor_phone',
'contractor_master_view_contractor_mobile',
'contractor_master_view_contractor_city',
'contractor_master_view_contractor_sup_jerarquico',
'contractor_master_view_contractor_dependencia',
'contractor_master_view_bank_name',
'contractor_master_view_bank_cta_type',
'contractor_master_view_bank_cta_number',
'contractor_master_view_iva_regimen',
'contractor_master_view_sys_update',
'contractor_master_view_sys_user',
'contractor_master_view_sys_date',
'contractor_master_view_sys_level',
'contractor_master_view_sys_status',
'contractor_master_view_sys_last_upd',
'contractor_master_view_groupid',
'contractor_master_view_active',
'contractor_master_view_contractor_dependientes',
'contractor_master_view_contractor_medicinapre_file',
'contractor_master_view_contractor_picmonetaria_file',
'contractor_master_view_contractor_decljur',
'contractor_master_view_contractor_eps',
'contractor_master_view_contractor_fondopensiones',
'contractor_master_view_contractor_cajacompensacion',
'contractor_master_view_contractor_arl',
'contractor_master_view_ubica_dep',
'contractor_master_view_ubica_extension',
'contractor_master_view_dem_genero',
'contractor_master_view_dem_ocupacion',
'contractor_master_view_dem_profesion',
'contractor_master_view_ct_fecha_nacimiento',
'contractor_master_view_ct_nacionalidad',
'contractor_master_view_dem_edad',
'contractor_master_view_dem_educacion',
'contractor_master_view_dem_discapacidad',
'contractor_master_view_emergencia',
'contractor_master_view_terms_msj',
'contractor_master_view_terms_acepta',
'contractor_master_view_signature',
'contractor_master_view_pin' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'cell_0_0',
'colspan' => 2,
'rowspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_1_0',
'colspan' => 2,
'rowspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_2_0',
'colspan' => 1,
'rowspan' => 1 ),
array( 'cell' => 'cell_2_1',
'colspan' => 1,
'rowspan' => 1 ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_3_0',
'colspan' => 2,
'rowspan' => 1 ) ) ) ),
'cells' => array( 'cell_0_0' => array( 'model' => 'c1',
'items' => array( 'contractor_master_chart_eps_chart' ) ),
'cell_1_0' => array( 'model' => 'c1',
'items' => array( 'contractor_master_chart_fondopension_chart' ) ),
'cell_2_0' => array( 'model' => 'c1',
'items' => array( 'contractor_master_chart_genero_chart' ) ),
'cell_2_1' => array( 'model' => 'c1',
'items' => array(  ) ),
'cell_3_0' => array( 'model' => 'c1',
'items' => array( 'contractor_master_view_list' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'advsearch_link' ) ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'logo1' => array( 'type' => 'logo' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'contractor_master_chart_eps_chart' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_chart_eps',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_eps_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'fa' => 'tag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'contractor_master_chart_fondopension_chart' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_chart_fondopension',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_fondopension_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'barcode' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'contractor_master_chart_genero_chart' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_Chart_genero',
'dashType' => 1,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_chart_genero_chart',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'hand-right' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true ),
'contractor_master_view_list' => array( 'type' => 'dashboard-item',
'table' => 'contractor_master_view',
'dashType' => 0,
'reloadInterval' => 0,
'pageId' => '',
'detailsFilterByMaster' => false,
'detailsMasterTable' => '',
'dashName' => 'contractor_master_view_list',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => 'send' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'addRecord' => false,
'editRecord' => false,
'viewRecord' => false,
'inlineAdd' => false,
'inlineEdit' => false,
'copyRecord' => false,
'deleteRecords' => false,
'updateSelected' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>