<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'contractor_master_chart_eps_contractor_eps',
'contractor_master_chart_eps_qtygen' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'contractor_master_chart_eps_contractor_eps' => array( 'integrated_search_field' ),
'contractor_master_chart_eps_qtygen' => array( 'integrated_search_field1' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c1' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashSearch' => array( 'searchFields' => array( 'contractor_master_chart_eps_contractor_eps' => array( array( 'field' => 'contractor_eps',
'table' => 'contractor_master_chart_eps' ) ),
'contractor_master_chart_eps_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_chart_eps' ) ),
'contractor_master_chart_fondopension_contractor_fondopensiones' => array( array( 'field' => 'contractor_fondopensiones',
'table' => 'contractor_master_chart_fondopension' ) ),
'contractor_master_chart_fondopension_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_chart_fondopension' ) ),
'contractor_master_Chart_genero_dem_genero' => array( array( 'field' => 'dem_genero',
'table' => 'contractor_master_Chart_genero' ) ),
'contractor_master_Chart_genero_qtygen' => array( array( 'field' => 'qtygen',
'table' => 'contractor_master_Chart_genero' ) ),
'contractor_master_view_contractor_id' => array( array( 'field' => 'contractor_id',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_type' => array( array( 'field' => 'contractor_type',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_doc_id' => array( array( 'field' => 'contractor_doc_id',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_doc_dv' => array( array( 'field' => 'contractor_doc_dv',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_pwd' => array( array( 'field' => 'contractor_pwd',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_image' => array( array( 'field' => 'contractor_image',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_name' => array( array( 'field' => 'contractor_name',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_lname' => array( array( 'field' => 'contractor_lname',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_nombresfull' => array( array( 'field' => 'contractor_nombresfull',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_enlace_sigep' => array( array( 'field' => 'enlace_sigep',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_email' => array( array( 'field' => 'contractor_email',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_email_mincit' => array( array( 'field' => 'contractor_email_mincit',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_address' => array( array( 'field' => 'contractor_address',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_phone' => array( array( 'field' => 'contractor_phone',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_mobile' => array( array( 'field' => 'contractor_mobile',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_city' => array( array( 'field' => 'contractor_city',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_sup_jerarquico' => array( array( 'field' => 'contractor_sup_jerarquico',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_dependencia' => array( array( 'field' => 'contractor_dependencia',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_name' => array( array( 'field' => 'bank_name',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_cta_type' => array( array( 'field' => 'bank_cta_type',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_bank_cta_number' => array( array( 'field' => 'bank_cta_number',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_iva_regimen' => array( array( 'field' => 'iva_regimen',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_update' => array( array( 'field' => 'sys_update',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_user' => array( array( 'field' => 'sys_user',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_date' => array( array( 'field' => 'sys_date',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_level' => array( array( 'field' => 'sys_level',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_status' => array( array( 'field' => 'sys_status',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_sys_last_upd' => array( array( 'field' => 'sys_last_upd',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_groupid' => array( array( 'field' => 'groupid',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_active' => array( array( 'field' => 'active',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_dependientes' => array( array( 'field' => 'contractor_dependientes',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_medicinapre_file' => array( array( 'field' => 'contractor_medicinapre_file',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_picmonetaria_file' => array( array( 'field' => 'contractor_picmonetaria_file',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_decljur' => array( array( 'field' => 'contractor_decljur',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_eps' => array( array( 'field' => 'contractor_eps',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_fondopensiones' => array( array( 'field' => 'contractor_fondopensiones',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_cajacompensacion' => array( array( 'field' => 'contractor_cajacompensacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_contractor_arl' => array( array( 'field' => 'contractor_arl',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ubica_dep' => array( array( 'field' => 'ubica_dep',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ubica_extension' => array( array( 'field' => 'ubica_extension',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_genero' => array( array( 'field' => 'dem_genero',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_ocupacion' => array( array( 'field' => 'dem_ocupacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_profesion' => array( array( 'field' => 'dem_profesion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ct_fecha_nacimiento' => array( array( 'field' => 'ct_fecha_nacimiento',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_ct_nacionalidad' => array( array( 'field' => 'ct_nacionalidad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_edad' => array( array( 'field' => 'dem_edad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_educacion' => array( array( 'field' => 'dem_educacion',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_dem_discapacidad' => array( array( 'field' => 'dem_discapacidad',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_emergencia' => array( array( 'field' => 'emergencia',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_terms_msj' => array( array( 'field' => 'terms_msj',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_terms_acepta' => array( array( 'field' => 'terms_acepta',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_signature' => array( array( 'field' => 'signature',
'table' => 'contractor_master_view' ) ),
'contractor_master_view_pin' => array( array( 'field' => 'pin',
'table' => 'contractor_master_view' ) ) ),
'allSearchFields' => array( 'contractor_master_chart_eps_contractor_eps',
'contractor_master_chart_eps_qtygen',
'contractor_master_chart_fondopension_contractor_fondopensiones',
'contractor_master_chart_fondopension_qtygen',
'contractor_master_Chart_genero_dem_genero',
'contractor_master_Chart_genero_qtygen',
'contractor_master_view_contractor_id',
'contractor_master_view_contractor_type',
'contractor_master_view_contractor_doc_id',
'contractor_master_view_contractor_doc_dv',
'contractor_master_view_contractor_pwd',
'contractor_master_view_contractor_image',
'contractor_master_view_contractor_name',
'contractor_master_view_contractor_lname',
'contractor_master_view_contractor_nombresfull',
'contractor_master_view_enlace_sigep',
'contractor_master_view_contractor_email',
'contractor_master_view_contractor_email_mincit',
'contractor_master_view_contractor_address',
'contractor_master_view_contractor_phone',
'contractor_master_view_contractor_mobile',
'contractor_master_view_contractor_city',
'contractor_master_view_contractor_sup_jerarquico',
'contractor_master_view_contractor_dependencia',
'contractor_master_view_bank_name',
'contractor_master_view_bank_cta_type',
'contractor_master_view_bank_cta_number',
'contractor_master_view_iva_regimen',
'contractor_master_view_sys_update',
'contractor_master_view_sys_user',
'contractor_master_view_sys_date',
'contractor_master_view_sys_level',
'contractor_master_view_sys_status',
'contractor_master_view_sys_last_upd',
'contractor_master_view_groupid',
'contractor_master_view_active',
'contractor_master_view_contractor_dependientes',
'contractor_master_view_contractor_medicinapre_file',
'contractor_master_view_contractor_picmonetaria_file',
'contractor_master_view_contractor_decljur',
'contractor_master_view_contractor_eps',
'contractor_master_view_contractor_fondopensiones',
'contractor_master_view_contractor_cajacompensacion',
'contractor_master_view_contractor_arl',
'contractor_master_view_ubica_dep',
'contractor_master_view_ubica_extension',
'contractor_master_view_dem_genero',
'contractor_master_view_dem_ocupacion',
'contractor_master_view_dem_profesion',
'contractor_master_view_ct_fecha_nacimiento',
'contractor_master_view_ct_nacionalidad',
'contractor_master_view_dem_edad',
'contractor_master_view_dem_educacion',
'contractor_master_view_dem_discapacidad',
'contractor_master_view_emergencia',
'contractor_master_view_terms_msj',
'contractor_master_view_terms_acepta',
'contractor_master_view_signature',
'contractor_master_view_pin' ),
'googleLikeFields' => array( 'contractor_master_chart_eps_contractor_eps',
'contractor_master_chart_eps_qtygen',
'contractor_master_chart_fondopension_contractor_fondopensiones',
'contractor_master_chart_fondopension_qtygen',
'contractor_master_Chart_genero_dem_genero',
'contractor_master_Chart_genero_qtygen',
'contractor_master_view_contractor_id',
'contractor_master_view_contractor_type',
'contractor_master_view_contractor_doc_id',
'contractor_master_view_contractor_doc_dv',
'contractor_master_view_contractor_pwd',
'contractor_master_view_contractor_image',
'contractor_master_view_contractor_name',
'contractor_master_view_contractor_lname',
'contractor_master_view_contractor_nombresfull',
'contractor_master_view_enlace_sigep',
'contractor_master_view_contractor_email',
'contractor_master_view_contractor_email_mincit',
'contractor_master_view_contractor_address',
'contractor_master_view_contractor_phone',
'contractor_master_view_contractor_mobile',
'contractor_master_view_contractor_city',
'contractor_master_view_contractor_sup_jerarquico',
'contractor_master_view_contractor_dependencia',
'contractor_master_view_bank_name',
'contractor_master_view_bank_cta_type',
'contractor_master_view_bank_cta_number',
'contractor_master_view_iva_regimen',
'contractor_master_view_sys_update',
'contractor_master_view_sys_user',
'contractor_master_view_sys_date',
'contractor_master_view_sys_level',
'contractor_master_view_sys_status',
'contractor_master_view_sys_last_upd',
'contractor_master_view_groupid',
'contractor_master_view_active',
'contractor_master_view_contractor_dependientes',
'contractor_master_view_contractor_medicinapre_file',
'contractor_master_view_contractor_picmonetaria_file',
'contractor_master_view_contractor_decljur',
'contractor_master_view_contractor_eps',
'contractor_master_view_contractor_fondopensiones',
'contractor_master_view_contractor_cajacompensacion',
'contractor_master_view_contractor_arl',
'contractor_master_view_ubica_dep',
'contractor_master_view_ubica_extension',
'contractor_master_view_dem_genero',
'contractor_master_view_dem_ocupacion',
'contractor_master_view_dem_profesion',
'contractor_master_view_ct_fecha_nacimiento',
'contractor_master_view_ct_nacionalidad',
'contractor_master_view_dem_edad',
'contractor_master_view_dem_educacion',
'contractor_master_view_dem_discapacidad',
'contractor_master_view_emergencia',
'contractor_master_view_terms_msj',
'contractor_master_view_terms_acepta',
'contractor_master_view_signature',
'contractor_master_view_pin' ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_search_field',
'integrated_search_field1' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'contractor_master_chart_eps_contractor_eps',
'type' => 'integrated_search_field',
'orientation' => 0 ),
'integrated_search_field1' => array( 'field' => 'contractor_master_chart_eps_qtygen',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>