<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => null,
'editInPopup' => null,
'viewInPopup' => null,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'idusrglobal' => array( 'totalsType' => '' ),
'id_fk' => array( 'totalsType' => '' ),
'Username' => array( 'totalsType' => '' ),
'Password' => array( 'totalsType' => '' ),
'usr_email' => array( 'totalsType' => '' ),
'usr_name' => array( 'totalsType' => '' ),
'usr_lname' => array( 'totalsType' => '' ),
'usr_nombresfull' => array( 'totalsType' => '' ),
'usr_personalid' => array( 'totalsType' => '' ),
'usr_inicial' => array( 'totalsType' => '' ),
'usr_sessini' => array( 'totalsType' => '' ),
'usr_image' => array( 'totalsType' => '' ),
'usr_status_nomina' => array( 'totalsType' => '' ),
'usr_status' => array( 'totalsType' => '' ),
'usr_rdnkey' => array( 'totalsType' => '' ),
'usr_type_vinc' => array( 'totalsType' => '' ),
'usr_type_vinculacion' => array( 'totalsType' => '' ),
'usr_status_sol' => array( 'totalsType' => '' ),
'usr_dependencia' => array( 'totalsType' => '' ),
'user_dep' => array( 'totalsType' => '' ),
'usr_entidad' => array( 'totalsType' => '' ),
'usr_not' => array( 'totalsType' => '' ),
'usr_not_msj' => array( 'totalsType' => '' ),
'usr_jefe' => array( 'totalsType' => '' ),
'usr_minequipo_lider' => array( 'totalsType' => '' ),
'usr_minequipo_grupo' => array( 'totalsType' => '' ),
'global_rol_me' => array( 'totalsType' => '' ),
'global_rol_gh' => array( 'totalsType' => '' ),
'global_rol_almacen' => array( 'totalsType' => '' ),
'global_rol_ci' => array( 'totalsType' => '' ),
'global_rol_contratos' => array( 'totalsType' => '' ),
'global_rol_hojar' => array( 'totalsType' => '' ),
'global_rol_inmuebles' => array( 'totalsType' => '' ),
'global_rol_siis' => array( 'totalsType' => '' ),
'global_rol_cpanel' => array( 'totalsType' => '' ),
'global_rol_dashboard' => array( 'totalsType' => '' ),
'global_rol_zf' => array( 'totalsType' => '' ),
'global_rol_sipi' => array( 'totalsType' => '' ),
'global_rol_cej' => array( 'totalsType' => '' ),
'global_rol_jc3' => array( 'totalsType' => '' ),
'global_rol_th' => array( 'totalsType' => '' ),
'global_rol_sid' => array( 'totalsType' => '' ),
'global_rol' => array( 'totalsType' => '' ),
'global_rol_cont' => array( 'totalsType' => '' ),
'globla_rol_ct' => array( 'totalsType' => '' ),
'global_rol_procjur' => array( 'totalsType' => '' ),
'global_rol_comacc' => array( 'totalsType' => '' ),
'global_rol_gestion' => array( 'totalsType' => '' ),
'global_rol_ciudadano' => array( 'totalsType' => '' ),
'global_rol_ciudadano_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'sys_time' => array( 'totalsType' => '' ),
'sys_ntries_usr' => array( 'totalsType' => '' ),
'sys_registrationdate_usr' => array( 'totalsType' => '' ),
'sys_expiration_usr' => array( 'totalsType' => '' ),
'sys_disabledate_usr' => array( 'totalsType' => '' ),
'sys_upd_fecha' => array( 'totalsType' => '' ),
'sys_upd_user' => array( 'totalsType' => '' ),
'sys_upd_time' => array( 'totalsType' => '' ),
'sys_update_info' => array( 'totalsType' => '' ),
'sys_update_family_info' => array( 'totalsType' => '' ),
'usr_update_almacen' => array( 'totalsType' => '' ),
'sys_anio' => array( 'totalsType' => '' ),
'ctrl' => array( 'totalsType' => '' ),
'ext_security_id' => array( 'totalsType' => '' ),
'covid_sn' => array( 'totalsType' => '' ),
'covid_fecha' => array( 'totalsType' => '' ),
'vacuna_sn' => array( 'totalsType' => '' ),
'vacuna_nombre' => array( 'totalsType' => '' ),
'vacuna_a_fecha' => array( 'totalsType' => '' ),
'vacuna_b_fechaprog' => array( 'totalsType' => '' ),
'vacuna_b_fecha' => array( 'totalsType' => '' ),
'vacuna_c_fecha' => array( 'totalsType' => '' ),
'vacuna_consentimiento_sn' => array( 'totalsType' => '' ),
'vacuna_obs' => array( 'totalsType' => '' ),
'vacuna_dosis' => array( 'totalsType' => '' ),
'vacuna_interes' => array( 'totalsType' => '' ),
'vacuna_etapa' => array( 'totalsType' => '' ),
'usr_dep' => array( 'totalsType' => '' ),
'usr_dep_sup' => array( 'totalsType' => '' ),
'usr_cargo' => array( 'totalsType' => '' ),
'usr_regpago' => array( 'totalsType' => '' ),
'usr_extension' => array( 'totalsType' => '' ),
'usr_piso' => array( 'totalsType' => '' ),
'usr_datebirth' => array( 'totalsType' => '' ),
'ctrl_pedidoalmacen' => array( 'totalsType' => '' ),
'ctrl_contacto' => array( 'totalsType' => '' ),
'usr_emergencia' => array( 'totalsType' => '' ),
'upd_date' => array( 'totalsType' => '' ),
'active' => array( 'totalsType' => '' ),
'groupid' => array( 'totalsType' => '' ),
'habilita_almacen' => array( 'totalsType' => '' ),
'estado_vinculacion_mincit' => array( 'totalsType' => '' ),
'usr_firma' => array( 'totalsType' => '' ),
'usr_firma_b' => array( 'totalsType' => '' ),
'usr_hojaruta' => array( 'totalsType' => '' ),
'reset_token' => array( 'totalsType' => '' ),
'reset_date' => array( 'totalsType' => '' ),
'usr_edl' => array( 'totalsType' => '' ),
'userpic' => array( 'totalsType' => '' ),
'phone' => array( 'totalsType' => '' ),
'phone1' => array( 'totalsType' => '' ),
'usr_directivo' => array( 'totalsType' => '' ),
'vacuna_autoriza' => array( 'totalsType' => '' ),
'vacuna_autoriza_email' => array( 'totalsType' => '' ),
'two_factor' => array( 'totalsType' => '' ),
'totp' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'usr_nombresfull',
'Username',
'usr_email',
'idusrglobal',
'two_factor',
'totp' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'Password',
'userpic',
'totp',
'two_factor',
'vacuna_autoriza_email',
'vacuna_autoriza',
'vacuna_etapa',
'vacuna_interes',
'vacuna_dosis',
'vacuna_obs',
'vacuna_consentimiento_sn',
'vacuna_c_fecha',
'vacuna_b_fecha',
'vacuna_b_fechaprog',
'vacuna_a_fecha',
'vacuna_nombre',
'vacuna_sn',
'covid_fecha',
'covid_sn',
'ext_security_id',
'usr_update_almacen',
'usr_type_vinculacion',
'usr_type_vinc',
'usr_status_sol',
'usr_status_nomina',
'usr_status',
'usr_sessini',
'usr_regpago',
'usr_rdnkey',
'usr_piso',
'usr_personalid',
'usr_not_msj',
'usr_not',
'usr_nombresfull',
'usr_name',
'usr_minequipo_lider',
'usr_minequipo_grupo',
'usr_lname',
'usr_jefe',
'usr_inicial',
'usr_image',
'usr_hojaruta',
'usr_firma_b',
'usr_firma',
'usr_extension',
'usr_entidad',
'usr_emergencia',
'usr_email',
'usr_edl',
'usr_directivo',
'usr_dependencia',
'usr_dep_sup',
'usr_dep',
'usr_datebirth',
'usr_cargo',
'user_dep',
'upd_date',
'sys_user',
'sys_update_info',
'sys_update_family_info',
'sys_upd_user',
'sys_upd_time',
'sys_upd_fecha',
'sys_time',
'sys_registrationdate_usr',
'sys_ntries_usr',
'sys_expiration_usr',
'sys_disabledate_usr',
'sys_date',
'sys_anio',
'reset_token',
'reset_date',
'phone1',
'phone',
'idusrglobal',
'id_fk',
'habilita_almacen',
'groupid',
'globla_rol_ct',
'global_rol_zf',
'global_rol_th',
'global_rol_sipi',
'global_rol_siis',
'global_rol_sid',
'global_rol_procjur',
'global_rol_me',
'global_rol_jc3',
'global_rol_inmuebles',
'global_rol_hojar',
'global_rol_gh',
'global_rol_gestion',
'global_rol_dashboard',
'global_rol_cpanel',
'global_rol_contratos',
'global_rol_cont',
'global_rol_comacc',
'global_rol_ciudadano_dep',
'global_rol_ciudadano',
'global_rol_ci',
'global_rol_cej',
'global_rol_almacen',
'global_rol',
'estado_vinculacion_mincit',
'ctrl_pedidoalmacen',
'ctrl_contacto',
'ctrl',
'active',
'Username' ),
'filterFields' => array(  ),
'inlineAddFields' => array( 'two_factor',
'totp' ),
'inlineEditFields' => array( 'two_factor',
'totp' ),
'fieldItems' => array( 'usr_nombresfull' => array( 'simple_grid_field7',
'simple_grid_field8' ),
'Username' => array( 'simple_grid_field2',
'simple_grid_field5' ),
'usr_email' => array( 'simple_grid_field4',
'simple_grid_field6' ),
'idusrglobal' => array( 'simple_grid_field',
'simple_grid_field9' ),
'two_factor' => array( 'simple_grid_field1',
'simple_grid_field10' ),
'totp' => array( 'simple_grid_field3',
'simple_grid_field11' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'delete',
'details_found',
'page_size' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ),
'grid' => array( 'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field5',
'simple_grid_field2',
'simple_grid_field6',
'simple_grid_field4',
'simple_grid_field9',
'simple_grid_field',
'simple_grid_field10',
'simple_grid_field1',
'simple_grid_field11',
'simple_grid_field3',
'grid_checkbox_head',
'grid_checkbox' ) ),
'formXtTags' => array( 'above-grid' => array( 'deleteselected_link',
'details_found',
'recsPerPage' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field8' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field6' => 'grid',
'simple_grid_field4' => 'grid',
'simple_grid_field9' => 'grid',
'simple_grid_field' => 'grid',
'simple_grid_field10' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field3' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid' ),
'itemLocations' => array( 'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field6' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field9' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'simple_grid_field10' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'-' => array( '-3',
'-',
'-1',
'-2',
'-4' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field8',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field12',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field16',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field21',
'search_panel_field22',
'search_panel_field23',
'search_panel_field24',
'search_panel_field25',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field33',
'search_panel_field34',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field39',
'search_panel_field40',
'search_panel_field41',
'search_panel_field42',
'search_panel_field43',
'search_panel_field44',
'search_panel_field45',
'search_panel_field46',
'search_panel_field47',
'search_panel_field48',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field56',
'search_panel_field57',
'search_panel_field58',
'search_panel_field59',
'search_panel_field60',
'search_panel_field61',
'search_panel_field62',
'search_panel_field63',
'search_panel_field64',
'search_panel_field65',
'search_panel_field66',
'search_panel_field67',
'search_panel_field68',
'search_panel_field69',
'search_panel_field70',
'search_panel_field71',
'search_panel_field72',
'search_panel_field73',
'search_panel_field74',
'search_panel_field75',
'search_panel_field76',
'search_panel_field77',
'search_panel_field78',
'search_panel_field79',
'search_panel_field80',
'search_panel_field81',
'search_panel_field82',
'search_panel_field83',
'search_panel_field84',
'search_panel_field85',
'search_panel_field86',
'search_panel_field87',
'search_panel_field88',
'search_panel_field89',
'search_panel_field90',
'search_panel_field91',
'search_panel_field92',
'search_panel_field93',
'search_panel_field94',
'search_panel_field95',
'search_panel_field96',
'search_panel_field97',
'search_panel_field98',
'search_panel_field99',
'search_panel_field100',
'search_panel_field101',
'search_panel_field102',
'search_panel_field103',
'search_panel_field104',
'search_panel_field105',
'search_panel_field106',
'search_panel_field107' ),
'logo' => array( 'logo1' ),
'advsearch_link' => array( 'advsearch_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'grid_field' => array( 'simple_grid_field7',
'simple_grid_field2',
'simple_grid_field4',
'simple_grid_field',
'simple_grid_field1',
'simple_grid_field3' ),
'grid_field_label' => array( 'simple_grid_field8',
'simple_grid_field5',
'simple_grid_field6',
'simple_grid_field9',
'simple_grid_field10',
'simple_grid_field11' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'usr_nombresfull_fieldheadercolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array( 'Username_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'usr_email_fieldheadercolumn' ),
'items' => array( 'simple_grid_field6' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'idusrglobal_fieldheadercolumn' ),
'items' => array( 'simple_grid_field9' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'two_factor_fieldheadercolumn' ),
'items' => array( 'simple_grid_field10' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'totp_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'usr_nombresfull_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array( 'Username_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'usr_email_fieldcolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'idusrglobal_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'two_factor_fieldcolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'totp_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 3 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 4 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 5 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 6 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 7,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ) ) ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'usr_nombresfull',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'usr_nombresfull',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'Username',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'Username',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field6' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'usr_email',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field9' ),
'field' => 'idusrglobal',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'idusrglobal',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field10' ),
'field' => 'two_factor',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'two_factor',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'totp',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'totp',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'delete_selected',
'-4',
'advsearch_link',
'-3',
'show_search_panel',
'hide_search_panel' ) ),
'-3' => array( 'type' => '-' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'-' => array( 'type' => '-' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field',
'search_panel_field107',
'search_panel_field106',
'search_panel_field105',
'search_panel_field104',
'search_panel_field103',
'search_panel_field102',
'search_panel_field101',
'search_panel_field100',
'search_panel_field99',
'search_panel_field98',
'search_panel_field97',
'search_panel_field96',
'search_panel_field95',
'search_panel_field94',
'search_panel_field93',
'search_panel_field92',
'search_panel_field91',
'search_panel_field90',
'search_panel_field89',
'search_panel_field88',
'search_panel_field87',
'search_panel_field86',
'search_panel_field85',
'search_panel_field84',
'search_panel_field83',
'search_panel_field82',
'search_panel_field81',
'search_panel_field80',
'search_panel_field79',
'search_panel_field78',
'search_panel_field77',
'search_panel_field76',
'search_panel_field75',
'search_panel_field74',
'search_panel_field73',
'search_panel_field72',
'search_panel_field71',
'search_panel_field70',
'search_panel_field69',
'search_panel_field68',
'search_panel_field67',
'search_panel_field66',
'search_panel_field65',
'search_panel_field64',
'search_panel_field63',
'search_panel_field62',
'search_panel_field61',
'search_panel_field60',
'search_panel_field59',
'search_panel_field58',
'search_panel_field57',
'search_panel_field56',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field48',
'search_panel_field47',
'search_panel_field46',
'search_panel_field45',
'search_panel_field44',
'search_panel_field43',
'search_panel_field42',
'search_panel_field41',
'search_panel_field40',
'search_panel_field39',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field34',
'search_panel_field33',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field25',
'search_panel_field24',
'search_panel_field23',
'search_panel_field22',
'search_panel_field21',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field16',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field12',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field8',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field' => array( 'field' => 'Password',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field1' => array( 'field' => 'Username',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field2' => array( 'field' => 'active',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field3' => array( 'field' => 'ctrl',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field4' => array( 'field' => 'ctrl_contacto',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field5' => array( 'field' => 'ctrl_pedidoalmacen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field6' => array( 'field' => 'estado_vinculacion_mincit',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field7' => array( 'field' => 'global_rol',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field8' => array( 'field' => 'global_rol_almacen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field9' => array( 'field' => 'global_rol_cej',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field10' => array( 'field' => 'global_rol_ci',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field11' => array( 'field' => 'global_rol_ciudadano',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field12' => array( 'field' => 'global_rol_ciudadano_dep',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field13' => array( 'field' => 'global_rol_comacc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field14' => array( 'field' => 'global_rol_cont',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field15' => array( 'field' => 'global_rol_contratos',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field16' => array( 'field' => 'global_rol_cpanel',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field17' => array( 'field' => 'global_rol_dashboard',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field18' => array( 'field' => 'global_rol_gestion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field19' => array( 'field' => 'global_rol_gh',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field20' => array( 'field' => 'global_rol_hojar',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field21' => array( 'field' => 'global_rol_inmuebles',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field22' => array( 'field' => 'global_rol_jc3',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field23' => array( 'field' => 'global_rol_me',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field24' => array( 'field' => 'global_rol_procjur',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field25' => array( 'field' => 'global_rol_sid',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field26' => array( 'field' => 'global_rol_siis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field27' => array( 'field' => 'global_rol_sipi',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field28' => array( 'field' => 'global_rol_th',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field29' => array( 'field' => 'global_rol_zf',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field30' => array( 'field' => 'globla_rol_ct',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field31' => array( 'field' => 'groupid',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field32' => array( 'field' => 'habilita_almacen',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field33' => array( 'field' => 'id_fk',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field34' => array( 'field' => 'idusrglobal',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field35' => array( 'field' => 'phone',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field36' => array( 'field' => 'phone1',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field37' => array( 'field' => 'reset_date',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field38' => array( 'field' => 'reset_token',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field39' => array( 'field' => 'sys_anio',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field40' => array( 'field' => 'sys_date',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field41' => array( 'field' => 'sys_disabledate_usr',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field42' => array( 'field' => 'sys_expiration_usr',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field43' => array( 'field' => 'sys_ntries_usr',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field44' => array( 'field' => 'sys_registrationdate_usr',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field45' => array( 'field' => 'sys_time',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field46' => array( 'field' => 'sys_upd_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field47' => array( 'field' => 'sys_upd_time',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field48' => array( 'field' => 'sys_upd_user',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field49' => array( 'field' => 'sys_update_family_info',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field50' => array( 'field' => 'sys_update_info',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field51' => array( 'field' => 'sys_user',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field52' => array( 'field' => 'upd_date',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field53' => array( 'field' => 'user_dep',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field54' => array( 'field' => 'usr_cargo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field55' => array( 'field' => 'usr_datebirth',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field56' => array( 'field' => 'usr_dep',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'usr_dep_sup',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field58' => array( 'field' => 'usr_dependencia',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field59' => array( 'field' => 'usr_directivo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field60' => array( 'field' => 'usr_edl',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field61' => array( 'field' => 'usr_email',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field62' => array( 'field' => 'usr_emergencia',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field63' => array( 'field' => 'usr_entidad',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field64' => array( 'field' => 'usr_extension',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field65' => array( 'field' => 'usr_firma',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field66' => array( 'field' => 'usr_firma_b',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field67' => array( 'field' => 'usr_hojaruta',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field68' => array( 'field' => 'usr_image',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field69' => array( 'field' => 'usr_inicial',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field70' => array( 'field' => 'usr_jefe',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field71' => array( 'field' => 'usr_lname',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field72' => array( 'field' => 'usr_minequipo_grupo',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field73' => array( 'field' => 'usr_minequipo_lider',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field74' => array( 'field' => 'usr_name',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field75' => array( 'field' => 'usr_nombresfull',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field76' => array( 'field' => 'usr_not',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field77' => array( 'field' => 'usr_not_msj',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field78' => array( 'field' => 'usr_personalid',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field79' => array( 'field' => 'usr_piso',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field80' => array( 'field' => 'usr_rdnkey',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field81' => array( 'field' => 'usr_regpago',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field82' => array( 'field' => 'usr_sessini',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field83' => array( 'field' => 'usr_status',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field84' => array( 'field' => 'usr_status_nomina',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field85' => array( 'field' => 'usr_status_sol',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field86' => array( 'field' => 'usr_type_vinc',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field87' => array( 'field' => 'usr_type_vinculacion',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field88' => array( 'field' => 'usr_update_almacen',
'type' => 'search_panel_field',
'required' => false ),
'logo1' => array( 'type' => 'logo' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'-4' => array( 'type' => '-' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'search_panel_field89' => array( 'field' => 'ext_security_id',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field90' => array( 'field' => 'covid_sn',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field91' => array( 'field' => 'covid_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field92' => array( 'field' => 'vacuna_sn',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field93' => array( 'field' => 'vacuna_nombre',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field94' => array( 'field' => 'vacuna_a_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field95' => array( 'field' => 'vacuna_b_fechaprog',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field96' => array( 'field' => 'vacuna_b_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field97' => array( 'field' => 'vacuna_c_fecha',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field98' => array( 'field' => 'vacuna_consentimiento_sn',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field99' => array( 'field' => 'vacuna_obs',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field100' => array( 'field' => 'vacuna_dosis',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field101' => array( 'field' => 'vacuna_interes',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field102' => array( 'field' => 'vacuna_etapa',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field103' => array( 'field' => 'vacuna_autoriza',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field104' => array( 'field' => 'vacuna_autoriza_email',
'type' => 'search_panel_field',
'required' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'search_panel_field105' => array( 'field' => 'two_factor',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field106' => array( 'field' => 'totp',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field107' => array( 'field' => 'userpic',
'type' => 'search_panel_field' ),
'simple_grid_field7' => array( 'field' => 'usr_nombresfull',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field8' => array( 'type' => 'grid_field_label',
'field' => 'usr_nombresfull' ),
'simple_grid_field2' => array( 'field' => 'Username',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'Username' ),
'simple_grid_field4' => array( 'field' => 'usr_email',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field6' => array( 'type' => 'grid_field_label',
'field' => 'usr_email' ),
'simple_grid_field' => array( 'field' => 'idusrglobal',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'simple_grid_field9' => array( 'type' => 'grid_field_label',
'field' => 'idusrglobal' ),
'simple_grid_field1' => array( 'field' => 'two_factor',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field10' => array( 'type' => 'grid_field_label',
'field' => 'two_factor' ),
'simple_grid_field3' => array( 'field' => 'totp',
'type' => 'grid_field',
'inlineAdd' => true,
'inlineEdit' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'totp' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>