<?php
			$optionsArray = array( 'totals' => array( 'hr_id' => array( 'totalsType' => '' ),
'hr_nit_contra_ta' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'id_informe_fk' => array( 'totalsType' => '' ),
'hr_concepto_id' => array( 'totalsType' => '' ),
'hr_anio' => array( 'totalsType' => '' ),
'hr_asunto' => array( 'totalsType' => '' ),
'hr_valor' => array( 'totalsType' => '' ),
'hr_fechaingreso' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_fecha_reg' => array( 'totalsType' => '' ),
'not_mail' => array( 'totalsType' => '' ),
'evento_type_id_fk' => array( 'totalsType' => '' ),
'etapa' => array( 'totalsType' => '' ),
'user_from' => array( 'totalsType' => '' ),
'tercero_email' => array( 'totalsType' => '' ),
'last_act_user' => array( 'totalsType' => '' ),
'cxc_id_fk' => array( 'totalsType' => '' ),
'sysdate' => array( 'totalsType' => '' ),
'supervisor_email' => array( 'totalsType' => '' ),
'uej' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'hr_id',
'etapa',
'id_cont_fk',
'id_informe_fk',
'hr_concepto_id',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'sys_fecha_reg',
'not_mail',
'evento_type_id_fk',
'tercero_email',
'last_act_user',
'supervisor_email',
'sysdate',
'uej' ),
'exportFields' => array( 'hr_id',
'id_cont_fk',
'id_informe_fk',
'hr_concepto_id',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'sys_fecha_reg',
'not_mail',
'evento_type_id_fk',
'tercero_email',
'last_act_user',
'etapa',
'sysdate',
'supervisor_email',
'uej' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_id' => array( 'export_field' ),
'etapa' => array( 'export_field1' ),
'id_cont_fk' => array( 'export_field4' ),
'id_informe_fk' => array( 'export_field5' ),
'hr_concepto_id' => array( 'export_field6' ),
'hr_anio' => array( 'export_field7' ),
'hr_nit_contra_ta' => array( 'export_field8' ),
'hr_asunto' => array( 'export_field9' ),
'hr_valor' => array( 'export_field10' ),
'hr_fechaingreso' => array( 'export_field11' ),
'sys_user' => array( 'export_field18' ),
'sys_fecha_reg' => array( 'export_field20' ),
'not_mail' => array( 'export_field26' ),
'evento_type_id_fk' => array( 'export_field29' ),
'tercero_email' => array( 'export_field31' ),
'last_act_user' => array( 'export_field32' ),
'supervisor_email' => array( 'export_field3' ),
'sysdate' => array( 'export_field2' ),
'uej' => array( 'export_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field20',
'export_field26',
'export_field29',
'export_field31',
'export_field32',
'export_field1',
'export_field2',
'export_field3',
'export_field12' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field18' => 'grid',
'export_field20' => 'grid',
'export_field26' => 'grid',
'export_field29' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field12' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field20',
'export_field26',
'export_field29',
'export_field31',
'export_field32',
'export_field3',
'export_field2',
'export_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field18',
'export_field20',
'export_field26',
'export_field29',
'export_field31',
'export_field32',
'export_field1',
'export_field2',
'export_field3',
'export_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'hr_id',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'etapa',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'id_cont_fk',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'id_informe_fk',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'hr_concepto_id',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'hr_anio',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'hr_asunto',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'hr_valor',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'hr_fechaingreso',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'sys_fecha_reg',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'not_mail',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'evento_type_id_fk',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'tercero_email',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'last_act_user',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'supervisor_email',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'sysdate',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'uej',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>