<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'hr_id',
'id_cont_fk',
'id_informe_fk',
'hr_concepto_id',
'hr_anio',
'hr_nit_contra_ta',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'sys_fecha_reg',
'not_mail',
'evento_type_id_fk',
'tercero_email',
'last_act_user',
'etapa',
'cxc_id_fk',
'sysdate',
'supervisor_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_id' => array( 'import_field' ),
'etapa' => array( 'import_field1' ),
'id_cont_fk' => array( 'import_field4' ),
'id_informe_fk' => array( 'import_field5' ),
'hr_concepto_id' => array( 'import_field6' ),
'hr_anio' => array( 'import_field7' ),
'hr_nit_contra_ta' => array( 'import_field8' ),
'hr_asunto' => array( 'import_field9' ),
'hr_valor' => array( 'import_field10' ),
'hr_fechaingreso' => array( 'import_field11' ),
'sys_user' => array( 'import_field18' ),
'sys_fecha_reg' => array( 'import_field20' ),
'not_mail' => array( 'import_field26' ),
'evento_type_id_fk' => array( 'import_field29' ),
'tercero_email' => array( 'import_field31' ),
'last_act_user' => array( 'import_field32' ),
'cxc_id_fk' => array( 'import_field3' ),
'sysdate' => array( 'import_field2' ),
'supervisor_email' => array( 'import_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field18',
'import_field20',
'import_field26',
'import_field29',
'import_field31',
'import_field32',
'import_field1',
'import_field3',
'import_field2',
'import_field12' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field18' => 'grid',
'import_field20' => 'grid',
'import_field26' => 'grid',
'import_field29' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field1' => 'grid',
'import_field3' => 'grid',
'import_field2' => 'grid',
'import_field12' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field18',
'import_field20',
'import_field26',
'import_field29',
'import_field31',
'import_field32',
'import_field3',
'import_field2',
'import_field12' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field18',
'import_field20',
'import_field26',
'import_field29',
'import_field31',
'import_field32',
'import_field1',
'import_field3',
'import_field2',
'import_field12' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'hr_id',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'etapa',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'id_cont_fk',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'id_informe_fk',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'hr_concepto_id',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'hr_anio',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'hr_asunto',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'hr_valor',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'hr_fechaingreso',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'sys_fecha_reg',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'not_mail',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'evento_type_id_fk',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'tercero_email',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'last_act_user',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cxc_id_fk',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'sysdate',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'supervisor_email',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>