<?php
			$optionsArray = array( 'details' => array( 'informe_intersup_anexos_contratista' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'hoja_ruta_2020_tracking' => array( 'displayPreview' => 2,
'previewPageId' => '' ),
'q_consulta_op' => array( 'displayPreview' => 2,
'previewPageId' => '' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'hr_nit_contra_ta',
'id_cont_fk',
'id_informe_fk',
'hr_concepto_id',
'hr_anio',
'hr_asunto',
'hr_valor',
'hr_fechaingreso',
'sys_user',
'sys_fecha_reg',
'not_mail',
'evento_type_id_fk',
'tercero_email',
'last_act_user',
'user_from',
'cxc_id_fk',
'supervisor_email' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'hr_nit_contra_ta' => array( 'integrated_edit_field' ),
'id_cont_fk' => array( 'integrated_edit_field3' ),
'id_informe_fk' => array( 'integrated_edit_field4' ),
'hr_concepto_id' => array( 'integrated_edit_field5' ),
'hr_anio' => array( 'integrated_edit_field6' ),
'hr_asunto' => array( 'integrated_edit_field8' ),
'hr_valor' => array( 'integrated_edit_field9' ),
'hr_fechaingreso' => array( 'integrated_edit_field10' ),
'sys_user' => array( 'integrated_edit_field17' ),
'sys_fecha_reg' => array( 'integrated_edit_field19' ),
'not_mail' => array( 'integrated_edit_field25' ),
'evento_type_id_fk' => array( 'integrated_edit_field28' ),
'tercero_email' => array( 'integrated_edit_field30' ),
'last_act_user' => array( 'integrated_edit_field31' ),
'user_from' => array( 'integrated_edit_field1' ),
'cxc_id_fk' => array( 'integrated_edit_field7' ),
'supervisor_email' => array( 'integrated_edit_field2' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'add_header' ),
'above-grid' => array( 'add_message' ),
'below-grid' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field17',
'integrated_edit_field25',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field2',
'integrated_edit_field30',
'integrated_edit_field',
'text',
'integrated_edit_field7',
'integrated_edit_field28',
'integrated_edit_field5' ),
'section1' => array( 'integrated_edit_field10',
'integrated_edit_field19',
'integrated_edit_field31',
'integrated_edit_field1',
'integrated_edit_field6' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'add_header' => 'top',
'add_message' => 'above-grid',
'add_save' => 'below-grid',
'add_back_list' => 'below-grid',
'add_cancel' => 'below-grid',
'tabs' => 'grid',
'integrated_edit_field17' => 'section',
'integrated_edit_field25' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field4' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field2' => 'section',
'integrated_edit_field30' => 'section',
'integrated_edit_field' => 'section',
'text' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field28' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field10' => 'section1',
'integrated_edit_field19' => 'section1',
'integrated_edit_field31' => 'section1',
'integrated_edit_field1' => 'section1',
'integrated_edit_field6' => 'section1' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'integrated_edit_field17' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field25' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field2' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field30' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c14' ),
'text' => array( 'location' => 'section',
'cellId' => 'c15' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field28' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c16' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field19' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field31' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'add_header' => array( 'add_header' ),
'add_back_list' => array( 'add_back_list' ),
'add_cancel' => array( 'add_cancel' ),
'add_message' => array( 'add_message' ),
'add_save' => array( 'add_save' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field10',
'integrated_edit_field17',
'integrated_edit_field19',
'integrated_edit_field25',
'integrated_edit_field28',
'integrated_edit_field30',
'integrated_edit_field31',
'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field2' ),
'tabs' => array( 'tabs' ),
'text' => array( 'text' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c8' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c15' => array( 'cols' => array( 0,
1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'text' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field25' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field30' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 7 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10',
'integrated_edit_field19',
'integrated_edit_field31',
'integrated_edit_field1',
'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'add',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'add',
'type' => 'add',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'add-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'add-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'add-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add_save',
'add_back_list',
'add_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c8',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c8' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c15',
'colspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c14' ),
array( 'cell' => 'c16' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field25' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field30' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'useFullWidth' => true ),
'c15' => array( 'model' => 'c1',
'items' => array( 'text' ),
'useFullWidth' => true ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10',
'integrated_edit_field19',
'integrated_edit_field31',
'integrated_edit_field1',
'integrated_edit_field6' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'add_header' => array( 'type' => 'add_header',
'title' => array( 'page' => 'add',
'table' => 'hoja_ruta_2020_trpn',
'type' => 7 ) ),
'add_back_list' => array( 'type' => 'add_back_list' ),
'add_cancel' => array( 'type' => 'add_cancel' ),
'add_message' => array( 'type' => 'add_message' ),
'add_save' => array( 'type' => 'add_save' ),
'integrated_edit_field' => array( 'field' => 'hr_nit_contra_ta',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'hr_nit_contra_ta',
'table' => 'hoja_ruta_2020_trpn',
'type' => 3 ) ),
'integrated_edit_field3' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'id_informe_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'hr_concepto_id',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'hr_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'hr_asunto',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'hr_valor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'hr_fechaingreso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'sys_fecha_reg',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field25' => array( 'field' => 'not_mail',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'evento_type_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field30' => array( 'field' => 'tercero_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field31' => array( 'field' => 'last_act_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Gestionar pago',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section1' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'text' => array( 'type' => 'text',
'label' => array( 'text' => '<div class="alert alert-info" role="alert">
<p>Recuerde revisar los datos ingresados antes de radicar en Central de Cuentas, esto puede generar demora en el trámite de su solicitud.</p></div>',
'type' => 0 ),
'editedByRte' => false ),
'integrated_edit_field1' => array( 'field' => 'user_from',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'cxc_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cxc_id_fk',
'table' => 'hoja_ruta_2020_trpn',
'type' => 3 ) ),
'integrated_edit_field2' => array( 'field' => 'supervisor_email',
'type' => 'integrated_edit_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>