<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'inf_id',
'id_cont_fk',
'inf_consecutivo',
'inf_hash',
'inf_estado',
'inf_fechapresenta',
'inf_periodicidad',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_numerocontrato',
'inf_anio',
'inf_prenum',
'inf_doccontratista',
'inf_nombrecontratista',
'inf_valorcontrato',
'inf_adicionreduc',
'inf_cdp',
'inf_rp',
'inf_rubrocode',
'inf_rubroname',
'inf_objeto',
'inf_fechasuscripcion',
'inf_fechacont_i',
'inf_fechacont_f',
'inf_plazo',
'inf_vigencia',
'inf_modificacionesplazo',
'inf_intersup',
'inf_nombre',
'inf_cargo',
'inf_dependencia',
'inf_avgejecucion',
'inf_actividades',
'inf_declarainconf',
'inf_declarainconf_obs',
'inf_incumplimiento',
'inf_incumplimiento_obs',
'inf_otrosaspectostecnicos',
'inf_recomyobserva',
'sign_date',
'sign_hash',
'sign_file',
'sign_mailnot',
'file_verifica',
'sign_verificacert',
'cert_date',
'cert_file',
'cert_mail',
'cert_compare',
'inf_ultimopago',
'sys_date',
'inf_mail_a',
'inf_mail_b',
'url_secop',
'num_poliza',
'mun_ejec',
'cont_cesion',
'cont_modifica',
'qty_inf',
'qty_inf_compare',
'qty_inf_verifica',
'hashfirmado',
'inf_usopresupuestal',
'inf_supervisoremail',
'cert_process',
'sign_verificacert_ip',
'sign_verificacert_user',
'sign_verificacert_date',
'cert_modalidad',
'cert_mes' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_id' => array( 'integrated_search_field' ),
'id_cont_fk' => array( 'integrated_search_field1' ),
'inf_consecutivo' => array( 'integrated_search_field2' ),
'inf_hash' => array( 'integrated_search_field3' ),
'inf_estado' => array( 'integrated_search_field4' ),
'inf_fechapresenta' => array( 'integrated_search_field5' ),
'inf_periodicidad' => array( 'integrated_search_field6' ),
'inf_fecharep_i' => array( 'integrated_search_field7' ),
'inf_fecharep_f' => array( 'integrated_search_field8' ),
'inf_numerocontrato' => array( 'integrated_search_field9' ),
'inf_anio' => array( 'integrated_search_field10' ),
'inf_prenum' => array( 'integrated_search_field11' ),
'inf_doccontratista' => array( 'integrated_search_field12' ),
'inf_nombrecontratista' => array( 'integrated_search_field13' ),
'inf_valorcontrato' => array( 'integrated_search_field14' ),
'inf_adicionreduc' => array( 'integrated_search_field15' ),
'inf_cdp' => array( 'integrated_search_field16' ),
'inf_rp' => array( 'integrated_search_field17' ),
'inf_rubrocode' => array( 'integrated_search_field18' ),
'inf_rubroname' => array( 'integrated_search_field19' ),
'inf_objeto' => array( 'integrated_search_field20' ),
'inf_fechasuscripcion' => array( 'integrated_search_field21' ),
'inf_fechacont_i' => array( 'integrated_search_field22' ),
'inf_fechacont_f' => array( 'integrated_search_field23' ),
'inf_plazo' => array( 'integrated_search_field24' ),
'inf_vigencia' => array( 'integrated_search_field25' ),
'inf_modificacionesplazo' => array( 'integrated_search_field26' ),
'inf_intersup' => array( 'integrated_search_field27' ),
'inf_nombre' => array( 'integrated_search_field28' ),
'inf_cargo' => array( 'integrated_search_field29' ),
'inf_dependencia' => array( 'integrated_search_field30' ),
'inf_avgejecucion' => array( 'integrated_search_field31' ),
'inf_actividades' => array( 'integrated_search_field32' ),
'inf_declarainconf' => array( 'integrated_search_field33' ),
'inf_declarainconf_obs' => array( 'integrated_search_field34' ),
'inf_incumplimiento' => array( 'integrated_search_field35' ),
'inf_incumplimiento_obs' => array( 'integrated_search_field36' ),
'inf_otrosaspectostecnicos' => array( 'integrated_search_field37' ),
'inf_recomyobserva' => array( 'integrated_search_field38' ),
'sign_date' => array( 'integrated_search_field39' ),
'sign_hash' => array( 'integrated_search_field40' ),
'sign_file' => array( 'integrated_search_field41' ),
'sign_mailnot' => array( 'integrated_search_field42' ),
'file_verifica' => array( 'integrated_search_field43' ),
'sign_verificacert' => array( 'integrated_search_field44' ),
'cert_date' => array( 'integrated_search_field45' ),
'cert_file' => array( 'integrated_search_field46' ),
'cert_mail' => array( 'integrated_search_field47' ),
'cert_compare' => array( 'integrated_search_field48' ),
'inf_ultimopago' => array( 'integrated_search_field49' ),
'sys_date' => array( 'integrated_search_field50' ),
'inf_mail_a' => array( 'integrated_search_field51' ),
'inf_mail_b' => array( 'integrated_search_field52' ),
'url_secop' => array( 'integrated_search_field53' ),
'num_poliza' => array( 'integrated_search_field54' ),
'mun_ejec' => array( 'integrated_search_field55' ),
'cont_cesion' => array( 'integrated_search_field56' ),
'cont_modifica' => array( 'integrated_search_field57' ),
'qty_inf' => array( 'integrated_search_field58' ),
'qty_inf_compare' => array( 'integrated_search_field59' ),
'qty_inf_verifica' => array( 'integrated_search_field60' ),
'hashfirmado' => array( 'integrated_search_field61' ),
'inf_usopresupuestal' => array( 'integrated_search_field62' ),
'inf_supervisoremail' => array( 'integrated_search_field63' ),
'cert_process' => array( 'integrated_search_field64' ),
'sign_verificacert_ip' => array( 'integrated_search_field65' ),
'sign_verificacert_user' => array( 'integrated_search_field66' ),
'sign_verificacert_date' => array( 'integrated_search_field67' ),
'cert_modalidad' => array( 'integrated_search_field68' ),
'cert_mes' => array( 'integrated_search_field69' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field68',
'integrated_search_field69' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid',
'integrated_search_field54' => 'grid',
'integrated_search_field55' => 'grid',
'integrated_search_field56' => 'grid',
'integrated_search_field57' => 'grid',
'integrated_search_field58' => 'grid',
'integrated_search_field59' => 'grid',
'integrated_search_field60' => 'grid',
'integrated_search_field65' => 'grid',
'integrated_search_field66' => 'grid',
'integrated_search_field67' => 'grid',
'integrated_search_field61' => 'grid',
'integrated_search_field62' => 'grid',
'integrated_search_field63' => 'grid',
'integrated_search_field64' => 'grid',
'integrated_search_field68' => 'grid',
'integrated_search_field69' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field54' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field55' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field56' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field57' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field58' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field59' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field60' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field65' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field66' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field67' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field61' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field62' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field63' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field64' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field68' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field69' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field68',
'integrated_search_field69' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field68',
'integrated_search_field69' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53',
'integrated_search_field54',
'integrated_search_field55',
'integrated_search_field56',
'integrated_search_field57',
'integrated_search_field58',
'integrated_search_field59',
'integrated_search_field60',
'integrated_search_field65',
'integrated_search_field66',
'integrated_search_field67',
'integrated_search_field61',
'integrated_search_field62',
'integrated_search_field63',
'integrated_search_field64',
'integrated_search_field68',
'integrated_search_field69' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'inf_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'id_cont_fk',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'inf_consecutivo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'inf_hash',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'inf_estado',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'inf_fechapresenta',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'inf_periodicidad',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'inf_fecharep_i',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'inf_fecharep_f',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'inf_numerocontrato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'inf_anio',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'inf_prenum',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'inf_doccontratista',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'inf_nombrecontratista',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'inf_valorcontrato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'inf_adicionreduc',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'inf_cdp',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'inf_rp',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'inf_rubrocode',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'inf_rubroname',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'inf_objeto',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'inf_fechasuscripcion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'inf_fechacont_i',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'inf_fechacont_f',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'inf_plazo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'inf_vigencia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'inf_modificacionesplazo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'inf_intersup',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'inf_nombre',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'inf_cargo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'inf_dependencia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'inf_avgejecucion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'inf_actividades',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'inf_declarainconf',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'inf_declarainconf_obs',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'inf_incumplimiento',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'inf_incumplimiento_obs',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'inf_otrosaspectostecnicos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'inf_recomyobserva',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'sign_date',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'sign_hash',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'sign_file',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'sign_mailnot',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'file_verifica',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'sign_verificacert',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'cert_date',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'cert_file',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'cert_mail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'cert_compare',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'inf_ultimopago',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'sys_date',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'inf_mail_a',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'inf_mail_b',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'url_secop',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field54' => array( 'field' => 'num_poliza',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field55' => array( 'field' => 'mun_ejec',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field56' => array( 'field' => 'cont_cesion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field57' => array( 'field' => 'cont_modifica',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field58' => array( 'field' => 'qty_inf',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field59' => array( 'field' => 'qty_inf_compare',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field60' => array( 'field' => 'qty_inf_verifica',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field61' => array( 'field' => 'hashfirmado',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field62' => array( 'field' => 'inf_usopresupuestal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field63' => array( 'field' => 'inf_supervisoremail',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field64' => array( 'field' => 'cert_process',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field65' => array( 'field' => 'sign_verificacert_ip',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field66' => array( 'field' => 'sign_verificacert_user',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field67' => array( 'field' => 'sign_verificacert_date',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field68' => array( 'field' => 'cert_modalidad',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field69' => array( 'field' => 'cert_mes',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>