<?php
			$optionsArray = array( 'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'cxc_fondopenvol',
'inf_id_fk',
'id_cont',
'inf_hash_fk',
'cxc_numdoc',
'cxc_razonsocial',
'cxc_periodoi',
'cxc_periodof',
'cont_factura',
'cxc_valor',
'cont_banco',
'cont_cuentatipo',
'cont_cuentanumero',
'id_consecutivo',
'inf_mes',
'inf_tipopago',
'sys_user',
'cxc_cont',
'sys_fecha',
'cont_fechai',
'cont_fechaf',
'cxc_fechaelab',
'cxc_anio',
'cxc_tipocontrato',
'cont_rp',
'cont_cdp',
'cont_uej',
'cont_rubro',
'cont_uso',
'cont_valorcontrato',
'cont_pagomensual',
'sup_name',
'sup_cargo',
'sup_dep',
'sys_status',
'de_pre',
'cxc_planilla',
'cxc_planillavalor',
'cxc_planillafecha',
'cxc_pagoafc' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'cxc_fondopenvol' => array( 'integrated_edit_field21' ),
'inf_id_fk' => array( 'integrated_edit_field' ),
'id_cont' => array( 'integrated_edit_field38' ),
'inf_hash_fk' => array( 'integrated_edit_field1' ),
'cxc_numdoc' => array( 'integrated_edit_field7' ),
'cxc_razonsocial' => array( 'integrated_edit_field5' ),
'cxc_periodoi' => array( 'integrated_edit_field8' ),
'cxc_periodof' => array( 'integrated_edit_field9' ),
'cont_factura' => array( 'integrated_edit_field51' ),
'cxc_valor' => array( 'integrated_edit_field10' ),
'cont_banco' => array( 'integrated_edit_field48' ),
'cont_cuentatipo' => array( 'integrated_edit_field49' ),
'cont_cuentanumero' => array( 'integrated_edit_field50' ),
'id_consecutivo' => array( 'integrated_edit_field40' ),
'inf_mes' => array( 'integrated_edit_field23' ),
'inf_tipopago' => array( 'integrated_edit_field24' ),
'sys_user' => array( 'integrated_edit_field18' ),
'cxc_cont' => array( 'integrated_edit_field3' ),
'sys_fecha' => array( 'integrated_edit_field19' ),
'cont_fechai' => array( 'integrated_edit_field6' ),
'cont_fechaf' => array( 'integrated_edit_field29' ),
'cxc_fechaelab' => array( 'integrated_edit_field11' ),
'cxc_anio' => array( 'integrated_edit_field4' ),
'cxc_tipocontrato' => array( 'integrated_edit_field2' ),
'cont_rp' => array( 'integrated_edit_field42' ),
'cont_cdp' => array( 'integrated_edit_field41' ),
'cont_uej' => array( 'integrated_edit_field44' ),
'cont_rubro' => array( 'integrated_edit_field43' ),
'cont_uso' => array( 'integrated_edit_field45' ),
'cont_valorcontrato' => array( 'integrated_edit_field46' ),
'cont_pagomensual' => array( 'integrated_edit_field47' ),
'sup_name' => array( 'integrated_edit_field15' ),
'sup_cargo' => array( 'integrated_edit_field16' ),
'sup_dep' => array( 'integrated_edit_field17' ),
'sys_status' => array( 'integrated_edit_field20' ),
'de_pre' => array( 'integrated_edit_field28' ),
'cxc_planilla' => array( 'integrated_edit_field12' ),
'cxc_planillavalor' => array( 'integrated_edit_field14' ),
'cxc_planillafecha' => array( 'integrated_edit_field13' ),
'cxc_pagoafc' => array( 'integrated_edit_field22' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => true,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_save',
'edit_back_list',
'edit_close',
'hamburger' ),
'supertop' => array( 'expand_menu_button',
'collapse_button',
'loginform_login',
'username_button' ),
'left' => array( 'logo',
'expand_button',
'menu' ),
'top' => array( 'edit_header' ),
'grid' => array( 'tabs' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field38',
'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field51',
'integrated_edit_field10',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field40',
'integrated_edit_field23',
'integrated_edit_field24' ),
'section2' => array( 'integrated_edit_field18',
'integrated_edit_field3',
'integrated_edit_field19',
'integrated_edit_field6',
'integrated_edit_field29',
'integrated_edit_field11',
'integrated_edit_field4',
'integrated_edit_field2',
'integrated_edit_field42',
'integrated_edit_field41',
'integrated_edit_field44',
'integrated_edit_field43',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field20',
'integrated_edit_field28',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field21',
'integrated_edit_field22' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_save' => 'below-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'hamburger' => 'below-grid',
'expand_menu_button' => 'supertop',
'collapse_button' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'logo' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'edit_header' => 'top',
'tabs' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field38' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field7' => 'section',
'integrated_edit_field5' => 'section',
'integrated_edit_field8' => 'section',
'integrated_edit_field9' => 'section',
'integrated_edit_field51' => 'section',
'integrated_edit_field10' => 'section',
'integrated_edit_field48' => 'section',
'integrated_edit_field49' => 'section',
'integrated_edit_field50' => 'section',
'integrated_edit_field40' => 'section',
'integrated_edit_field23' => 'section',
'integrated_edit_field24' => 'section',
'integrated_edit_field18' => 'section2',
'integrated_edit_field3' => 'section2',
'integrated_edit_field19' => 'section2',
'integrated_edit_field6' => 'section2',
'integrated_edit_field29' => 'section2',
'integrated_edit_field11' => 'section2',
'integrated_edit_field4' => 'section2',
'integrated_edit_field2' => 'section2',
'integrated_edit_field42' => 'section2',
'integrated_edit_field41' => 'section2',
'integrated_edit_field44' => 'section2',
'integrated_edit_field43' => 'section2',
'integrated_edit_field45' => 'section2',
'integrated_edit_field46' => 'section2',
'integrated_edit_field47' => 'section2',
'integrated_edit_field15' => 'section2',
'integrated_edit_field16' => 'section2',
'integrated_edit_field17' => 'section2',
'integrated_edit_field20' => 'section2',
'integrated_edit_field28' => 'section2',
'integrated_edit_field12' => 'section2',
'integrated_edit_field14' => 'section2',
'integrated_edit_field13' => 'section2',
'integrated_edit_field21' => 'section2',
'integrated_edit_field22' => 'section2' ),
'itemLocations' => array( 'tabs' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field38' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field7' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c5' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c6' ),
'integrated_edit_field9' => array( 'location' => 'section',
'cellId' => 'c7' ),
'integrated_edit_field51' => array( 'location' => 'section',
'cellId' => 'c8' ),
'integrated_edit_field10' => array( 'location' => 'section',
'cellId' => 'c9' ),
'integrated_edit_field48' => array( 'location' => 'section',
'cellId' => 'c12' ),
'integrated_edit_field49' => array( 'location' => 'section',
'cellId' => 'c13' ),
'integrated_edit_field50' => array( 'location' => 'section',
'cellId' => 'c14' ),
'integrated_edit_field40' => array( 'location' => 'section',
'cellId' => 'c18' ),
'integrated_edit_field23' => array( 'location' => 'section',
'cellId' => 'c19' ),
'integrated_edit_field24' => array( 'location' => 'section',
'cellId' => 'c20' ),
'integrated_edit_field18' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section2',
'cellId' => 'c' ),
'integrated_edit_field19' => array( 'location' => 'section2',
'cellId' => 'c2' ),
'integrated_edit_field6' => array( 'location' => 'section2',
'cellId' => 'c3' ),
'integrated_edit_field29' => array( 'location' => 'section2',
'cellId' => 'c4' ),
'integrated_edit_field11' => array( 'location' => 'section2',
'cellId' => 'c5' ),
'integrated_edit_field4' => array( 'location' => 'section2',
'cellId' => 'c6' ),
'integrated_edit_field2' => array( 'location' => 'section2',
'cellId' => 'c7' ),
'integrated_edit_field42' => array( 'location' => 'section2',
'cellId' => 'c9' ),
'integrated_edit_field41' => array( 'location' => 'section2',
'cellId' => 'c10' ),
'integrated_edit_field44' => array( 'location' => 'section2',
'cellId' => 'c12' ),
'integrated_edit_field43' => array( 'location' => 'section2',
'cellId' => 'c13' ),
'integrated_edit_field45' => array( 'location' => 'section2',
'cellId' => 'c14' ),
'integrated_edit_field46' => array( 'location' => 'section2',
'cellId' => 'c15' ),
'integrated_edit_field47' => array( 'location' => 'section2',
'cellId' => 'c16' ),
'integrated_edit_field15' => array( 'location' => 'section2',
'cellId' => 'c18' ),
'integrated_edit_field16' => array( 'location' => 'section2',
'cellId' => 'c19' ),
'integrated_edit_field17' => array( 'location' => 'section2',
'cellId' => 'c20' ),
'integrated_edit_field20' => array( 'location' => 'section2',
'cellId' => 'c21' ),
'integrated_edit_field28' => array( 'location' => 'section2',
'cellId' => 'c22' ),
'integrated_edit_field12' => array( 'location' => 'section2',
'cellId' => 'c24' ),
'integrated_edit_field14' => array( 'location' => 'section2',
'cellId' => 'c25' ),
'integrated_edit_field13' => array( 'location' => 'section2',
'cellId' => 'c26' ),
'integrated_edit_field21' => array( 'location' => 'section2',
'cellId' => 'c27' ),
'integrated_edit_field22' => array( 'location' => 'section2',
'cellId' => 'c28' ) ),
'itemVisiblity' => array( 'expand_menu_button' => 2,
'expand_button' => 5 ) ),
'itemsByType' => array( 'edit_header' => array( 'edit_header' ),
'edit_message' => array( 'edit_message' ),
'edit_save' => array( 'edit_save' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'hamburger' => array( 'hamburger' ),
'edit_reset' => array( 'edit_reset' ),
'edit_view' => array( 'edit_view' ),
'integrated_edit_field' => array( 'integrated_edit_field21',
'integrated_edit_field',
'integrated_edit_field38',
'integrated_edit_field1',
'integrated_edit_field7',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field51',
'integrated_edit_field10',
'integrated_edit_field48',
'integrated_edit_field49',
'integrated_edit_field50',
'integrated_edit_field40',
'integrated_edit_field23',
'integrated_edit_field24',
'integrated_edit_field18',
'integrated_edit_field3',
'integrated_edit_field19',
'integrated_edit_field6',
'integrated_edit_field29',
'integrated_edit_field11',
'integrated_edit_field4',
'integrated_edit_field2',
'integrated_edit_field42',
'integrated_edit_field41',
'integrated_edit_field44',
'integrated_edit_field43',
'integrated_edit_field45',
'integrated_edit_field46',
'integrated_edit_field47',
'integrated_edit_field15',
'integrated_edit_field16',
'integrated_edit_field17',
'integrated_edit_field20',
'integrated_edit_field28',
'integrated_edit_field12',
'integrated_edit_field14',
'integrated_edit_field13',
'integrated_edit_field22' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'expand_menu_button' => array( 'expand_menu_button' ),
'collapse_button' => array( 'collapse_button' ),
'tabs' => array( 'tabs' ),
'changepassword_link' => array( 'changepassword_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'tabs' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field38' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field51' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field40' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field23' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field24' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field48' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field49' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field50' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 6 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field18' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field19' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field29' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c12' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field44' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c13' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field43' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c14' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field45' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field42' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field41' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 2 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c15' => array( 'cols' => array( 0 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field46' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c16' => array( 'cols' => array( 1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field47' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c17' => array( 'cols' => array( 2 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c18' => array( 'cols' => array( 0 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field15' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c19' => array( 'cols' => array( 1 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field16' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c20' => array( 'cols' => array( 2 ),
'rows' => array( 6 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field17' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c21' => array( 'cols' => array( 0 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field20' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c22' => array( 'cols' => array( 1 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field28' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c23' => array( 'cols' => array( 2 ),
'rows' => array( 7 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c27' => array( 'cols' => array( 0 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field21' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c28' => array( 'cols' => array( 1 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field22' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c29' => array( 'cols' => array( 2 ),
'rows' => array( 8 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c24' => array( 'cols' => array( 0 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c25' => array( 'cols' => array( 1 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field14' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c26' => array( 'cols' => array( 2 ),
'rows' => array( 9 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field13' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 10 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_save',
'edit_back_list',
'edit_close' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'expand_menu_button',
'collapse_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo',
'expand_button' ) ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3',
'colspan' => 1 ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'tabs' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field38' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c8' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field51' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c10' => array( 'model' => 'c1',
'items' => array(  ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field48' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field49' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field50' ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field40' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field23' ) ),
'c20' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field24' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c8' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c12' ),
array( 'cell' => 'c13' ),
array( 'cell' => 'c14' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c11' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c15' ),
array( 'cell' => 'c16' ),
array( 'cell' => 'c17' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c18' ),
array( 'cell' => 'c19' ),
array( 'cell' => 'c20' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c21' ),
array( 'cell' => 'c22' ),
array( 'cell' => 'c23' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c27' ),
array( 'cell' => 'c28' ),
array( 'cell' => 'c29' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c24' ),
array( 'cell' => 'c25' ),
array( 'cell' => 'c26' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field18' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field19' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field29' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field42' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field41' ) ),
'c11' => array( 'model' => 'c1',
'items' => array(  ) ),
'c12' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field44' ) ),
'c13' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field43' ) ),
'c14' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field45' ) ),
'c15' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field46' ) ),
'c16' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field47' ) ),
'c17' => array( 'model' => 'c1',
'items' => array(  ) ),
'c18' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field15' ) ),
'c19' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field16' ) ),
'c20' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field17' ) ),
'c21' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field20' ) ),
'c22' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field28' ) ),
'c23' => array( 'model' => 'c1',
'items' => array(  ) ),
'c24' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ) ),
'c25' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field14' ) ),
'c26' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field13' ) ),
'c27' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field21' ) ),
'c28' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field22' ) ),
'c29' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_header' => array( 'type' => 'edit_header' ),
'edit_message' => array( 'type' => 'edit_message' ),
'edit_save' => array( 'type' => 'edit_save' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'edit_reset',
'edit_view' ) ),
'edit_reset' => array( 'type' => 'edit_reset' ),
'edit_view' => array( 'type' => 'edit_view' ),
'integrated_edit_field21' => array( 'field' => 'cxc_fondopenvol',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field' => array( 'field' => 'inf_id_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field38' => array( 'field' => 'id_cont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field1' => array( 'field' => 'inf_hash_fk',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field7' => array( 'field' => 'cxc_numdoc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field5' => array( 'field' => 'cxc_razonsocial',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field8' => array( 'field' => 'cxc_periodoi',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field9' => array( 'field' => 'cxc_periodof',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field51' => array( 'field' => 'cont_factura',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field10' => array( 'field' => 'cxc_valor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field48' => array( 'field' => 'cont_banco',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field49' => array( 'field' => 'cont_cuentatipo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field50' => array( 'field' => 'cont_cuentanumero',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field40' => array( 'field' => 'id_consecutivo',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field23' => array( 'field' => 'inf_mes',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field24' => array( 'field' => 'inf_tipopago',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field18' => array( 'field' => 'sys_user',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field3' => array( 'field' => 'cxc_cont',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field19' => array( 'field' => 'sys_fecha',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field6' => array( 'field' => 'cont_fechai',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field29' => array( 'field' => 'cont_fechaf',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field11' => array( 'field' => 'cxc_fechaelab',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field4' => array( 'field' => 'cxc_anio',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field2' => array( 'field' => 'cxc_tipocontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field42' => array( 'field' => 'cont_rp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field41' => array( 'field' => 'cont_cdp',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field44' => array( 'field' => 'cont_uej',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field43' => array( 'field' => 'cont_rubro',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field45' => array( 'field' => 'cont_uso',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field46' => array( 'field' => 'cont_valorcontrato',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field47' => array( 'field' => 'cont_pagomensual',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field15' => array( 'field' => 'sup_name',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field16' => array( 'field' => 'sup_cargo',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field17' => array( 'field' => 'sup_dep',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field20' => array( 'field' => 'sys_status',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field28' => array( 'field' => 'de_pre',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field12' => array( 'field' => 'cxc_planilla',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field14' => array( 'field' => 'cxc_planillavalor',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'integrated_edit_field13' => array( 'field' => 'cxc_planillafecha',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'cxc_planillafecha',
'table' => 'informe_intersup_cxc',
'type' => 3 ),
'tooltip' => array( 'field' => 'cxc_planillafecha',
'table' => null,
'type' => 4 ) ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login' ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'expand_menu_button' => array( 'type' => 'expand_menu_button' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'integrated_edit_field22' => array( 'field' => 'cxc_pagoafc',
'type' => 'integrated_edit_field',
'orientation' => 0 ),
'tabs' => array( 'type' => 'tabs',
'titles' => array( array( 'text' => 'Solicitud',
'type' => 0 ),
array( 'text' => '',
'type' => 0 ) ),
'locations' => array( 'section',
'section2' ),
'bsStyle' => 'default',
'panelType' => 2 ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>