<?php
			$optionsArray = array( 'totals' => array( 'cxc_id' => array( 'totalsType' => '' ),
'de_pre' => array( 'totalsType' => '' ),
'de_num' => array( 'totalsType' => '' ),
'inf_id_fk' => array( 'totalsType' => '' ),
'inf_hash_fk' => array( 'totalsType' => '' ),
'id_cont' => array( 'totalsType' => '' ),
'id_consecutivo' => array( 'totalsType' => '' ),
'cxc_tipocontrato' => array( 'totalsType' => '' ),
'cxc_cont' => array( 'totalsType' => '' ),
'cxc_anio' => array( 'totalsType' => '' ),
'cxc_razonsocial' => array( 'totalsType' => '' ),
'cxc_tipodoc' => array( 'totalsType' => '' ),
'cxc_numdoc' => array( 'totalsType' => '' ),
'cxc_periodoi' => array( 'totalsType' => '' ),
'cxc_periodof' => array( 'totalsType' => '' ),
'cxc_valor' => array( 'totalsType' => '' ),
'cxc_fechaelab' => array( 'totalsType' => '' ),
'cxc_planilla' => array( 'totalsType' => '' ),
'cxc_planillafecha' => array( 'totalsType' => '' ),
'cxc_planillavalor' => array( 'totalsType' => '' ),
'sup_name' => array( 'totalsType' => '' ),
'sup_cargo' => array( 'totalsType' => '' ),
'sup_dep' => array( 'totalsType' => '' ),
'sys_user' => array( 'totalsType' => '' ),
'sys_fecha' => array( 'totalsType' => '' ),
'sys_status' => array( 'totalsType' => '' ),
'cxc_fondopenvol' => array( 'totalsType' => '' ),
'cxc_pagoafc' => array( 'totalsType' => '' ),
'cont_fechai' => array( 'totalsType' => '' ),
'cont_fechaf' => array( 'totalsType' => '' ),
'cont_cdp' => array( 'totalsType' => '' ),
'cont_rp' => array( 'totalsType' => '' ),
'cont_rubro' => array( 'totalsType' => '' ),
'cont_uej' => array( 'totalsType' => '' ),
'cont_uso' => array( 'totalsType' => '' ),
'cont_valorcontrato' => array( 'totalsType' => '' ),
'cont_pagomensual' => array( 'totalsType' => '' ),
'cont_banco' => array( 'totalsType' => '' ),
'cont_cuentatipo' => array( 'totalsType' => '' ),
'cont_cuentanumero' => array( 'totalsType' => '' ),
'cont_factura' => array( 'totalsType' => '' ),
'inf_mes' => array( 'totalsType' => '' ),
'inf_tipopago' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'inf_id_fk',
'inf_hash_fk',
'cxc_tipocontrato',
'cxc_cont',
'cxc_anio',
'cxc_razonsocial',
'cxc_numdoc',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_fechaelab',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'sys_user',
'sys_fecha',
'sys_status',
'cxc_fondopenvol',
'cxc_pagoafc',
'de_pre',
'id_cont',
'id_consecutivo',
'cont_fechai',
'cont_fechaf',
'cont_cdp',
'cont_rp',
'cont_rubro',
'cont_uej',
'cont_uso',
'cont_valorcontrato',
'cont_pagomensual',
'cont_banco',
'cont_cuentatipo',
'cont_cuentanumero',
'cont_factura',
'inf_mes',
'inf_tipopago' ),
'exportFields' => array( 'inf_id_fk',
'inf_hash_fk',
'cxc_tipocontrato',
'cxc_cont',
'cxc_anio',
'cxc_razonsocial',
'cxc_numdoc',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_fechaelab',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'sys_user',
'sys_fecha',
'sys_status',
'cxc_fondopenvol',
'cxc_pagoafc',
'de_pre',
'id_cont',
'id_consecutivo',
'cont_fechai',
'cont_fechaf',
'cont_cdp',
'cont_rp',
'cont_rubro',
'cont_uej',
'cont_uso',
'cont_valorcontrato',
'cont_pagomensual',
'cont_banco',
'cont_cuentatipo',
'cont_cuentanumero',
'cont_factura',
'inf_mes',
'inf_tipopago' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_id_fk' => array( 'export_field1' ),
'inf_hash_fk' => array( 'export_field2' ),
'cxc_tipocontrato' => array( 'export_field3' ),
'cxc_cont' => array( 'export_field4' ),
'cxc_anio' => array( 'export_field5' ),
'cxc_razonsocial' => array( 'export_field6' ),
'cxc_numdoc' => array( 'export_field8' ),
'cxc_periodoi' => array( 'export_field9' ),
'cxc_periodof' => array( 'export_field10' ),
'cxc_valor' => array( 'export_field11' ),
'cxc_fechaelab' => array( 'export_field12' ),
'cxc_planilla' => array( 'export_field13' ),
'cxc_planillafecha' => array( 'export_field14' ),
'cxc_planillavalor' => array( 'export_field15' ),
'sup_name' => array( 'export_field16' ),
'sup_cargo' => array( 'export_field17' ),
'sup_dep' => array( 'export_field18' ),
'sys_user' => array( 'export_field19' ),
'sys_fecha' => array( 'export_field20' ),
'sys_status' => array( 'export_field21' ),
'cxc_fondopenvol' => array( 'export_field22' ),
'cxc_pagoafc' => array( 'export_field23' ),
'de_pre' => array( 'export_field29' ),
'id_cont' => array( 'export_field39' ),
'id_consecutivo' => array( 'export_field41' ),
'cont_fechai' => array( 'export_field' ),
'cont_fechaf' => array( 'export_field7' ),
'cont_cdp' => array( 'export_field30' ),
'cont_rp' => array( 'export_field42' ),
'cont_rubro' => array( 'export_field43' ),
'cont_uej' => array( 'export_field44' ),
'cont_uso' => array( 'export_field45' ),
'cont_valorcontrato' => array( 'export_field46' ),
'cont_pagomensual' => array( 'export_field47' ),
'cont_banco' => array( 'export_field48' ),
'cont_cuentatipo' => array( 'export_field49' ),
'cont_cuentanumero' => array( 'export_field50' ),
'cont_factura' => array( 'export_field51' ),
'inf_mes' => array( 'export_field24' ),
'inf_tipopago' => array( 'export_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field29',
'export_field39',
'export_field41',
'export_field',
'export_field7',
'export_field30',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field24',
'export_field25' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field29' => 'grid',
'export_field39' => 'grid',
'export_field41' => 'grid',
'export_field' => 'grid',
'export_field7' => 'grid',
'export_field30' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field29',
'export_field39',
'export_field41',
'export_field',
'export_field7',
'export_field30',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field24',
'export_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field29',
'export_field39',
'export_field41',
'export_field',
'export_field7',
'export_field30',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field24',
'export_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'inf_id_fk',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'inf_hash_fk',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'cxc_tipocontrato',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'cxc_cont',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'cxc_anio',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cxc_razonsocial',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'cxc_numdoc',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'cxc_periodoi',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'cxc_periodof',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'cxc_valor',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'cxc_fechaelab',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'cxc_planilla',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'cxc_planillafecha',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'cxc_planillavalor',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'sup_name',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'sup_cargo',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'sup_dep',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'sys_user',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'sys_fecha',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'sys_status',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cxc_fondopenvol',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'cxc_pagoafc',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'de_pre',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'id_cont',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'id_consecutivo',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'cont_fechai',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cont_fechaf',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'cont_cdp',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'cont_rp',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'cont_rubro',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'cont_uej',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'cont_uso',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'cont_valorcontrato',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'cont_pagomensual',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'cont_banco',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'cont_cuentatipo',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'cont_cuentanumero',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'cont_factura',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'inf_mes',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'inf_tipopago',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>