<?php
			$optionsArray = array( 'list' => array( 'inlineAdd' => false,
'detailsAdd' => false,
'inlineEdit' => false,
'addToBottom' => false,
'delete' => true,
'updateSelected' => false,
'addInPopup' => false,
'editInPopup' => true,
'viewInPopup' => true,
'clickSort' => true,
'sortDropdown' => false,
'showHideFields' => false,
'reorderFields' => false,
'fieldFilter' => false,
'hideNumberOfRecords' => false ),
'allDetails' => array( 'linkType' => 0 ),
'details' => array( 'informe_intersup_oe_contratista' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'informe_intersup_anexos_contratista' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ),
'informe_intersup_anexos_contratista_o' => array( 'displayPreview' => 1,
'previewPageId' => 'list',
'showCount' => true,
'hideEmptyChild' => false,
'hideEmptyPreview' => false,
'showProceedLink' => true,
'printDetails' => true ) ),
'listSearch' => array( 'alwaysOnPanelFields' => array(  ),
'searchPanel' => true,
'fixedSearchPanel' => false,
'simpleSearchOptions' => false,
'searchSaving' => false ),
'totals' => array( 'inf_id' => array( 'totalsType' => '' ),
'id_cont_fk' => array( 'totalsType' => '' ),
'inf_consecutivo' => array( 'totalsType' => '' ),
'inf_hash' => array( 'totalsType' => '' ),
'inf_estado' => array( 'totalsType' => '' ),
'inf_fechapresenta' => array( 'totalsType' => '' ),
'inf_periodicidad' => array( 'totalsType' => '' ),
'inf_fecharep_i' => array( 'totalsType' => '' ),
'inf_fecharep_f' => array( 'totalsType' => '' ),
'inf_numerocontrato' => array( 'totalsType' => '' ),
'inf_anio' => array( 'totalsType' => '' ),
'inf_prenum' => array( 'totalsType' => '' ),
'inf_doccontratista' => array( 'totalsType' => '' ),
'inf_nombrecontratista' => array( 'totalsType' => '' ),
'inf_valorcontrato' => array( 'totalsType' => '' ),
'inf_adicionreduc' => array( 'totalsType' => '' ),
'inf_cdp' => array( 'totalsType' => '' ),
'inf_rp' => array( 'totalsType' => '' ),
'inf_rubrocode' => array( 'totalsType' => '' ),
'inf_rubroname' => array( 'totalsType' => '' ),
'inf_usopresupuestal' => array( 'totalsType' => '' ),
'inf_objeto' => array( 'totalsType' => '' ),
'inf_fechasuscripcion' => array( 'totalsType' => '' ),
'inf_fechacont_i' => array( 'totalsType' => '' ),
'inf_fechacont_f' => array( 'totalsType' => '' ),
'inf_plazo' => array( 'totalsType' => '' ),
'inf_vigencia' => array( 'totalsType' => '' ),
'inf_modificacionesplazo' => array( 'totalsType' => '' ),
'inf_intersup' => array( 'totalsType' => '' ),
'inf_nombre' => array( 'totalsType' => '' ),
'inf_cargo' => array( 'totalsType' => '' ),
'inf_dependencia' => array( 'totalsType' => '' ),
'inf_avgejecucion' => array( 'totalsType' => '' ),
'inf_actividades' => array( 'totalsType' => '' ),
'inf_declarainconf' => array( 'totalsType' => '' ),
'inf_declarainconf_obs' => array( 'totalsType' => '' ),
'inf_incumplimiento' => array( 'totalsType' => '' ),
'inf_incumplimiento_obs' => array( 'totalsType' => '' ),
'inf_otrosaspectostecnicos' => array( 'totalsType' => '' ),
'inf_recomyobserva' => array( 'totalsType' => '' ),
'file_verifica' => array( 'totalsType' => '' ),
'inf_ultimopago' => array( 'totalsType' => '' ),
'sys_date' => array( 'totalsType' => '' ),
'inf_mail_a' => array( 'totalsType' => '' ),
'inf_mail_b' => array( 'totalsType' => '' ),
'url_secop' => array( 'totalsType' => '' ),
'num_poliza' => array( 'totalsType' => '' ),
'mun_ejec' => array( 'totalsType' => '' ),
'cont_cesion' => array( 'totalsType' => '' ),
'cont_modifica' => array( 'totalsType' => '' ),
'qty_inf' => array( 'totalsType' => '' ),
'qty_inf_compare' => array( 'totalsType' => '' ),
'qty_inf_verifica' => array( 'totalsType' => '' ),
'cert_process' => array( 'totalsType' => '' ),
'cert_modalidad' => array( 'totalsType' => '' ),
'cert_mes' => array( 'totalsType' => '' ),
'cert_mail' => array( 'totalsType' => '' ),
'cert_file' => array( 'totalsType' => '' ),
'cert_date' => array( 'totalsType' => '' ),
'cert_compare' => array( 'totalsType' => '' ),
'sign_hash' => array( 'totalsType' => '' ),
'sign_date' => array( 'totalsType' => '' ),
'sign_mailnot' => array( 'totalsType' => '' ),
'sign_verificacert' => array( 'totalsType' => '' ),
'sign_file' => array( 'totalsType' => '' ),
'sign_verificacert_ip' => array( 'totalsType' => '' ),
'sign_verificacert_user' => array( 'totalsType' => '' ),
'sign_verificacert_date' => array( 'totalsType' => '' ),
'inf_supervisoremail' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'inf_consecutivo',
'inf_hash',
'inf_fecharep_i',
'inf_fecharep_f',
'qty_inf',
'qty_inf_compare',
'inf_estado' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array( 'inf_numerocontrato',
'inf_usopresupuestal',
'qty_inf_compare',
'qty_inf',
'mun_ejec',
'num_poliza',
'url_secop',
'inf_mail_b',
'inf_mail_a',
'sys_date',
'inf_ultimopago',
'file_verifica',
'inf_recomyobserva',
'inf_otrosaspectostecnicos',
'inf_incumplimiento_obs',
'inf_incumplimiento',
'inf_declarainconf_obs',
'inf_declarainconf',
'inf_actividades',
'inf_avgejecucion',
'inf_dependencia',
'inf_cargo',
'inf_nombre',
'inf_modificacionesplazo',
'inf_vigencia',
'inf_plazo',
'inf_fechacont_f',
'inf_fechacont_i',
'inf_fechasuscripcion',
'inf_objeto',
'inf_rubroname',
'inf_rubrocode',
'inf_rp',
'inf_cdp',
'inf_adicionreduc',
'inf_valorcontrato',
'inf_prenum',
'inf_periodicidad',
'inf_fechapresenta',
'id_cont_fk',
'inf_id',
'inf_estado',
'inf_nombrecontratista',
'inf_hash',
'inf_fecharep_i',
'inf_fecharep_f',
'inf_doccontratista',
'inf_consecutivo',
'inf_anio' ),
'filterFields' => array( 'inf_estado' ),
'inlineAddFields' => array(  ),
'inlineEditFields' => array(  ),
'fieldItems' => array( 'inf_estado' => array( 'simple_grid_field',
'simple_grid_field1' ),
'inf_fecharep_f' => array( 'simple_grid_field8',
'simple_grid_field12' ),
'inf_fecharep_i' => array( 'simple_grid_field7',
'simple_grid_field11' ),
'inf_hash' => array( 'simple_grid_field3',
'simple_grid_field5' ),
'inf_consecutivo' => array( 'simple_grid_field2',
'simple_grid_field4' ),
'qty_inf' => array( 'grid_field2',
'grid_field' ),
'qty_inf_compare' => array( 'grid_field3',
'grid_field4' ) ),
'hideEmptyFields' => array(  ),
'fieldFilterFields' => array(  ) ),
'pageLinks' => array( 'edit' => true,
'add' => true,
'view' => true,
'print' => true ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'left' => array( 'logo1',
'expand_button',
'menu',
'search_panel',
'filter_panel' ),
'supertop' => array( 'collapse_button',
'breadcrumb',
'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'above-grid' => array( 'add',
'delete',
'details_found',
'page_size',
'print_panel' ),
'below-grid' => array( 'pagination' ),
'grid' => array( 'simple_grid_field4',
'simple_grid_field2',
'simple_grid_field5',
'simple_grid_field3',
'simple_grid_field11',
'simple_grid_field7',
'simple_grid_field12',
'simple_grid_field8',
'grid_field',
'grid_field2',
'grid_field4',
'grid_field3',
'simple_grid_field1',
'simple_grid_field',
'details_preview2',
'details_preview1',
'details_preview',
'grid_checkbox_head',
'grid_checkbox',
'grid_edit',
'grid_view',
'grid_alldetails_link',
'grid_details_link2',
'grid_details_link1',
'grid_details_link' ),
'top' => array(  ) ),
'formXtTags' => array( 'above-grid' => array( 'add_link',
'deleteselected_link',
'details_found',
'recsPerPage',
'print_friendly' ),
'below-grid' => array( 'pagination' ),
'top' => array(  ) ),
'itemForms' => array( 'logo1' => 'left',
'expand_button' => 'left',
'menu' => 'left',
'search_panel' => 'left',
'filter_panel' => 'left',
'collapse_button' => 'supertop',
'breadcrumb' => 'supertop',
'simple_search' => 'supertop',
'list_options' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'add' => 'above-grid',
'delete' => 'above-grid',
'details_found' => 'above-grid',
'page_size' => 'above-grid',
'print_panel' => 'above-grid',
'pagination' => 'below-grid',
'simple_grid_field4' => 'grid',
'simple_grid_field2' => 'grid',
'simple_grid_field5' => 'grid',
'simple_grid_field3' => 'grid',
'simple_grid_field11' => 'grid',
'simple_grid_field7' => 'grid',
'simple_grid_field12' => 'grid',
'simple_grid_field8' => 'grid',
'grid_field' => 'grid',
'grid_field2' => 'grid',
'grid_field4' => 'grid',
'grid_field3' => 'grid',
'simple_grid_field1' => 'grid',
'simple_grid_field' => 'grid',
'details_preview2' => 'grid',
'details_preview1' => 'grid',
'details_preview' => 'grid',
'grid_checkbox_head' => 'grid',
'grid_checkbox' => 'grid',
'grid_edit' => 'grid',
'grid_view' => 'grid',
'grid_alldetails_link' => 'grid',
'grid_details_link2' => 'grid',
'grid_details_link1' => 'grid',
'grid_details_link' => 'grid' ),
'itemLocations' => array( 'simple_grid_field4' => array( 'location' => 'grid',
'cellId' => 'headcell_field' ),
'simple_grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field' ),
'simple_grid_field5' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'simple_grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'simple_grid_field11' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'simple_grid_field7' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'simple_grid_field12' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'simple_grid_field8' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ),
'grid_field' => array( 'location' => 'grid',
'cellId' => 'headcell_field4' ),
'grid_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field4' ),
'grid_field4' => array( 'location' => 'grid',
'cellId' => 'headcell_field5' ),
'grid_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field5' ),
'simple_grid_field1' => array( 'location' => 'grid',
'cellId' => 'headcell_field8' ),
'simple_grid_field' => array( 'location' => 'grid',
'cellId' => 'cell_field8' ),
'details_preview2' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview1' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'details_preview' => array( 'location' => 'grid',
'cellId' => 'cell_dpreview' ),
'grid_checkbox_head' => array( 'location' => 'grid',
'cellId' => 'headcell_checkbox' ),
'grid_checkbox' => array( 'location' => 'grid',
'cellId' => 'cell_checkbox' ),
'grid_edit' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_view' => array( 'location' => 'grid',
'cellId' => 'cell_icons' ),
'grid_alldetails_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link2' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link1' => array( 'location' => 'grid',
'cellId' => 'cell_details' ),
'grid_details_link' => array( 'location' => 'grid',
'cellId' => 'cell_details' ) ),
'itemVisiblity' => array( 'breadcrumb' => 5,
'print_panel' => 5,
'expand_button' => 5 ) ),
'itemsByType' => array( 'page_size' => array( 'page_size' ),
'details_found' => array( 'details_found' ),
'breadcrumb' => array( 'breadcrumb' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'pagination' => array( 'pagination' ),
'list_options' => array( 'list_options' ),
'search_panel_field' => array( 'search_panel_field',
'search_panel_field8',
'search_panel_field12',
'search_panel_field16',
'search_panel_field21',
'search_panel_field22',
'search_panel_field24',
'search_panel_field33',
'search_panel_field34',
'search_panel_field1',
'search_panel_field2',
'search_panel_field3',
'search_panel_field4',
'search_panel_field5',
'search_panel_field6',
'search_panel_field7',
'search_panel_field9',
'search_panel_field10',
'search_panel_field11',
'search_panel_field13',
'search_panel_field14',
'search_panel_field15',
'search_panel_field17',
'search_panel_field18',
'search_panel_field19',
'search_panel_field20',
'search_panel_field23',
'search_panel_field26',
'search_panel_field27',
'search_panel_field28',
'search_panel_field29',
'search_panel_field30',
'search_panel_field31',
'search_panel_field32',
'search_panel_field35',
'search_panel_field36',
'search_panel_field37',
'search_panel_field38',
'search_panel_field43',
'search_panel_field49',
'search_panel_field50',
'search_panel_field51',
'search_panel_field52',
'search_panel_field53',
'search_panel_field54',
'search_panel_field55',
'search_panel_field58',
'search_panel_field59',
'search_panel_field57' ),
'grid_field' => array( 'simple_grid_field',
'simple_grid_field8',
'simple_grid_field7',
'simple_grid_field3',
'simple_grid_field2',
'grid_field2',
'grid_field3' ),
'-' => array( '-3',
'-',
'-1',
'-2' ),
'advsearch_link' => array( 'advsearch_link' ),
'delete_selected' => array( 'delete_selected' ),
'delete' => array( 'delete' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'collapse_button' => array( 'collapse_button' ),
'add' => array( 'add' ),
'grid_edit' => array( 'grid_edit' ),
'grid_view' => array( 'grid_view' ),
'print_panel' => array( 'print_panel' ),
'print_scope' => array( 'print_scope' ),
'print_button' => array( 'print_button' ),
'print_records' => array( 'print_records' ),
'grid_checkbox' => array( 'grid_checkbox' ),
'grid_checkbox_head' => array( 'grid_checkbox_head' ),
'export' => array( 'export' ),
'export_selected' => array( 'export_selected' ),
'search_panel' => array( 'search_panel' ),
'show_search_panel' => array( 'show_search_panel' ),
'hide_search_panel' => array( 'hide_search_panel' ),
'logo' => array( 'logo1' ),
'print_details' => array( 'print_details' ),
'details_preview' => array( 'details_preview',
'details_preview1',
'details_preview2' ),
'grid_alldetails_link' => array( 'grid_alldetails_link' ),
'grid_details_link' => array( 'grid_details_link',
'grid_details_link1',
'grid_details_link2' ),
'filter_panel' => array( 'filter_panel' ),
'filter_panel_field' => array( 'filter_panel_field' ),
'grid_field_label' => array( 'simple_grid_field4',
'simple_grid_field5',
'simple_grid_field11',
'simple_grid_field12',
'simple_grid_field1',
'grid_field',
'grid_field4' ),
'changepassword_link' => array( 'changepassword_link' ),
'userinfo_link' => array( 'userinfo_link' ),
'expand_button' => array( 'expand_button' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox_head' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 0 ),
'tags' => array( 'inf_consecutivo_fieldheadercolumn' ),
'items' => array( 'simple_grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 0 ),
'tags' => array( 'inf_hash_fieldheadercolumn' ),
'items' => array( 'simple_grid_field5' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fecharep_i_fieldheadercolumn' ),
'items' => array( 'simple_grid_field11' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 0 ),
'tags' => array( 'inf_fecharep_f_fieldheadercolumn' ),
'items' => array( 'simple_grid_field12' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 0 ),
'tags' => array( 'qty_inf_fieldheadercolumn' ),
'items' => array( 'grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 0 ),
'tags' => array( 'qty_inf_compare_fieldheadercolumn' ),
'items' => array( 'grid_field4' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'headcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 0 ),
'tags' => array( 'inf_estado_fieldheadercolumn' ),
'items' => array( 'simple_grid_field1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'edit_column',
'view_column' ),
'items' => array( 'grid_edit',
'grid_view' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array( 'checkbox_column' ),
'items' => array( 'grid_checkbox' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_details' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'grid_alldetails_link',
'grid_details_link2',
'grid_details_link1',
'grid_details_link' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field' => array( 'cols' => array( 3 ),
'rows' => array( 1 ),
'tags' => array( 'inf_consecutivo_fieldcolumn' ),
'items' => array( 'simple_grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 1 ),
'tags' => array( 'inf_hash_fieldcolumn' ),
'items' => array( 'simple_grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fecharep_i_fieldcolumn' ),
'items' => array( 'simple_grid_field7' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 1 ),
'tags' => array( 'inf_fecharep_f_fieldcolumn' ),
'items' => array( 'simple_grid_field8' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 1 ),
'tags' => array( 'qty_inf_fieldcolumn' ),
'items' => array( 'grid_field2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 1 ),
'tags' => array( 'qty_inf_compare_fieldcolumn' ),
'items' => array( 'grid_field3' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 1 ),
'tags' => array( 'inf_estado_fieldcolumn' ),
'items' => array( 'simple_grid_field' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'cell_dpreview' => array( 'cols' => array( 0,
1,
2,
3,
4,
5,
6,
7,
8,
9 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'details_preview2',
'details_preview1',
'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'footcell_icons' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_checkbox' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_details' => array( 'cols' => array( 2 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field' => array( 'cols' => array( 3 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field1' => array( 'cols' => array( 4 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field2' => array( 'cols' => array( 5 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field3' => array( 'cols' => array( 6 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field4' => array( 'cols' => array( 7 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field5' => array( 'cols' => array( 8 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'footcell_field8' => array( 'cols' => array( 9 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 10,
'height' => 4 ) ) ),
'loginForm' => array( 'loginForm' => 1 ),
'page' => array( 'verticalBar' => true,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array( 'details_found' => array( 'tag' => 'DISPLAYING',
'type' => 2 ) ) ),
'gridType' => 0,
'recsPerRow' => 1,
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array( array( 'id' => 'main',
'horizontal' => false ) ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'list',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dataGrid' => array( 'groupFields' => array(  ) ) );
			$pageArray = array( 'id' => 'list',
'type' => 'list',
'layoutId' => 'leftbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'left' => array( 'modelId' => 'leftbar-menu',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c0' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c0' => array( 'model' => 'c0',
'items' => array( 'logo1',
'expand_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c1' => array( 'model' => 'c1',
'items' => array( 'menu',
'search_panel',
'filter_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'leftbar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'collapse_button',
'breadcrumb' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'list_options',
'loginform_login',
'username_button' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'list-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ),
array( 'cells' => array( array( 'cell' => 'c3' ),
array( 'cell' => 'c4' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'add',
'delete' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c2' => array( 'model' => 'c2',
'items' => array( 'details_found',
'page_size',
'print_panel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'c3' => array( 'model' => 'c3',
'items' => array(  ) ),
'c4' => array( 'model' => 'c4',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'list-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'pagination' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'horizontal-grid',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_icons' ),
array( 'cell' => 'headcell_checkbox' ),
array( 'cell' => 'headcell_details' ),
array( 'cell' => 'headcell_field' ),
array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ),
array( 'cell' => 'headcell_field4' ),
array( 'cell' => 'headcell_field5' ),
array( 'cell' => 'headcell_field8' ) ) ),
array( 'section' => 'body',
'cells' => array( array( 'cell' => 'cell_icons' ),
array( 'cell' => 'cell_checkbox' ),
array( 'cell' => 'cell_details' ),
array( 'cell' => 'cell_field' ),
array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ),
array( 'cell' => 'cell_field4' ),
array( 'cell' => 'cell_field5' ),
array( 'cell' => 'cell_field8' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_dpreview',
'colspan' => 10 ) ),
'section' => 'body' ),
array( 'section' => 'foot',
'cells' => array( array( 'cell' => 'footcell_icons' ),
array( 'cell' => 'footcell_checkbox' ),
array( 'cell' => 'footcell_details' ),
array( 'cell' => 'footcell_field' ),
array( 'cell' => 'footcell_field1' ),
array( 'cell' => 'footcell_field2' ),
array( 'cell' => 'footcell_field3' ),
array( 'cell' => 'footcell_field4' ),
array( 'cell' => 'footcell_field5' ),
array( 'cell' => 'footcell_field8' ) ) ) ),
'cells' => array( 'headcell_field' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field4' ),
'field' => 'inf_consecutivo',
'columnName' => 'field' ),
'cell_field' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field2' ),
'field' => 'inf_consecutivo',
'columnName' => 'field' ),
'footcell_field' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field5' ),
'field' => 'inf_hash',
'columnName' => 'field' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field3' ),
'field' => 'inf_hash',
'columnName' => 'field' ),
'footcell_field1' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field11' ),
'field' => 'inf_fecharep_i',
'columnName' => 'field' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field7' ),
'field' => 'inf_fecharep_i',
'columnName' => 'field' ),
'footcell_field2' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field12' ),
'field' => 'inf_fecharep_f',
'columnName' => 'field' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field8' ),
'field' => 'inf_fecharep_f',
'columnName' => 'field' ),
'footcell_field3' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field4' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field' ),
'field' => 'qty_inf',
'columnName' => 'field' ),
'cell_field4' => array( 'model' => 'cell_field',
'items' => array( 'grid_field2' ),
'field' => 'qty_inf',
'columnName' => 'field' ),
'footcell_field4' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field5' => array( 'model' => 'headcell_field',
'items' => array( 'grid_field4' ),
'field' => 'qty_inf_compare',
'columnName' => 'field' ),
'cell_field5' => array( 'model' => 'cell_field',
'items' => array( 'grid_field3' ),
'field' => 'qty_inf_compare',
'columnName' => 'field' ),
'footcell_field5' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'headcell_field8' => array( 'model' => 'headcell_field',
'items' => array( 'simple_grid_field1' ),
'field' => 'inf_estado',
'columnName' => 'field' ),
'cell_field8' => array( 'model' => 'cell_field',
'items' => array( 'simple_grid_field' ),
'field' => 'inf_estado',
'columnName' => 'field' ),
'footcell_field8' => array( 'model' => 'footcell_field',
'items' => array(  ) ),
'cell_dpreview' => array( 'model' => 'cell_dpreview',
'items' => array( 'details_preview2',
'details_preview1',
'details_preview' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ),
'headcell_checkbox' => array( 'model' => 'headcell_checkbox',
'items' => array( 'grid_checkbox_head' ) ),
'cell_checkbox' => array( 'model' => 'cell_checkbox',
'items' => array( 'grid_checkbox' ) ),
'footcell_checkbox' => array( 'model' => 'footcell_checkbox',
'items' => array(  ) ),
'headcell_icons' => array( 'model' => 'headcell_icons',
'items' => array(  ) ),
'cell_icons' => array( 'model' => 'cell_icons',
'items' => array( 'grid_edit',
'grid_view' ) ),
'footcell_icons' => array( 'model' => 'footcell_icons',
'items' => array(  ) ),
'headcell_details' => array( 'model' => 'headcell_details',
'items' => array(  ) ),
'cell_details' => array( 'model' => 'cell_details',
'items' => array( 'grid_alldetails_link',
'grid_details_link2',
'grid_details_link1',
'grid_details_link' ) ),
'footcell_details' => array( 'model' => 'footcell_details',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'list-sidebar-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'page_size' => array( 'type' => 'page_size' ),
'details_found' => array( 'type' => 'details_found' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'pagination' => array( 'type' => 'pagination' ),
'list_options' => array( 'type' => 'list_options',
'items' => array( 'export_selected',
'delete_selected',
'-3',
'advsearch_link',
'show_search_panel',
'hide_search_panel',
'-1',
'export' ) ),
'search_panel_field' => array( 'field' => 'inf_estado',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'simple_grid_field' => array( 'field' => 'inf_estado',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field8' => array( 'field' => 'inf_fecharep_f',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field7' => array( 'field' => 'inf_fecharep_i',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'simple_grid_field3' => array( 'field' => 'inf_hash',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true,
'bold' => true,
'font-size' => '15px' ),
'simple_grid_field2' => array( 'field' => 'inf_consecutivo',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false,
'clickSort' => true ),
'-3' => array( 'type' => '-' ),
'advsearch_link' => array( 'type' => 'advsearch_link' ),
'delete_selected' => array( 'type' => 'delete_selected' ),
'delete' => array( 'type' => 'delete' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => true ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'collapse_button' => array( 'type' => 'collapse_button' ),
'add' => array( 'type' => 'add',
'popup' => false ),
'grid_edit' => array( 'type' => 'grid_edit',
'popup' => true,
'buttonStyle' => 'warning',
'buttonSize' => 'normal',
'icon' => array( 'fa' => 'send-o' ),
'tooltip' => array( 'type' => 0,
'text' => 'Cerrar y notificar al supervisor' ),
'label' => array( 'type' => 0,
'text' => '1. Notificar al supervisor' ) ),
'grid_view' => array( 'type' => 'grid_view',
'popup' => true,
'buttonStyle' => 'default',
'buttonSize' => 'normal' ),
'print_panel' => array( 'type' => 'print_panel',
'items' => array( 'print_scope',
'print_details',
'print_records',
'print_button' ) ),
'print_scope' => array( 'type' => 'print_scope' ),
'print_button' => array( 'type' => 'print_button' ),
'print_records' => array( 'type' => 'print_records' ),
'grid_checkbox' => array( 'type' => 'grid_checkbox' ),
'grid_checkbox_head' => array( 'type' => 'grid_checkbox_head' ),
'export' => array( 'type' => 'export' ),
'-' => array( 'type' => '-' ),
'export_selected' => array( 'type' => 'export_selected' ),
'-1' => array( 'type' => '-' ),
'-2' => array( 'type' => '-' ),
'search_panel' => array( 'type' => 'search_panel',
'items' => array( 'search_panel_field34',
'search_panel_field57',
'search_panel_field59',
'search_panel_field58',
'search_panel_field55',
'search_panel_field54',
'search_panel_field53',
'search_panel_field52',
'search_panel_field51',
'search_panel_field50',
'search_panel_field49',
'search_panel_field43',
'search_panel_field38',
'search_panel_field37',
'search_panel_field36',
'search_panel_field35',
'search_panel_field32',
'search_panel_field31',
'search_panel_field30',
'search_panel_field29',
'search_panel_field28',
'search_panel_field27',
'search_panel_field26',
'search_panel_field23',
'search_panel_field20',
'search_panel_field19',
'search_panel_field18',
'search_panel_field17',
'search_panel_field15',
'search_panel_field14',
'search_panel_field13',
'search_panel_field11',
'search_panel_field10',
'search_panel_field9',
'search_panel_field7',
'search_panel_field6',
'search_panel_field5',
'search_panel_field4',
'search_panel_field3',
'search_panel_field2',
'search_panel_field1',
'search_panel_field',
'search_panel_field33',
'search_panel_field24',
'search_panel_field22',
'search_panel_field21',
'search_panel_field16',
'search_panel_field12',
'search_panel_field8' ) ),
'show_search_panel' => array( 'type' => 'show_search_panel' ),
'hide_search_panel' => array( 'type' => 'hide_search_panel' ),
'search_panel_field8' => array( 'field' => 'inf_anio',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field12' => array( 'field' => 'inf_consecutivo',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field16' => array( 'field' => 'inf_doccontratista',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field21' => array( 'field' => 'inf_fecharep_f',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field22' => array( 'field' => 'inf_fecharep_i',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field24' => array( 'field' => 'inf_hash',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field33' => array( 'field' => 'inf_nombrecontratista',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'search_panel_field34' => array( 'field' => 'inf_numerocontrato',
'type' => 'search_panel_field',
'required' => false,
'alwaysOnPanel' => false ),
'logo1' => array( 'type' => 'logo' ),
'print_details' => array( 'type' => 'print_details',
'tables' => array( 'informe_intersup_oe_contratista' => true,
'informe_intersup_anexos_contratista' => true,
'informe_intersup_anexos_contratista_o' => true ) ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'informe_intersup_oe_contratista',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_alldetails_link' => array( 'type' => 'grid_alldetails_link',
'icon' => array( 'fa' => 'angle-double-down' ),
'text' => array( 'type' => 0,
'text' => 'Gestionar informe' ),
'bold' => true,
'font-family' => 'Roboto',
'font-size' => '20px' ),
'grid_details_link' => array( 'type' => 'grid_details_link',
'table' => 'informe_intersup_oe_contratista',
'badge' => true,
'hideIfNone' => false,
'showCount' => true ),
'filter_panel' => array( 'type' => 'filter_panel',
'items' => array( 'filter_panel_field' ) ),
'filter_panel_field' => array( 'field' => 'inf_estado',
'type' => 'filter_panel_field' ),
'simple_grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'inf_consecutivo',
'clickSort' => true ),
'simple_grid_field5' => array( 'type' => 'grid_field_label',
'field' => 'inf_hash',
'clickSort' => true ),
'simple_grid_field11' => array( 'type' => 'grid_field_label',
'field' => 'inf_fecharep_i',
'clickSort' => true ),
'simple_grid_field12' => array( 'type' => 'grid_field_label',
'field' => 'inf_fecharep_f',
'clickSort' => true ),
'simple_grid_field1' => array( 'type' => 'grid_field_label',
'field' => 'inf_estado',
'clickSort' => true ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'informe_intersup_anexos_contratista',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'search_panel_field1' => array( 'field' => 'inf_id',
'type' => 'search_panel_field' ),
'search_panel_field2' => array( 'field' => 'id_cont_fk',
'type' => 'search_panel_field' ),
'search_panel_field3' => array( 'field' => 'inf_fechapresenta',
'type' => 'search_panel_field' ),
'search_panel_field4' => array( 'field' => 'inf_periodicidad',
'type' => 'search_panel_field' ),
'search_panel_field5' => array( 'field' => 'inf_prenum',
'type' => 'search_panel_field' ),
'search_panel_field6' => array( 'field' => 'inf_valorcontrato',
'type' => 'search_panel_field' ),
'search_panel_field7' => array( 'field' => 'inf_adicionreduc',
'type' => 'search_panel_field' ),
'search_panel_field9' => array( 'field' => 'inf_cdp',
'type' => 'search_panel_field' ),
'search_panel_field10' => array( 'field' => 'inf_rp',
'type' => 'search_panel_field' ),
'search_panel_field11' => array( 'field' => 'inf_rubrocode',
'type' => 'search_panel_field' ),
'search_panel_field13' => array( 'field' => 'inf_rubroname',
'type' => 'search_panel_field' ),
'search_panel_field14' => array( 'field' => 'inf_objeto',
'type' => 'search_panel_field' ),
'search_panel_field15' => array( 'field' => 'inf_fechasuscripcion',
'type' => 'search_panel_field' ),
'search_panel_field17' => array( 'field' => 'inf_fechacont_i',
'type' => 'search_panel_field' ),
'search_panel_field18' => array( 'field' => 'inf_fechacont_f',
'type' => 'search_panel_field' ),
'search_panel_field19' => array( 'field' => 'inf_plazo',
'type' => 'search_panel_field' ),
'search_panel_field20' => array( 'field' => 'inf_vigencia',
'type' => 'search_panel_field' ),
'search_panel_field23' => array( 'field' => 'inf_modificacionesplazo',
'type' => 'search_panel_field' ),
'search_panel_field26' => array( 'field' => 'inf_nombre',
'type' => 'search_panel_field',
'alwaysOnPanel' => false,
'required' => false ),
'search_panel_field27' => array( 'field' => 'inf_cargo',
'type' => 'search_panel_field' ),
'search_panel_field28' => array( 'field' => 'inf_dependencia',
'type' => 'search_panel_field' ),
'search_panel_field29' => array( 'field' => 'inf_avgejecucion',
'type' => 'search_panel_field' ),
'search_panel_field30' => array( 'field' => 'inf_actividades',
'type' => 'search_panel_field' ),
'search_panel_field31' => array( 'field' => 'inf_declarainconf',
'type' => 'search_panel_field' ),
'search_panel_field32' => array( 'field' => 'inf_declarainconf_obs',
'type' => 'search_panel_field' ),
'search_panel_field35' => array( 'field' => 'inf_incumplimiento',
'type' => 'search_panel_field' ),
'search_panel_field36' => array( 'field' => 'inf_incumplimiento_obs',
'type' => 'search_panel_field' ),
'search_panel_field37' => array( 'field' => 'inf_otrosaspectostecnicos',
'type' => 'search_panel_field' ),
'search_panel_field38' => array( 'field' => 'inf_recomyobserva',
'type' => 'search_panel_field' ),
'search_panel_field43' => array( 'field' => 'file_verifica',
'type' => 'search_panel_field' ),
'search_panel_field49' => array( 'field' => 'inf_ultimopago',
'type' => 'search_panel_field' ),
'search_panel_field50' => array( 'field' => 'sys_date',
'type' => 'search_panel_field' ),
'search_panel_field51' => array( 'field' => 'inf_mail_a',
'type' => 'search_panel_field' ),
'search_panel_field52' => array( 'field' => 'inf_mail_b',
'type' => 'search_panel_field' ),
'search_panel_field53' => array( 'field' => 'url_secop',
'type' => 'search_panel_field' ),
'search_panel_field54' => array( 'field' => 'num_poliza',
'type' => 'search_panel_field' ),
'search_panel_field55' => array( 'field' => 'mun_ejec',
'type' => 'search_panel_field' ),
'grid_field2' => array( 'field' => 'qty_inf',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'search_panel_field58' => array( 'field' => 'qty_inf',
'type' => 'search_panel_field',
'required' => false ),
'grid_field3' => array( 'field' => 'qty_inf_compare',
'type' => 'grid_field',
'inlineAdd' => false,
'inlineEdit' => false ),
'search_panel_field59' => array( 'field' => 'qty_inf_compare',
'type' => 'search_panel_field',
'required' => false ),
'search_panel_field57' => array( 'field' => 'inf_usopresupuestal',
'type' => 'search_panel_field',
'required' => false ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'grid_field' => array( 'type' => 'grid_field_label',
'field' => 'qty_inf' ),
'grid_field4' => array( 'type' => 'grid_field_label',
'field' => 'qty_inf_compare' ),
'grid_details_link1' => array( 'type' => 'grid_details_link',
'table' => 'informe_intersup_anexos_contratista',
'badge' => true,
'showCount' => true,
'hideIfNone' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'details_preview2' => array( 'type' => 'details_preview',
'table' => 'informe_intersup_anexos_contratista_o',
'items' => array(  ),
'popup' => false,
'hideEmptyPreview' => false,
'proceedLink' => true,
'pageId' => 'list' ),
'grid_details_link2' => array( 'type' => 'grid_details_link',
'table' => 'informe_intersup_anexos_contratista_o',
'badge' => true,
'showCount' => true,
'hideIfNone' => false ),
'expand_button' => array( 'type' => 'expand_button' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>