<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'inf_id_fk',
'inf_hash_fk',
'cxc_tipocontrato',
'cxc_cont',
'cxc_anio',
'cxc_razonsocial',
'cxc_numdoc',
'cxc_periodoi',
'cxc_periodof',
'cxc_valor',
'cxc_fechaelab',
'cxc_planilla',
'cxc_planillafecha',
'cxc_planillavalor',
'sup_name',
'sup_cargo',
'sup_dep',
'sys_user',
'sys_fecha',
'sys_status',
'cxc_fondopenvol',
'cxc_pagoafc',
'de_pre',
'id_cont',
'id_consecutivo',
'cont_fechai',
'cont_fechaf',
'cont_cdp',
'cont_rp',
'cont_rubro',
'cont_uej',
'cont_uso',
'cont_valorcontrato',
'cont_pagomensual',
'cont_banco',
'cont_cuentatipo',
'cont_cuentanumero',
'cont_factura',
'inf_mes',
'inf_tipopago' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'inf_id_fk' => array( 'import_field1' ),
'inf_hash_fk' => array( 'import_field2' ),
'cxc_tipocontrato' => array( 'import_field3' ),
'cxc_cont' => array( 'import_field4' ),
'cxc_anio' => array( 'import_field5' ),
'cxc_razonsocial' => array( 'import_field6' ),
'cxc_numdoc' => array( 'import_field8' ),
'cxc_periodoi' => array( 'import_field9' ),
'cxc_periodof' => array( 'import_field10' ),
'cxc_valor' => array( 'import_field11' ),
'cxc_fechaelab' => array( 'import_field12' ),
'cxc_planilla' => array( 'import_field13' ),
'cxc_planillafecha' => array( 'import_field14' ),
'cxc_planillavalor' => array( 'import_field15' ),
'sup_name' => array( 'import_field16' ),
'sup_cargo' => array( 'import_field17' ),
'sup_dep' => array( 'import_field18' ),
'sys_user' => array( 'import_field19' ),
'sys_fecha' => array( 'import_field20' ),
'sys_status' => array( 'import_field21' ),
'cxc_fondopenvol' => array( 'import_field22' ),
'cxc_pagoafc' => array( 'import_field23' ),
'de_pre' => array( 'import_field29' ),
'id_cont' => array( 'import_field39' ),
'id_consecutivo' => array( 'import_field41' ),
'cont_fechai' => array( 'import_field' ),
'cont_fechaf' => array( 'import_field7' ),
'cont_cdp' => array( 'import_field30' ),
'cont_rp' => array( 'import_field42' ),
'cont_rubro' => array( 'import_field43' ),
'cont_uej' => array( 'import_field44' ),
'cont_uso' => array( 'import_field45' ),
'cont_valorcontrato' => array( 'import_field46' ),
'cont_pagomensual' => array( 'import_field47' ),
'cont_banco' => array( 'import_field48' ),
'cont_cuentatipo' => array( 'import_field49' ),
'cont_cuentanumero' => array( 'import_field50' ),
'cont_factura' => array( 'import_field51' ),
'inf_mes' => array( 'import_field24' ),
'inf_tipopago' => array( 'import_field25' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field29',
'import_field39',
'import_field41',
'import_field',
'import_field7',
'import_field30',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field24',
'import_field25' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field29' => 'grid',
'import_field39' => 'grid',
'import_field41' => 'grid',
'import_field' => 'grid',
'import_field7' => 'grid',
'import_field30' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field29',
'import_field39',
'import_field41',
'import_field',
'import_field7',
'import_field30',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field24',
'import_field25' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field29',
'import_field39',
'import_field41',
'import_field',
'import_field7',
'import_field30',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field24',
'import_field25' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'inf_id_fk',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'inf_hash_fk',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'cxc_tipocontrato',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'cxc_cont',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'cxc_anio',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cxc_razonsocial',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'cxc_numdoc',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'cxc_periodoi',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'cxc_periodof',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'cxc_valor',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'cxc_fechaelab',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'cxc_planilla',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'cxc_planillafecha',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'cxc_planillavalor',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'sup_name',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'sup_cargo',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'sup_dep',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'sys_user',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'sys_fecha',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'sys_status',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'cxc_fondopenvol',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'cxc_pagoafc',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'de_pre',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'id_cont',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'id_consecutivo',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'cont_fechai',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cont_fechaf',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'cont_cdp',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'cont_rp',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'cont_rubro',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'cont_uej',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'cont_uso',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'cont_valorcontrato',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'cont_pagomensual',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'cont_banco',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'cont_cuentatipo',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'cont_cuentanumero',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'cont_factura',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'inf_mes',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'inf_tipopago',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>