<?php
			$optionsArray = array( 'totals' => array( 'id_cont' => array( 'totalsType' => '' ),
'CONTRATOID' => array( 'totalsType' => '' ),
'LOGINLEVEL' => array( 'totalsType' => '' ),
'VIGENCIA' => array( 'totalsType' => '' ),
'cont_hash' => array( 'totalsType' => '' ),
'cont_estado' => array( 'totalsType' => '' ),
'estado_nombre' => array( 'totalsType' => '' ),
'estado_img' => array( 'totalsType' => '' ),
'estado_lnk' => array( 'totalsType' => '' ),
'contractor_type' => array( 'totalsType' => '' ),
'DOCID' => array( 'totalsType' => '' ),
'contractor_name' => array( 'totalsType' => '' ),
'contractor_lname' => array( 'totalsType' => '' ),
'contractor_nombresfull' => array( 'totalsType' => '' ),
'contractor_email' => array( 'totalsType' => '' ),
'contractor_email_mincit' => array( 'totalsType' => '' ),
'contractor_phone' => array( 'totalsType' => '' ),
'contractor_mobile' => array( 'totalsType' => '' ),
'CODC' => array( 'totalsType' => '' ),
'NUMC' => array( 'totalsType' => '' ),
'cont_tipo' => array( 'totalsType' => '' ),
'nombre' => array( 'totalsType' => '' ),
'cont_codrubro' => array( 'totalsType' => '' ),
'cont_tipopre' => array( 'totalsType' => '' ),
'cont_catalogo_presupuestal' => array( 'totalsType' => '' ),
'cont_fase' => array( 'totalsType' => '' ),
'FECHAI' => array( 'totalsType' => '' ),
'FECHAINICIO' => array( 'totalsType' => '' ),
'FECHAF' => array( 'totalsType' => '' ),
'FECHAFINAL' => array( 'totalsType' => '' ),
'QTYDIAS' => array( 'totalsType' => '' ),
'QTYMESES' => array( 'totalsType' => '' ),
'VALORI' => array( 'totalsType' => '' ),
'cont_fechaapertura' => array( 'totalsType' => '' ),
'CDP' => array( 'totalsType' => '' ),
'RP' => array( 'totalsType' => '' ),
'cont_tipoproceso' => array( 'totalsType' => '' ),
'cont_periodicidad' => array( 'totalsType' => '' ),
'periodo_name' => array( 'totalsType' => '' ),
'periodo_value' => array( 'totalsType' => '' ),
'periodo_dias' => array( 'totalsType' => '' ),
'cont_informessug' => array( 'totalsType' => '' ),
'periodo_meses' => array( 'totalsType' => '' ),
'cont_objeto' => array( 'totalsType' => '' ),
'cont_fechavigencia' => array( 'totalsType' => '' ),
'VALORINICIAL' => array( 'totalsType' => '' ),
'cont_valormensual' => array( 'totalsType' => '' ),
'iva_regimen' => array( 'totalsType' => '' ),
'cont_iva' => array( 'totalsType' => '' ),
'cont_valormensual_base' => array( 'totalsType' => '' ),
'cont_valormensual_iva' => array( 'totalsType' => '' ),
'CONTVINCULADO' => array( 'totalsType' => '' ),
'cont_paa_id' => array( 'totalsType' => '' ),
'cont_tipoc' => array( 'totalsType' => '' ),
'ct_tipo_nombre' => array( 'totalsType' => '' ),
'cont_modalidad' => array( 'totalsType' => '' ),
'des_mod_proceso' => array( 'totalsType' => '' ),
'cont_causalc' => array( 'totalsType' => '' ),
'ctb_tipo_nombre' => array( 'totalsType' => '' ),
'cont_secop_enlace' => array( 'totalsType' => '' ),
'cont_dep' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'id_cont',
'CONTRATOID',
'LOGINLEVEL',
'VIGENCIA',
'cont_hash',
'cont_estado',
'estado_nombre',
'estado_img',
'estado_lnk',
'contractor_type',
'DOCID',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_phone',
'contractor_mobile',
'CODC',
'NUMC',
'cont_tipo',
'nombre',
'cont_codrubro',
'cont_tipopre',
'cont_catalogo_presupuestal',
'cont_fase',
'FECHAI',
'FECHAINICIO',
'FECHAF',
'FECHAFINAL',
'QTYDIAS',
'QTYMESES',
'VALORI',
'cont_fechaapertura',
'CDP',
'RP',
'cont_tipoproceso',
'cont_periodicidad',
'periodo_name',
'periodo_value',
'periodo_dias',
'cont_informessug',
'periodo_meses',
'cont_objeto',
'cont_fechavigencia',
'VALORINICIAL',
'cont_valormensual',
'iva_regimen',
'cont_iva',
'cont_valormensual_base',
'cont_valormensual_iva',
'CONTVINCULADO',
'cont_paa_id',
'cont_tipoc',
'ct_tipo_nombre',
'cont_modalidad',
'des_mod_proceso',
'cont_causalc',
'ctb_tipo_nombre',
'cont_secop_enlace',
'cont_dep' ),
'exportFields' => array( 'id_cont',
'CONTRATOID',
'LOGINLEVEL',
'VIGENCIA',
'cont_hash',
'cont_estado',
'estado_nombre',
'estado_img',
'estado_lnk',
'contractor_type',
'DOCID',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_phone',
'contractor_mobile',
'CODC',
'NUMC',
'cont_tipo',
'nombre',
'cont_codrubro',
'cont_tipopre',
'cont_catalogo_presupuestal',
'cont_fase',
'FECHAI',
'FECHAINICIO',
'FECHAF',
'FECHAFINAL',
'QTYDIAS',
'QTYMESES',
'VALORI',
'cont_fechaapertura',
'CDP',
'RP',
'cont_tipoproceso',
'cont_periodicidad',
'periodo_name',
'periodo_value',
'periodo_dias',
'cont_informessug',
'periodo_meses',
'cont_objeto',
'cont_fechavigencia',
'VALORINICIAL',
'cont_valormensual',
'iva_regimen',
'cont_iva',
'cont_valormensual_base',
'cont_valormensual_iva',
'CONTVINCULADO',
'cont_paa_id',
'cont_tipoc',
'ct_tipo_nombre',
'cont_modalidad',
'des_mod_proceso',
'cont_causalc',
'ctb_tipo_nombre',
'cont_secop_enlace',
'cont_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'export_field' ),
'CONTRATOID' => array( 'export_field1' ),
'LOGINLEVEL' => array( 'export_field2' ),
'VIGENCIA' => array( 'export_field3' ),
'cont_hash' => array( 'export_field6' ),
'cont_estado' => array( 'export_field7' ),
'estado_nombre' => array( 'export_field8' ),
'estado_img' => array( 'export_field9' ),
'estado_lnk' => array( 'export_field10' ),
'contractor_type' => array( 'export_field11' ),
'DOCID' => array( 'export_field12' ),
'contractor_name' => array( 'export_field13' ),
'contractor_lname' => array( 'export_field14' ),
'contractor_nombresfull' => array( 'export_field15' ),
'contractor_email' => array( 'export_field16' ),
'contractor_email_mincit' => array( 'export_field17' ),
'contractor_phone' => array( 'export_field18' ),
'contractor_mobile' => array( 'export_field19' ),
'CODC' => array( 'export_field20' ),
'NUMC' => array( 'export_field21' ),
'cont_tipo' => array( 'export_field22' ),
'nombre' => array( 'export_field23' ),
'cont_codrubro' => array( 'export_field24' ),
'cont_tipopre' => array( 'export_field25' ),
'cont_catalogo_presupuestal' => array( 'export_field26' ),
'cont_fase' => array( 'export_field27' ),
'FECHAI' => array( 'export_field28' ),
'FECHAINICIO' => array( 'export_field29' ),
'FECHAF' => array( 'export_field30' ),
'FECHAFINAL' => array( 'export_field31' ),
'QTYDIAS' => array( 'export_field32' ),
'QTYMESES' => array( 'export_field33' ),
'VALORI' => array( 'export_field34' ),
'cont_fechaapertura' => array( 'export_field35' ),
'CDP' => array( 'export_field36' ),
'RP' => array( 'export_field37' ),
'cont_tipoproceso' => array( 'export_field38' ),
'cont_periodicidad' => array( 'export_field39' ),
'periodo_name' => array( 'export_field40' ),
'periodo_value' => array( 'export_field41' ),
'periodo_dias' => array( 'export_field42' ),
'cont_informessug' => array( 'export_field43' ),
'periodo_meses' => array( 'export_field44' ),
'cont_objeto' => array( 'export_field45' ),
'cont_fechavigencia' => array( 'export_field46' ),
'VALORINICIAL' => array( 'export_field47' ),
'cont_valormensual' => array( 'export_field48' ),
'iva_regimen' => array( 'export_field49' ),
'cont_iva' => array( 'export_field50' ),
'cont_valormensual_base' => array( 'export_field51' ),
'cont_valormensual_iva' => array( 'export_field52' ),
'CONTVINCULADO' => array( 'export_field53' ),
'cont_paa_id' => array( 'export_field54' ),
'cont_tipoc' => array( 'export_field55' ),
'ct_tipo_nombre' => array( 'export_field56' ),
'cont_modalidad' => array( 'export_field57' ),
'des_mod_proceso' => array( 'export_field58' ),
'cont_causalc' => array( 'export_field59' ),
'ctb_tipo_nombre' => array( 'export_field60' ),
'cont_secop_enlace' => array( 'export_field61' ),
'cont_dep' => array( 'export_field62' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_field20' => 'grid',
'export_field21' => 'grid',
'export_field22' => 'grid',
'export_field23' => 'grid',
'export_field24' => 'grid',
'export_field25' => 'grid',
'export_field26' => 'grid',
'export_field27' => 'grid',
'export_field28' => 'grid',
'export_field29' => 'grid',
'export_field30' => 'grid',
'export_field31' => 'grid',
'export_field32' => 'grid',
'export_field33' => 'grid',
'export_field34' => 'grid',
'export_field35' => 'grid',
'export_field36' => 'grid',
'export_field37' => 'grid',
'export_field38' => 'grid',
'export_field39' => 'grid',
'export_field40' => 'grid',
'export_field41' => 'grid',
'export_field42' => 'grid',
'export_field43' => 'grid',
'export_field44' => 'grid',
'export_field45' => 'grid',
'export_field46' => 'grid',
'export_field47' => 'grid',
'export_field48' => 'grid',
'export_field49' => 'grid',
'export_field50' => 'grid',
'export_field51' => 'grid',
'export_field52' => 'grid',
'export_field53' => 'grid',
'export_field54' => 'grid',
'export_field55' => 'grid',
'export_field56' => 'grid',
'export_field57' => 'grid',
'export_field58' => 'grid',
'export_field59' => 'grid',
'export_field60' => 'grid',
'export_field61' => 'grid',
'export_field62' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19',
'export_field20',
'export_field21',
'export_field22',
'export_field23',
'export_field24',
'export_field25',
'export_field26',
'export_field27',
'export_field28',
'export_field29',
'export_field30',
'export_field31',
'export_field32',
'export_field33',
'export_field34',
'export_field35',
'export_field36',
'export_field37',
'export_field38',
'export_field39',
'export_field40',
'export_field41',
'export_field42',
'export_field43',
'export_field44',
'export_field45',
'export_field46',
'export_field47',
'export_field48',
'export_field49',
'export_field50',
'export_field51',
'export_field52',
'export_field53',
'export_field54',
'export_field55',
'export_field56',
'export_field57',
'export_field58',
'export_field59',
'export_field60',
'export_field61',
'export_field62' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'id_cont',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CONTRATOID',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'LOGINLEVEL',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'VIGENCIA',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'cont_hash',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'cont_estado',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'estado_nombre',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'estado_img',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'estado_lnk',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'contractor_type',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'DOCID',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'contractor_name',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'contractor_lname',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'contractor_nombresfull',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'contractor_email',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'contractor_email_mincit',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'contractor_phone',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'contractor_mobile',
'type' => 'export_field' ),
'export_field20' => array( 'field' => 'CODC',
'type' => 'export_field' ),
'export_field21' => array( 'field' => 'NUMC',
'type' => 'export_field' ),
'export_field22' => array( 'field' => 'cont_tipo',
'type' => 'export_field' ),
'export_field23' => array( 'field' => 'nombre',
'type' => 'export_field' ),
'export_field24' => array( 'field' => 'cont_codrubro',
'type' => 'export_field' ),
'export_field25' => array( 'field' => 'cont_tipopre',
'type' => 'export_field' ),
'export_field26' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'export_field' ),
'export_field27' => array( 'field' => 'cont_fase',
'type' => 'export_field' ),
'export_field28' => array( 'field' => 'FECHAI',
'type' => 'export_field' ),
'export_field29' => array( 'field' => 'FECHAINICIO',
'type' => 'export_field' ),
'export_field30' => array( 'field' => 'FECHAF',
'type' => 'export_field' ),
'export_field31' => array( 'field' => 'FECHAFINAL',
'type' => 'export_field' ),
'export_field32' => array( 'field' => 'QTYDIAS',
'type' => 'export_field' ),
'export_field33' => array( 'field' => 'QTYMESES',
'type' => 'export_field' ),
'export_field34' => array( 'field' => 'VALORI',
'type' => 'export_field' ),
'export_field35' => array( 'field' => 'cont_fechaapertura',
'type' => 'export_field' ),
'export_field36' => array( 'field' => 'CDP',
'type' => 'export_field' ),
'export_field37' => array( 'field' => 'RP',
'type' => 'export_field' ),
'export_field38' => array( 'field' => 'cont_tipoproceso',
'type' => 'export_field' ),
'export_field39' => array( 'field' => 'cont_periodicidad',
'type' => 'export_field' ),
'export_field40' => array( 'field' => 'periodo_name',
'type' => 'export_field' ),
'export_field41' => array( 'field' => 'periodo_value',
'type' => 'export_field' ),
'export_field42' => array( 'field' => 'periodo_dias',
'type' => 'export_field' ),
'export_field43' => array( 'field' => 'cont_informessug',
'type' => 'export_field' ),
'export_field44' => array( 'field' => 'periodo_meses',
'type' => 'export_field' ),
'export_field45' => array( 'field' => 'cont_objeto',
'type' => 'export_field' ),
'export_field46' => array( 'field' => 'cont_fechavigencia',
'type' => 'export_field' ),
'export_field47' => array( 'field' => 'VALORINICIAL',
'type' => 'export_field' ),
'export_field48' => array( 'field' => 'cont_valormensual',
'type' => 'export_field' ),
'export_field49' => array( 'field' => 'iva_regimen',
'type' => 'export_field' ),
'export_field50' => array( 'field' => 'cont_iva',
'type' => 'export_field' ),
'export_field51' => array( 'field' => 'cont_valormensual_base',
'type' => 'export_field' ),
'export_field52' => array( 'field' => 'cont_valormensual_iva',
'type' => 'export_field' ),
'export_field53' => array( 'field' => 'CONTVINCULADO',
'type' => 'export_field' ),
'export_field54' => array( 'field' => 'cont_paa_id',
'type' => 'export_field' ),
'export_field55' => array( 'field' => 'cont_tipoc',
'type' => 'export_field' ),
'export_field56' => array( 'field' => 'ct_tipo_nombre',
'type' => 'export_field' ),
'export_field57' => array( 'field' => 'cont_modalidad',
'type' => 'export_field' ),
'export_field58' => array( 'field' => 'des_mod_proceso',
'type' => 'export_field' ),
'export_field59' => array( 'field' => 'cont_causalc',
'type' => 'export_field' ),
'export_field60' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'export_field' ),
'export_field61' => array( 'field' => 'cont_secop_enlace',
'type' => 'export_field' ),
'export_field62' => array( 'field' => 'cont_dep',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1,
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>