<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_cont',
'CONTRATOID',
'LOGINLEVEL',
'VIGENCIA',
'cont_hash',
'cont_estado',
'estado_nombre',
'estado_img',
'estado_lnk',
'contractor_type',
'DOCID',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'contractor_phone',
'contractor_mobile',
'CODC',
'NUMC',
'cont_tipo',
'nombre',
'cont_codrubro',
'cont_tipopre',
'cont_catalogo_presupuestal',
'cont_fase',
'FECHAI',
'FECHAINICIO',
'FECHAF',
'FECHAFINAL',
'QTYDIAS',
'QTYMESES',
'VALORI',
'cont_fechaapertura',
'CDP',
'RP',
'cont_tipoproceso',
'cont_periodicidad',
'periodo_name',
'periodo_value',
'periodo_dias',
'cont_informessug',
'periodo_meses',
'cont_objeto',
'cont_fechavigencia',
'VALORINICIAL',
'cont_valormensual',
'iva_regimen',
'cont_iva',
'cont_valormensual_base',
'cont_valormensual_iva',
'CONTVINCULADO',
'cont_paa_id',
'cont_tipoc',
'ct_tipo_nombre',
'cont_modalidad',
'des_mod_proceso',
'cont_causalc',
'ctb_tipo_nombre',
'cont_secop_enlace',
'cont_dep' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'import_field' ),
'CONTRATOID' => array( 'import_field1' ),
'LOGINLEVEL' => array( 'import_field2' ),
'VIGENCIA' => array( 'import_field3' ),
'cont_hash' => array( 'import_field6' ),
'cont_estado' => array( 'import_field7' ),
'estado_nombre' => array( 'import_field8' ),
'estado_img' => array( 'import_field9' ),
'estado_lnk' => array( 'import_field10' ),
'contractor_type' => array( 'import_field11' ),
'DOCID' => array( 'import_field12' ),
'contractor_name' => array( 'import_field13' ),
'contractor_lname' => array( 'import_field14' ),
'contractor_nombresfull' => array( 'import_field15' ),
'contractor_email' => array( 'import_field16' ),
'contractor_email_mincit' => array( 'import_field17' ),
'contractor_phone' => array( 'import_field18' ),
'contractor_mobile' => array( 'import_field19' ),
'CODC' => array( 'import_field20' ),
'NUMC' => array( 'import_field21' ),
'cont_tipo' => array( 'import_field22' ),
'nombre' => array( 'import_field23' ),
'cont_codrubro' => array( 'import_field24' ),
'cont_tipopre' => array( 'import_field25' ),
'cont_catalogo_presupuestal' => array( 'import_field26' ),
'cont_fase' => array( 'import_field27' ),
'FECHAI' => array( 'import_field28' ),
'FECHAINICIO' => array( 'import_field29' ),
'FECHAF' => array( 'import_field30' ),
'FECHAFINAL' => array( 'import_field31' ),
'QTYDIAS' => array( 'import_field32' ),
'QTYMESES' => array( 'import_field33' ),
'VALORI' => array( 'import_field34' ),
'cont_fechaapertura' => array( 'import_field35' ),
'CDP' => array( 'import_field36' ),
'RP' => array( 'import_field37' ),
'cont_tipoproceso' => array( 'import_field38' ),
'cont_periodicidad' => array( 'import_field39' ),
'periodo_name' => array( 'import_field40' ),
'periodo_value' => array( 'import_field41' ),
'periodo_dias' => array( 'import_field42' ),
'cont_informessug' => array( 'import_field43' ),
'periodo_meses' => array( 'import_field44' ),
'cont_objeto' => array( 'import_field45' ),
'cont_fechavigencia' => array( 'import_field46' ),
'VALORINICIAL' => array( 'import_field47' ),
'cont_valormensual' => array( 'import_field48' ),
'iva_regimen' => array( 'import_field49' ),
'cont_iva' => array( 'import_field50' ),
'cont_valormensual_base' => array( 'import_field51' ),
'cont_valormensual_iva' => array( 'import_field52' ),
'CONTVINCULADO' => array( 'import_field53' ),
'cont_paa_id' => array( 'import_field54' ),
'cont_tipoc' => array( 'import_field55' ),
'ct_tipo_nombre' => array( 'import_field56' ),
'cont_modalidad' => array( 'import_field57' ),
'des_mod_proceso' => array( 'import_field58' ),
'cont_causalc' => array( 'import_field59' ),
'ctb_tipo_nombre' => array( 'import_field60' ),
'cont_secop_enlace' => array( 'import_field61' ),
'cont_dep' => array( 'import_field62' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid',
'import_field33' => 'grid',
'import_field34' => 'grid',
'import_field35' => 'grid',
'import_field36' => 'grid',
'import_field37' => 'grid',
'import_field38' => 'grid',
'import_field39' => 'grid',
'import_field40' => 'grid',
'import_field41' => 'grid',
'import_field42' => 'grid',
'import_field43' => 'grid',
'import_field44' => 'grid',
'import_field45' => 'grid',
'import_field46' => 'grid',
'import_field47' => 'grid',
'import_field48' => 'grid',
'import_field49' => 'grid',
'import_field50' => 'grid',
'import_field51' => 'grid',
'import_field52' => 'grid',
'import_field53' => 'grid',
'import_field54' => 'grid',
'import_field55' => 'grid',
'import_field56' => 'grid',
'import_field57' => 'grid',
'import_field58' => 'grid',
'import_field59' => 'grid',
'import_field60' => 'grid',
'import_field61' => 'grid',
'import_field62' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32',
'import_field33',
'import_field34',
'import_field35',
'import_field36',
'import_field37',
'import_field38',
'import_field39',
'import_field40',
'import_field41',
'import_field42',
'import_field43',
'import_field44',
'import_field45',
'import_field46',
'import_field47',
'import_field48',
'import_field49',
'import_field50',
'import_field51',
'import_field52',
'import_field53',
'import_field54',
'import_field55',
'import_field56',
'import_field57',
'import_field58',
'import_field59',
'import_field60',
'import_field61',
'import_field62' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'id_cont',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CONTRATOID',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'LOGINLEVEL',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'VIGENCIA',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'cont_hash',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'cont_estado',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'estado_nombre',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'estado_img',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'estado_lnk',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'contractor_type',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'DOCID',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'contractor_name',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'contractor_lname',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'contractor_nombresfull',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'contractor_email',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'contractor_email_mincit',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'contractor_phone',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'contractor_mobile',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'CODC',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'NUMC',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'cont_tipo',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'nombre',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'cont_codrubro',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'cont_tipopre',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'cont_fase',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'FECHAI',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'FECHAINICIO',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'FECHAF',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'FECHAFINAL',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'QTYDIAS',
'type' => 'import_field' ),
'import_field33' => array( 'field' => 'QTYMESES',
'type' => 'import_field' ),
'import_field34' => array( 'field' => 'VALORI',
'type' => 'import_field' ),
'import_field35' => array( 'field' => 'cont_fechaapertura',
'type' => 'import_field' ),
'import_field36' => array( 'field' => 'CDP',
'type' => 'import_field' ),
'import_field37' => array( 'field' => 'RP',
'type' => 'import_field' ),
'import_field38' => array( 'field' => 'cont_tipoproceso',
'type' => 'import_field' ),
'import_field39' => array( 'field' => 'cont_periodicidad',
'type' => 'import_field' ),
'import_field40' => array( 'field' => 'periodo_name',
'type' => 'import_field' ),
'import_field41' => array( 'field' => 'periodo_value',
'type' => 'import_field' ),
'import_field42' => array( 'field' => 'periodo_dias',
'type' => 'import_field' ),
'import_field43' => array( 'field' => 'cont_informessug',
'type' => 'import_field' ),
'import_field44' => array( 'field' => 'periodo_meses',
'type' => 'import_field' ),
'import_field45' => array( 'field' => 'cont_objeto',
'type' => 'import_field' ),
'import_field46' => array( 'field' => 'cont_fechavigencia',
'type' => 'import_field' ),
'import_field47' => array( 'field' => 'VALORINICIAL',
'type' => 'import_field' ),
'import_field48' => array( 'field' => 'cont_valormensual',
'type' => 'import_field' ),
'import_field49' => array( 'field' => 'iva_regimen',
'type' => 'import_field' ),
'import_field50' => array( 'field' => 'cont_iva',
'type' => 'import_field' ),
'import_field51' => array( 'field' => 'cont_valormensual_base',
'type' => 'import_field' ),
'import_field52' => array( 'field' => 'cont_valormensual_iva',
'type' => 'import_field' ),
'import_field53' => array( 'field' => 'CONTVINCULADO',
'type' => 'import_field' ),
'import_field54' => array( 'field' => 'cont_paa_id',
'type' => 'import_field' ),
'import_field55' => array( 'field' => 'cont_tipoc',
'type' => 'import_field' ),
'import_field56' => array( 'field' => 'ct_tipo_nombre',
'type' => 'import_field' ),
'import_field57' => array( 'field' => 'cont_modalidad',
'type' => 'import_field' ),
'import_field58' => array( 'field' => 'des_mod_proceso',
'type' => 'import_field' ),
'import_field59' => array( 'field' => 'cont_causalc',
'type' => 'import_field' ),
'import_field60' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'import_field' ),
'import_field61' => array( 'field' => 'cont_secop_enlace',
'type' => 'import_field' ),
'import_field62' => array( 'field' => 'cont_dep',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>