<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'id_cont',
'cont_nit_contra_ta',
'cont_estado',
'numcontrato',
'pre_contnumero',
'contnumero',
'cont_ano',
'cont_codrubro',
'cont_catalogo_presupuestal',
'cont_fecha_inicio',
'cont_fechafinal',
'PLAZO',
'cont_periodicidad',
'cont_valorinicial',
'cont_valormensual',
'cont_secop_enlace',
'documento_id',
'nombres',
'apellidos',
'nombresupfull',
'cargo_id',
'dependencia_id',
'sup_fechanot',
'sup_mailnot',
'sup_status',
'idusrglobal_fk',
'contractor_name',
'contractor_lname',
'contractor_nombresfull',
'contractor_email',
'contractor_email_mincit',
'prenumero',
'numregistro',
'cont_unspsc',
'cont_tipo_rubro',
'cont_tipopre',
'cont_causalc',
'cont_objeto',
'cont_obligaciones',
'cont_plazo',
'ctb_tipo_nombre',
'nombre_cargo',
'nombre_dependencia',
'id_depto_superior',
'Departamento_superior',
'cont_numpoliza',
'cont_secop_proceso',
'cont_fecha_aprobgarantia',
'cont_fechaapertura',
'cont_munejec',
'cont_cesion',
'cont_modifica',
'Username',
'contractor_type' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'id_cont' => array( 'integrated_search_field' ),
'cont_nit_contra_ta' => array( 'integrated_search_field1' ),
'cont_estado' => array( 'integrated_search_field2' ),
'numcontrato' => array( 'integrated_search_field3' ),
'pre_contnumero' => array( 'integrated_search_field4' ),
'contnumero' => array( 'integrated_search_field5' ),
'cont_ano' => array( 'integrated_search_field6' ),
'cont_codrubro' => array( 'integrated_search_field7' ),
'cont_catalogo_presupuestal' => array( 'integrated_search_field8' ),
'cont_fecha_inicio' => array( 'integrated_search_field9' ),
'cont_fechafinal' => array( 'integrated_search_field10' ),
'PLAZO' => array( 'integrated_search_field11' ),
'cont_periodicidad' => array( 'integrated_search_field12' ),
'cont_valorinicial' => array( 'integrated_search_field13' ),
'cont_valormensual' => array( 'integrated_search_field14' ),
'cont_secop_enlace' => array( 'integrated_search_field15' ),
'documento_id' => array( 'integrated_search_field16' ),
'nombres' => array( 'integrated_search_field17' ),
'apellidos' => array( 'integrated_search_field18' ),
'nombresupfull' => array( 'integrated_search_field19' ),
'cargo_id' => array( 'integrated_search_field20' ),
'dependencia_id' => array( 'integrated_search_field21' ),
'sup_fechanot' => array( 'integrated_search_field22' ),
'sup_mailnot' => array( 'integrated_search_field23' ),
'sup_status' => array( 'integrated_search_field24' ),
'idusrglobal_fk' => array( 'integrated_search_field25' ),
'contractor_name' => array( 'integrated_search_field26' ),
'contractor_lname' => array( 'integrated_search_field27' ),
'contractor_nombresfull' => array( 'integrated_search_field28' ),
'contractor_email' => array( 'integrated_search_field29' ),
'contractor_email_mincit' => array( 'integrated_search_field30' ),
'prenumero' => array( 'integrated_search_field31' ),
'numregistro' => array( 'integrated_search_field32' ),
'cont_unspsc' => array( 'integrated_search_field33' ),
'cont_tipo_rubro' => array( 'integrated_search_field34' ),
'cont_tipopre' => array( 'integrated_search_field35' ),
'cont_causalc' => array( 'integrated_search_field36' ),
'cont_objeto' => array( 'integrated_search_field37' ),
'cont_obligaciones' => array( 'integrated_search_field38' ),
'cont_plazo' => array( 'integrated_search_field39' ),
'ctb_tipo_nombre' => array( 'integrated_search_field40' ),
'nombre_cargo' => array( 'integrated_search_field41' ),
'nombre_dependencia' => array( 'integrated_search_field42' ),
'id_depto_superior' => array( 'integrated_search_field43' ),
'Departamento_superior' => array( 'integrated_search_field44' ),
'cont_numpoliza' => array( 'integrated_search_field45' ),
'cont_secop_proceso' => array( 'integrated_search_field46' ),
'cont_fecha_aprobgarantia' => array( 'integrated_search_field47' ),
'cont_fechaapertura' => array( 'integrated_search_field48' ),
'cont_munejec' => array( 'integrated_search_field49' ),
'cont_cesion' => array( 'integrated_search_field50' ),
'cont_modifica' => array( 'integrated_search_field51' ),
'Username' => array( 'integrated_search_field52' ),
'contractor_type' => array( 'integrated_search_field53' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'top' => array( 'search_header' ),
'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'grid' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_header' => 'top',
'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'integrated_search_field' => 'grid',
'integrated_search_field1' => 'grid',
'integrated_search_field2' => 'grid',
'integrated_search_field3' => 'grid',
'integrated_search_field4' => 'grid',
'integrated_search_field5' => 'grid',
'integrated_search_field6' => 'grid',
'integrated_search_field7' => 'grid',
'integrated_search_field8' => 'grid',
'integrated_search_field9' => 'grid',
'integrated_search_field10' => 'grid',
'integrated_search_field11' => 'grid',
'integrated_search_field12' => 'grid',
'integrated_search_field13' => 'grid',
'integrated_search_field14' => 'grid',
'integrated_search_field15' => 'grid',
'integrated_search_field16' => 'grid',
'integrated_search_field17' => 'grid',
'integrated_search_field18' => 'grid',
'integrated_search_field19' => 'grid',
'integrated_search_field20' => 'grid',
'integrated_search_field21' => 'grid',
'integrated_search_field22' => 'grid',
'integrated_search_field23' => 'grid',
'integrated_search_field24' => 'grid',
'integrated_search_field25' => 'grid',
'integrated_search_field26' => 'grid',
'integrated_search_field27' => 'grid',
'integrated_search_field28' => 'grid',
'integrated_search_field29' => 'grid',
'integrated_search_field30' => 'grid',
'integrated_search_field31' => 'grid',
'integrated_search_field32' => 'grid',
'integrated_search_field33' => 'grid',
'integrated_search_field34' => 'grid',
'integrated_search_field35' => 'grid',
'integrated_search_field36' => 'grid',
'integrated_search_field37' => 'grid',
'integrated_search_field38' => 'grid',
'integrated_search_field39' => 'grid',
'integrated_search_field40' => 'grid',
'integrated_search_field41' => 'grid',
'integrated_search_field42' => 'grid',
'integrated_search_field43' => 'grid',
'integrated_search_field44' => 'grid',
'integrated_search_field45' => 'grid',
'integrated_search_field46' => 'grid',
'integrated_search_field47' => 'grid',
'integrated_search_field48' => 'grid',
'integrated_search_field49' => 'grid',
'integrated_search_field50' => 'grid',
'integrated_search_field51' => 'grid',
'integrated_search_field52' => 'grid',
'integrated_search_field53' => 'grid' ),
'itemLocations' => array( 'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field3' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field6' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field7' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field8' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field9' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field10' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field11' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field12' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field13' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field14' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field15' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field16' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field17' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field18' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field19' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field20' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field21' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field22' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field23' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field24' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field25' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field26' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field27' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field28' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field29' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field30' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field31' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field32' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field33' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field34' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field35' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field36' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field37' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field38' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field39' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field40' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field41' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field42' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field43' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field44' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field45' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field46' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field47' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field48' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field49' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field50' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field51' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field52' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_search_field53' => array( 'location' => 'grid',
'cellId' => 'c3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'integrated_search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false,
'menus' => array(  ),
'calcTotalsFor' => 1 ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 0,
'forms' => array( 'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array(  ),
'cells' => array(  ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field2',
'integrated_search_field3',
'integrated_search_field4',
'integrated_search_field5',
'integrated_search_field6',
'integrated_search_field7',
'integrated_search_field8',
'integrated_search_field9',
'integrated_search_field10',
'integrated_search_field11',
'integrated_search_field12',
'integrated_search_field13',
'integrated_search_field14',
'integrated_search_field15',
'integrated_search_field16',
'integrated_search_field17',
'integrated_search_field18',
'integrated_search_field19',
'integrated_search_field20',
'integrated_search_field21',
'integrated_search_field22',
'integrated_search_field23',
'integrated_search_field24',
'integrated_search_field25',
'integrated_search_field26',
'integrated_search_field27',
'integrated_search_field28',
'integrated_search_field29',
'integrated_search_field30',
'integrated_search_field31',
'integrated_search_field32',
'integrated_search_field33',
'integrated_search_field34',
'integrated_search_field35',
'integrated_search_field36',
'integrated_search_field37',
'integrated_search_field38',
'integrated_search_field39',
'integrated_search_field40',
'integrated_search_field41',
'integrated_search_field42',
'integrated_search_field43',
'integrated_search_field44',
'integrated_search_field45',
'integrated_search_field46',
'integrated_search_field47',
'integrated_search_field48',
'integrated_search_field49',
'integrated_search_field50',
'integrated_search_field51',
'integrated_search_field52',
'integrated_search_field53' ),
'_t' => 'Map',
'_i' => array(  ),
'_s' => 0 ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header' ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'id_cont',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field1' => array( 'field' => 'cont_nit_contra_ta',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field2' => array( 'field' => 'cont_estado',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field3' => array( 'field' => 'numcontrato',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field4' => array( 'field' => 'pre_contnumero',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field5' => array( 'field' => 'contnumero',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field6' => array( 'field' => 'cont_ano',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field7' => array( 'field' => 'cont_codrubro',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field8' => array( 'field' => 'cont_catalogo_presupuestal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field9' => array( 'field' => 'cont_fecha_inicio',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field10' => array( 'field' => 'cont_fechafinal',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field11' => array( 'field' => 'PLAZO',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field12' => array( 'field' => 'cont_periodicidad',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field13' => array( 'field' => 'cont_valorinicial',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field14' => array( 'field' => 'cont_valormensual',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field15' => array( 'field' => 'cont_secop_enlace',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field16' => array( 'field' => 'documento_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field17' => array( 'field' => 'nombres',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field18' => array( 'field' => 'apellidos',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field19' => array( 'field' => 'nombresupfull',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field20' => array( 'field' => 'cargo_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field21' => array( 'field' => 'dependencia_id',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field22' => array( 'field' => 'sup_fechanot',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field23' => array( 'field' => 'sup_mailnot',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field24' => array( 'field' => 'sup_status',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field25' => array( 'field' => 'idusrglobal_fk',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field26' => array( 'field' => 'contractor_name',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field27' => array( 'field' => 'contractor_lname',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field28' => array( 'field' => 'contractor_nombresfull',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field29' => array( 'field' => 'contractor_email',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field30' => array( 'field' => 'contractor_email_mincit',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field31' => array( 'field' => 'prenumero',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field32' => array( 'field' => 'numregistro',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field33' => array( 'field' => 'cont_unspsc',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field34' => array( 'field' => 'cont_tipo_rubro',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field35' => array( 'field' => 'cont_tipopre',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field36' => array( 'field' => 'cont_causalc',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field37' => array( 'field' => 'cont_objeto',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field38' => array( 'field' => 'cont_obligaciones',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field39' => array( 'field' => 'cont_plazo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field40' => array( 'field' => 'ctb_tipo_nombre',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field41' => array( 'field' => 'nombre_cargo',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field42' => array( 'field' => 'nombre_dependencia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field43' => array( 'field' => 'id_depto_superior',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field44' => array( 'field' => 'Departamento_superior',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field45' => array( 'field' => 'cont_numpoliza',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field46' => array( 'field' => 'cont_secop_proceso',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field47' => array( 'field' => 'cont_fecha_aprobgarantia',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field48' => array( 'field' => 'cont_fechaapertura',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field49' => array( 'field' => 'cont_munejec',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field50' => array( 'field' => 'cont_cesion',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field51' => array( 'field' => 'cont_modifica',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field52' => array( 'field' => 'Username',
'type' => 'integrated_search_field',
'orientation' => 0,
'required' => false ),
'integrated_search_field53' => array( 'field' => 'contractor_type',
'type' => 'integrated_search_field',
'orientation' => 0 ) ),
'dbProps' => array(  ),
'version' => 14,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'listTotals' => 1 );
		?>