<?php
$dalTablehoja_ruta_2020 = array();
$dalTablehoja_ruta_2020["anio"] = array("type"=>2,"varname"=>"anio", "name" => "anio", "autoInc" => "0");
$dalTablehoja_ruta_2020["cont_num"] = array("type"=>200,"varname"=>"cont_num", "name" => "cont_num", "autoInc" => "0");
$dalTablehoja_ruta_2020["ctrlpagos_id_fk"] = array("type"=>3,"varname"=>"ctrlpagos_id_fk", "name" => "ctrlpagos_id_fk", "autoInc" => "0");
$dalTablehoja_ruta_2020["cxc_id_fk"] = array("type"=>3,"varname"=>"cxc_id_fk", "name" => "cxc_id_fk", "autoInc" => "0");
$dalTablehoja_ruta_2020["evento_type_id_fk"] = array("type"=>3,"varname"=>"evento_type_id_fk", "name" => "evento_type_id_fk", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_anio"] = array("type"=>2,"varname"=>"hr_anio", "name" => "hr_anio", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_aprob_estado"] = array("type"=>16,"varname"=>"hr_aprob_estado", "name" => "hr_aprob_estado", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_aprob_fecha"] = array("type"=>135,"varname"=>"hr_aprob_fecha", "name" => "hr_aprob_fecha", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_aprob_user"] = array("type"=>200,"varname"=>"hr_aprob_user", "name" => "hr_aprob_user", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_asunto"] = array("type"=>200,"varname"=>"hr_asunto", "name" => "hr_asunto", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_concepto_id"] = array("type"=>3,"varname"=>"hr_concepto_id", "name" => "hr_concepto_id", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_estado_fecha"] = array("type"=>7,"varname"=>"hr_estado_fecha", "name" => "hr_estado_fecha", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_estado_file"] = array("type"=>200,"varname"=>"hr_estado_file", "name" => "hr_estado_file", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_estado_firma"] = array("type"=>200,"varname"=>"hr_estado_firma", "name" => "hr_estado_firma", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_estado_numero"] = array("type"=>200,"varname"=>"hr_estado_numero", "name" => "hr_estado_numero", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_estado_user"] = array("type"=>200,"varname"=>"hr_estado_user", "name" => "hr_estado_user", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_fecha_salida"] = array("type"=>135,"varname"=>"hr_fecha_salida", "name" => "hr_fecha_salida", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_fechaingreso"] = array("type"=>135,"varname"=>"hr_fechaingreso", "name" => "hr_fechaingreso", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_file"] = array("type"=>200,"varname"=>"hr_file", "name" => "hr_file", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_id"] = array("type"=>3,"varname"=>"hr_id", "name" => "hr_id", "autoInc" => "1");
$dalTablehoja_ruta_2020["hr_nit_contra_ta"] = array("type"=>200,"varname"=>"hr_nit_contra_ta", "name" => "hr_nit_contra_ta", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_valor"] = array("type"=>5,"varname"=>"hr_valor", "name" => "hr_valor", "autoInc" => "0");
$dalTablehoja_ruta_2020["id_cont_fk"] = array("type"=>3,"varname"=>"id_cont_fk", "name" => "id_cont_fk", "autoInc" => "0");
$dalTablehoja_ruta_2020["id_informe_fk"] = array("type"=>3,"varname"=>"id_informe_fk", "name" => "id_informe_fk", "autoInc" => "0");
$dalTablehoja_ruta_2020["last_act_user"] = array("type"=>200,"varname"=>"last_act_user", "name" => "last_act_user", "autoInc" => "0");
$dalTablehoja_ruta_2020["mes"] = array("type"=>16,"varname"=>"mes", "name" => "mes", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_date"] = array("type"=>135,"varname"=>"not_date", "name" => "not_date", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_mail"] = array("type"=>200,"varname"=>"not_mail", "name" => "not_mail", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_msg"] = array("type"=>200,"varname"=>"not_msg", "name" => "not_msg", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_status"] = array("type"=>16,"varname"=>"not_status", "name" => "not_status", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_time"] = array("type"=>134,"varname"=>"not_time", "name" => "not_time", "autoInc" => "0");
$dalTablehoja_ruta_2020["not_user"] = array("type"=>200,"varname"=>"not_user", "name" => "not_user", "autoInc" => "0");
$dalTablehoja_ruta_2020["obligacion"] = array("type"=>200,"varname"=>"obligacion", "name" => "obligacion", "autoInc" => "0");
$dalTablehoja_ruta_2020["periodo_id"] = array("type"=>3,"varname"=>"periodo_id", "name" => "periodo_id", "autoInc" => "0");
$dalTablehoja_ruta_2020["supervisor_email"] = array("type"=>200,"varname"=>"supervisor_email", "name" => "supervisor_email", "autoInc" => "0");
$dalTablehoja_ruta_2020["sys_dep"] = array("type"=>3,"varname"=>"sys_dep", "name" => "sys_dep", "autoInc" => "0");
$dalTablehoja_ruta_2020["sys_fecha_reg"] = array("type"=>135,"varname"=>"sys_fecha_reg", "name" => "sys_fecha_reg", "autoInc" => "0");
$dalTablehoja_ruta_2020["sys_sup"] = array("type"=>200,"varname"=>"sys_sup", "name" => "sys_sup", "autoInc" => "0");
$dalTablehoja_ruta_2020["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user", "autoInc" => "0");
$dalTablehoja_ruta_2020["sys_user_actual"] = array("type"=>200,"varname"=>"sys_user_actual", "name" => "sys_user_actual", "autoInc" => "0");
$dalTablehoja_ruta_2020["sysdate"] = array("type"=>135,"varname"=>"sysdate", "name" => "sysdate", "autoInc" => "0");
$dalTablehoja_ruta_2020["tercero_email"] = array("type"=>200,"varname"=>"tercero_email", "name" => "tercero_email", "autoInc" => "0");
$dalTablehoja_ruta_2020["tercero_email_a"] = array("type"=>200,"varname"=>"tercero_email_a", "name" => "tercero_email_a", "autoInc" => "0");
$dalTablehoja_ruta_2020["tercero_email_b"] = array("type"=>200,"varname"=>"tercero_email_b", "name" => "tercero_email_b", "autoInc" => "0");
$dalTablehoja_ruta_2020["user_from"] = array("type"=>200,"varname"=>"user_from", "name" => "user_from", "autoInc" => "0");
$dalTablehoja_ruta_2020["hr_id"]["key"]=true;

$dal_info["contratacion_at_172_18_0_115__hoja_ruta_2020"] = &$dalTablehoja_ruta_2020;
?>