<?php
$dalTableinforme_intersup_cxc = array();
$dalTableinforme_intersup_cxc["cont_banco"] = array("type"=>3,"varname"=>"cont_banco", "name" => "cont_banco", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_cdp"] = array("type"=>200,"varname"=>"cont_cdp", "name" => "cont_cdp", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_cuentanumero"] = array("type"=>200,"varname"=>"cont_cuentanumero", "name" => "cont_cuentanumero", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_cuentatipo"] = array("type"=>16,"varname"=>"cont_cuentatipo", "name" => "cont_cuentatipo", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_factura"] = array("type"=>16,"varname"=>"cont_factura", "name" => "cont_factura", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_fechaf"] = array("type"=>7,"varname"=>"cont_fechaf", "name" => "cont_fechaf", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_fechai"] = array("type"=>7,"varname"=>"cont_fechai", "name" => "cont_fechai", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_pagomensual"] = array("type"=>5,"varname"=>"cont_pagomensual", "name" => "cont_pagomensual", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_rp"] = array("type"=>200,"varname"=>"cont_rp", "name" => "cont_rp", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_rubro"] = array("type"=>200,"varname"=>"cont_rubro", "name" => "cont_rubro", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_uej"] = array("type"=>200,"varname"=>"cont_uej", "name" => "cont_uej", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_uso"] = array("type"=>200,"varname"=>"cont_uso", "name" => "cont_uso", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cont_valorcontrato"] = array("type"=>5,"varname"=>"cont_valorcontrato", "name" => "cont_valorcontrato", "autoInc" => "0");
$dalTableinforme_intersup_cxc["ctrl"] = array("type"=>200,"varname"=>"ctrl", "name" => "ctrl", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_anio"] = array("type"=>2,"varname"=>"cxc_anio", "name" => "cxc_anio", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_cont"] = array("type"=>200,"varname"=>"cxc_cont", "name" => "cxc_cont", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_fechaelab"] = array("type"=>7,"varname"=>"cxc_fechaelab", "name" => "cxc_fechaelab", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_fondopenvol"] = array("type"=>5,"varname"=>"cxc_fondopenvol", "name" => "cxc_fondopenvol", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_id"] = array("type"=>3,"varname"=>"cxc_id", "name" => "cxc_id", "autoInc" => "1");
$dalTableinforme_intersup_cxc["cxc_numdoc"] = array("type"=>200,"varname"=>"cxc_numdoc", "name" => "cxc_numdoc", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_pagoafc"] = array("type"=>5,"varname"=>"cxc_pagoafc", "name" => "cxc_pagoafc", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_periodof"] = array("type"=>7,"varname"=>"cxc_periodof", "name" => "cxc_periodof", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_periodoi"] = array("type"=>7,"varname"=>"cxc_periodoi", "name" => "cxc_periodoi", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_planilla"] = array("type"=>200,"varname"=>"cxc_planilla", "name" => "cxc_planilla", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_planillafecha"] = array("type"=>7,"varname"=>"cxc_planillafecha", "name" => "cxc_planillafecha", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_planillavalor"] = array("type"=>5,"varname"=>"cxc_planillavalor", "name" => "cxc_planillavalor", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_razonsocial"] = array("type"=>200,"varname"=>"cxc_razonsocial", "name" => "cxc_razonsocial", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_tipocontrato"] = array("type"=>200,"varname"=>"cxc_tipocontrato", "name" => "cxc_tipocontrato", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_tipodoc"] = array("type"=>200,"varname"=>"cxc_tipodoc", "name" => "cxc_tipodoc", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_valor"] = array("type"=>5,"varname"=>"cxc_valor", "name" => "cxc_valor", "autoInc" => "0");
$dalTableinforme_intersup_cxc["de_num"] = array("type"=>3,"varname"=>"de_num", "name" => "de_num", "autoInc" => "0");
$dalTableinforme_intersup_cxc["de_pre"] = array("type"=>200,"varname"=>"de_pre", "name" => "de_pre", "autoInc" => "0");
$dalTableinforme_intersup_cxc["evento_type_id_fk"] = array("type"=>3,"varname"=>"evento_type_id_fk", "name" => "evento_type_id_fk", "autoInc" => "0");
$dalTableinforme_intersup_cxc["id_consecutivo"] = array("type"=>3,"varname"=>"id_consecutivo", "name" => "id_consecutivo", "autoInc" => "0");
$dalTableinforme_intersup_cxc["id_cont"] = array("type"=>3,"varname"=>"id_cont", "name" => "id_cont", "autoInc" => "0");
$dalTableinforme_intersup_cxc["inf_hash_fk"] = array("type"=>200,"varname"=>"inf_hash_fk", "name" => "inf_hash_fk", "autoInc" => "0");
$dalTableinforme_intersup_cxc["inf_id_fk"] = array("type"=>3,"varname"=>"inf_id_fk", "name" => "inf_id_fk", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_date"] = array("type"=>135,"varname"=>"send_date", "name" => "send_date", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_dev_date"] = array("type"=>135,"varname"=>"send_dev_date", "name" => "send_dev_date", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_dev_func"] = array("type"=>200,"varname"=>"send_dev_func", "name" => "send_dev_func", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_dev_mail"] = array("type"=>200,"varname"=>"send_dev_mail", "name" => "send_dev_mail", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_dev_mail_obs"] = array("type"=>200,"varname"=>"send_dev_mail_obs", "name" => "send_dev_mail_obs", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_mail"] = array("type"=>200,"varname"=>"send_mail", "name" => "send_mail", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_mail_obs"] = array("type"=>200,"varname"=>"send_mail_obs", "name" => "send_mail_obs", "autoInc" => "0");
$dalTableinforme_intersup_cxc["send_user"] = array("type"=>200,"varname"=>"send_user", "name" => "send_user", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sup_cargo"] = array("type"=>200,"varname"=>"sup_cargo", "name" => "sup_cargo", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sup_dep"] = array("type"=>200,"varname"=>"sup_dep", "name" => "sup_dep", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sup_name"] = array("type"=>200,"varname"=>"sup_name", "name" => "sup_name", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_fecha"] = array("type"=>135,"varname"=>"sys_fecha", "name" => "sys_fecha", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_radicadate"] = array("type"=>7,"varname"=>"sys_radicadate", "name" => "sys_radicadate", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_radicaperiodo"] = array("type"=>200,"varname"=>"sys_radicaperiodo", "name" => "sys_radicaperiodo", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_radicatime"] = array("type"=>134,"varname"=>"sys_radicatime", "name" => "sys_radicatime", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_radicauser"] = array("type"=>200,"varname"=>"sys_radicauser", "name" => "sys_radicauser", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_status"] = array("type"=>16,"varname"=>"sys_status", "name" => "sys_status", "autoInc" => "0");
$dalTableinforme_intersup_cxc["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user", "autoInc" => "0");
$dalTableinforme_intersup_cxc["cxc_id"]["key"]=true;

$dal_info["dbct_at_localhost__informe_intersup_cxc"] = &$dalTableinforme_intersup_cxc;
?>