<?php
$dalTablecontractor_master = array();
$dalTablecontractor_master["active"] = array("type"=>3,"varname"=>"active", "name" => "active", "autoInc" => "0");
$dalTablecontractor_master["actividad_economica"] = array("type"=>200,"varname"=>"actividad_economica", "name" => "actividad_economica", "autoInc" => "0");
$dalTablecontractor_master["bank_cta_number"] = array("type"=>200,"varname"=>"bank_cta_number", "name" => "bank_cta_number", "autoInc" => "0");
$dalTablecontractor_master["bank_cta_type"] = array("type"=>3,"varname"=>"bank_cta_type", "name" => "bank_cta_type", "autoInc" => "0");
$dalTablecontractor_master["bank_name"] = array("type"=>3,"varname"=>"bank_name", "name" => "bank_name", "autoInc" => "0");
$dalTablecontractor_master["contractor_address"] = array("type"=>200,"varname"=>"contractor_address", "name" => "contractor_address", "autoInc" => "0");
$dalTablecontractor_master["contractor_arl"] = array("type"=>3,"varname"=>"contractor_arl", "name" => "contractor_arl", "autoInc" => "0");
$dalTablecontractor_master["contractor_cajacompensacion"] = array("type"=>3,"varname"=>"contractor_cajacompensacion", "name" => "contractor_cajacompensacion", "autoInc" => "0");
$dalTablecontractor_master["contractor_city"] = array("type"=>200,"varname"=>"contractor_city", "name" => "contractor_city", "autoInc" => "0");
$dalTablecontractor_master["contractor_decljur"] = array("type"=>200,"varname"=>"contractor_decljur", "name" => "contractor_decljur", "autoInc" => "0");
$dalTablecontractor_master["contractor_dependencia"] = array("type"=>3,"varname"=>"contractor_dependencia", "name" => "contractor_dependencia", "autoInc" => "0");
$dalTablecontractor_master["contractor_dependientes"] = array("type"=>16,"varname"=>"contractor_dependientes", "name" => "contractor_dependientes", "autoInc" => "0");
$dalTablecontractor_master["contractor_doc_dv"] = array("type"=>200,"varname"=>"contractor_doc_dv", "name" => "contractor_doc_dv", "autoInc" => "0");
$dalTablecontractor_master["contractor_doc_id"] = array("type"=>200,"varname"=>"contractor_doc_id", "name" => "contractor_doc_id", "autoInc" => "0");
$dalTablecontractor_master["contractor_email"] = array("type"=>200,"varname"=>"contractor_email", "name" => "contractor_email", "autoInc" => "0");
$dalTablecontractor_master["contractor_email_mincit"] = array("type"=>200,"varname"=>"contractor_email_mincit", "name" => "contractor_email_mincit", "autoInc" => "0");
$dalTablecontractor_master["contractor_eps"] = array("type"=>3,"varname"=>"contractor_eps", "name" => "contractor_eps", "autoInc" => "0");
$dalTablecontractor_master["contractor_fondopensiones"] = array("type"=>3,"varname"=>"contractor_fondopensiones", "name" => "contractor_fondopensiones", "autoInc" => "0");
$dalTablecontractor_master["contractor_id"] = array("type"=>3,"varname"=>"contractor_id", "name" => "contractor_id", "autoInc" => "1");
$dalTablecontractor_master["contractor_image"] = array("type"=>200,"varname"=>"contractor_image", "name" => "contractor_image", "autoInc" => "0");
$dalTablecontractor_master["contractor_lname"] = array("type"=>200,"varname"=>"contractor_lname", "name" => "contractor_lname", "autoInc" => "0");
$dalTablecontractor_master["contractor_medicinapre_file"] = array("type"=>200,"varname"=>"contractor_medicinapre_file", "name" => "contractor_medicinapre_file", "autoInc" => "0");
$dalTablecontractor_master["contractor_mobile"] = array("type"=>200,"varname"=>"contractor_mobile", "name" => "contractor_mobile", "autoInc" => "0");
$dalTablecontractor_master["contractor_name"] = array("type"=>200,"varname"=>"contractor_name", "name" => "contractor_name", "autoInc" => "0");
$dalTablecontractor_master["contractor_naturaleza"] = array("type"=>16,"varname"=>"contractor_naturaleza", "name" => "contractor_naturaleza", "autoInc" => "0");
$dalTablecontractor_master["contractor_nombresfull"] = array("type"=>200,"varname"=>"contractor_nombresfull", "name" => "contractor_nombresfull", "autoInc" => "0");
$dalTablecontractor_master["contractor_phone"] = array("type"=>200,"varname"=>"contractor_phone", "name" => "contractor_phone", "autoInc" => "0");
$dalTablecontractor_master["contractor_picmonetaria_file"] = array("type"=>200,"varname"=>"contractor_picmonetaria_file", "name" => "contractor_picmonetaria_file", "autoInc" => "0");
$dalTablecontractor_master["contractor_pwd"] = array("type"=>200,"varname"=>"contractor_pwd", "name" => "contractor_pwd", "autoInc" => "0");
$dalTablecontractor_master["contractor_sup_jerarquico"] = array("type"=>3,"varname"=>"contractor_sup_jerarquico", "name" => "contractor_sup_jerarquico", "autoInc" => "0");
$dalTablecontractor_master["contractor_type"] = array("type"=>200,"varname"=>"contractor_type", "name" => "contractor_type", "autoInc" => "0");
$dalTablecontractor_master["ct_fecha_nacimiento"] = array("type"=>7,"varname"=>"ct_fecha_nacimiento", "name" => "ct_fecha_nacimiento", "autoInc" => "0");
$dalTablecontractor_master["ct_fecha_nacimiento_mun"] = array("type"=>200,"varname"=>"ct_fecha_nacimiento_mun", "name" => "ct_fecha_nacimiento_mun", "autoInc" => "0");
$dalTablecontractor_master["ct_nacionalidad"] = array("type"=>200,"varname"=>"ct_nacionalidad", "name" => "ct_nacionalidad", "autoInc" => "0");
$dalTablecontractor_master["dem_discapacidad"] = array("type"=>200,"varname"=>"dem_discapacidad", "name" => "dem_discapacidad", "autoInc" => "0");
$dalTablecontractor_master["dem_edad"] = array("type"=>3,"varname"=>"dem_edad", "name" => "dem_edad", "autoInc" => "0");
$dalTablecontractor_master["dem_educacion"] = array("type"=>3,"varname"=>"dem_educacion", "name" => "dem_educacion", "autoInc" => "0");
$dalTablecontractor_master["dem_genero"] = array("type"=>200,"varname"=>"dem_genero", "name" => "dem_genero", "autoInc" => "0");
$dalTablecontractor_master["dem_ocupacion"] = array("type"=>3,"varname"=>"dem_ocupacion", "name" => "dem_ocupacion", "autoInc" => "0");
$dalTablecontractor_master["dem_profesion"] = array("type"=>200,"varname"=>"dem_profesion", "name" => "dem_profesion", "autoInc" => "0");
$dalTablecontractor_master["emergencia"] = array("type"=>200,"varname"=>"emergencia", "name" => "emergencia", "autoInc" => "0");
$dalTablecontractor_master["enlace_sigep"] = array("type"=>200,"varname"=>"enlace_sigep", "name" => "enlace_sigep", "autoInc" => "0");
$dalTablecontractor_master["factura"] = array("type"=>16,"varname"=>"factura", "name" => "factura", "autoInc" => "0");
$dalTablecontractor_master["groupid"] = array("type"=>200,"varname"=>"groupid", "name" => "groupid", "autoInc" => "0");
$dalTablecontractor_master["iva_regimen"] = array("type"=>16,"varname"=>"iva_regimen", "name" => "iva_regimen", "autoInc" => "0");
$dalTablecontractor_master["pin"] = array("type"=>200,"varname"=>"pin", "name" => "pin", "autoInc" => "0");
$dalTablecontractor_master["reset_date"] = array("type"=>135,"varname"=>"reset_date", "name" => "reset_date", "autoInc" => "0");
$dalTablecontractor_master["reset_date1"] = array("type"=>135,"varname"=>"reset_date1", "name" => "reset_date1", "autoInc" => "0");
$dalTablecontractor_master["reset_token"] = array("type"=>201,"varname"=>"reset_token", "name" => "reset_token", "autoInc" => "0");
$dalTablecontractor_master["reset_token1"] = array("type"=>201,"varname"=>"reset_token1", "name" => "reset_token1", "autoInc" => "0");
$dalTablecontractor_master["responsabilidades"] = array("type"=>200,"varname"=>"responsabilidades", "name" => "responsabilidades", "autoInc" => "0");
$dalTablecontractor_master["signature"] = array("type"=>200,"varname"=>"signature", "name" => "signature", "autoInc" => "0");
$dalTablecontractor_master["sys_date"] = array("type"=>7,"varname"=>"sys_date", "name" => "sys_date", "autoInc" => "0");
$dalTablecontractor_master["sys_last_upd"] = array("type"=>135,"varname"=>"sys_last_upd", "name" => "sys_last_upd", "autoInc" => "0");
$dalTablecontractor_master["sys_level"] = array("type"=>16,"varname"=>"sys_level", "name" => "sys_level", "autoInc" => "0");
$dalTablecontractor_master["sys_status"] = array("type"=>16,"varname"=>"sys_status", "name" => "sys_status", "autoInc" => "0");
$dalTablecontractor_master["sys_update"] = array("type"=>16,"varname"=>"sys_update", "name" => "sys_update", "autoInc" => "0");
$dalTablecontractor_master["sys_user"] = array("type"=>200,"varname"=>"sys_user", "name" => "sys_user", "autoInc" => "0");
$dalTablecontractor_master["terms_acepta"] = array("type"=>16,"varname"=>"terms_acepta", "name" => "terms_acepta", "autoInc" => "0");
$dalTablecontractor_master["terms_msj"] = array("type"=>201,"varname"=>"terms_msj", "name" => "terms_msj", "autoInc" => "0");
$dalTablecontractor_master["ubica_dep"] = array("type"=>3,"varname"=>"ubica_dep", "name" => "ubica_dep", "autoInc" => "0");
$dalTablecontractor_master["ubica_extension"] = array("type"=>200,"varname"=>"ubica_extension", "name" => "ubica_extension", "autoInc" => "0");
$dalTablecontractor_master["contractor_doc_id"]["key"]=true;
$dalTablecontractor_master["contractor_id"]["key"]=true;

$dal_info["dbct_at_localhost__contractor_master"] = &$dalTablecontractor_master;
?>