<?php
$dalTableq_genera_informe = array();
$dalTableq_genera_informe["cert_mes"] = array("type"=>200,"varname"=>"cert_mes", "name" => "cert_mes", "autoInc" => "0");
$dalTableq_genera_informe["cert_modalidad"] = array("type"=>200,"varname"=>"cert_modalidad", "name" => "cert_modalidad", "autoInc" => "0");
$dalTableq_genera_informe["cert_msj"] = array("type"=>201,"varname"=>"cert_msj", "name" => "cert_msj", "autoInc" => "0");
$dalTableq_genera_informe["id_cont_fk"] = array("type"=>3,"varname"=>"id_cont_fk", "name" => "id_cont_fk", "autoInc" => "0");
$dalTableq_genera_informe["inf_actividades"] = array("type"=>201,"varname"=>"inf_actividades", "name" => "inf_actividades", "autoInc" => "0");
$dalTableq_genera_informe["inf_anio"] = array("type"=>2,"varname"=>"inf_anio", "name" => "inf_anio", "autoInc" => "0");
$dalTableq_genera_informe["inf_avgejecucion"] = array("type"=>5,"varname"=>"inf_avgejecucion", "name" => "inf_avgejecucion", "autoInc" => "0");
$dalTableq_genera_informe["inf_cargo"] = array("type"=>200,"varname"=>"inf_cargo", "name" => "inf_cargo", "autoInc" => "0");
$dalTableq_genera_informe["inf_cdp"] = array("type"=>200,"varname"=>"inf_cdp", "name" => "inf_cdp", "autoInc" => "0");
$dalTableq_genera_informe["inf_consecutivo"] = array("type"=>3,"varname"=>"inf_consecutivo", "name" => "inf_consecutivo", "autoInc" => "0");
$dalTableq_genera_informe["inf_declarainconf"] = array("type"=>200,"varname"=>"inf_declarainconf", "name" => "inf_declarainconf", "autoInc" => "0");
$dalTableq_genera_informe["inf_declarainconf_obs"] = array("type"=>200,"varname"=>"inf_declarainconf_obs", "name" => "inf_declarainconf_obs", "autoInc" => "0");
$dalTableq_genera_informe["inf_dependencia"] = array("type"=>200,"varname"=>"inf_dependencia", "name" => "inf_dependencia", "autoInc" => "0");
$dalTableq_genera_informe["inf_doccontratista"] = array("type"=>200,"varname"=>"inf_doccontratista", "name" => "inf_doccontratista", "autoInc" => "0");
$dalTableq_genera_informe["inf_estado"] = array("type"=>3,"varname"=>"inf_estado", "name" => "inf_estado", "autoInc" => "0");
$dalTableq_genera_informe["inf_fechacont_f"] = array("type"=>7,"varname"=>"inf_fechacont_f", "name" => "inf_fechacont_f", "autoInc" => "0");
$dalTableq_genera_informe["inf_fechacont_i"] = array("type"=>7,"varname"=>"inf_fechacont_i", "name" => "inf_fechacont_i", "autoInc" => "0");
$dalTableq_genera_informe["inf_fechapresenta"] = array("type"=>7,"varname"=>"inf_fechapresenta", "name" => "inf_fechapresenta", "autoInc" => "0");
$dalTableq_genera_informe["inf_fecharep_f"] = array("type"=>7,"varname"=>"inf_fecharep_f", "name" => "inf_fecharep_f", "autoInc" => "0");
$dalTableq_genera_informe["inf_fecharep_i"] = array("type"=>7,"varname"=>"inf_fecharep_i", "name" => "inf_fecharep_i", "autoInc" => "0");
$dalTableq_genera_informe["inf_fechasuscripcion"] = array("type"=>7,"varname"=>"inf_fechasuscripcion", "name" => "inf_fechasuscripcion", "autoInc" => "0");
$dalTableq_genera_informe["inf_hash"] = array("type"=>200,"varname"=>"inf_hash", "name" => "inf_hash", "autoInc" => "0");
$dalTableq_genera_informe["inf_id"] = array("type"=>3,"varname"=>"inf_id", "name" => "inf_id", "autoInc" => "0");
$dalTableq_genera_informe["inf_incumplimiento"] = array("type"=>200,"varname"=>"inf_incumplimiento", "name" => "inf_incumplimiento", "autoInc" => "0");
$dalTableq_genera_informe["inf_incumplimiento_obs"] = array("type"=>200,"varname"=>"inf_incumplimiento_obs", "name" => "inf_incumplimiento_obs", "autoInc" => "0");
$dalTableq_genera_informe["inf_intersup"] = array("type"=>200,"varname"=>"inf_intersup", "name" => "inf_intersup", "autoInc" => "0");
$dalTableq_genera_informe["inf_mail_a"] = array("type"=>200,"varname"=>"inf_mail_a", "name" => "inf_mail_a", "autoInc" => "0");
$dalTableq_genera_informe["inf_mail_b"] = array("type"=>200,"varname"=>"inf_mail_b", "name" => "inf_mail_b", "autoInc" => "0");
$dalTableq_genera_informe["inf_modificacionesplazo"] = array("type"=>200,"varname"=>"inf_modificacionesplazo", "name" => "inf_modificacionesplazo", "autoInc" => "0");
$dalTableq_genera_informe["inf_nombre"] = array("type"=>200,"varname"=>"inf_nombre", "name" => "inf_nombre", "autoInc" => "0");
$dalTableq_genera_informe["inf_nombrecontratista"] = array("type"=>200,"varname"=>"inf_nombrecontratista", "name" => "inf_nombrecontratista", "autoInc" => "0");
$dalTableq_genera_informe["inf_numerocontrato"] = array("type"=>200,"varname"=>"inf_numerocontrato", "name" => "inf_numerocontrato", "autoInc" => "0");
$dalTableq_genera_informe["inf_objeto"] = array("type"=>200,"varname"=>"inf_objeto", "name" => "inf_objeto", "autoInc" => "0");
$dalTableq_genera_informe["inf_periodicidad"] = array("type"=>16,"varname"=>"inf_periodicidad", "name" => "inf_periodicidad", "autoInc" => "0");
$dalTableq_genera_informe["inf_plazo"] = array("type"=>200,"varname"=>"inf_plazo", "name" => "inf_plazo", "autoInc" => "0");
$dalTableq_genera_informe["inf_rp"] = array("type"=>200,"varname"=>"inf_rp", "name" => "inf_rp", "autoInc" => "0");
$dalTableq_genera_informe["inf_rubrocode"] = array("type"=>200,"varname"=>"inf_rubrocode", "name" => "inf_rubrocode", "autoInc" => "0");
$dalTableq_genera_informe["inf_rubroname"] = array("type"=>200,"varname"=>"inf_rubroname", "name" => "inf_rubroname", "autoInc" => "0");
$dalTableq_genera_informe["inf_usopresupuestal"] = array("type"=>200,"varname"=>"inf_usopresupuestal", "name" => "inf_usopresupuestal", "autoInc" => "0");
$dalTableq_genera_informe["inf_valorcontrato"] = array("type"=>5,"varname"=>"inf_valorcontrato", "name" => "inf_valorcontrato", "autoInc" => "0");
$dalTableq_genera_informe["inf_vigencia"] = array("type"=>200,"varname"=>"inf_vigencia", "name" => "inf_vigencia", "autoInc" => "0");
$dalTableq_genera_informe["periodo_name"] = array("type"=>200,"varname"=>"periodo_name", "name" => "periodo_name", "autoInc" => "0");
$dalTableq_genera_informe["sign_verificacert_date"] = array("type"=>135,"varname"=>"sign_verificacert_date", "name" => "sign_verificacert_date", "autoInc" => "0");
$dalTableq_genera_informe["sign_verificacert_ip"] = array("type"=>200,"varname"=>"sign_verificacert_ip", "name" => "sign_verificacert_ip", "autoInc" => "0");
$dalTableq_genera_informe["sign_verificacert_user"] = array("type"=>200,"varname"=>"sign_verificacert_user", "name" => "sign_verificacert_user", "autoInc" => "0");

$dal_info["dbct_at_localhost__q_genera_informe"] = &$dalTableq_genera_informe;
?>