<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_informe_intersup_anexos_contratista  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeAdd"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record added
function BeforeAdd(&$values, &$sqlValues, &$message, $inline, $pageObject)
{

		$dirname= "../GesDoc/Contratos/".$values['id_cont_fk'];
    if (is_dir($dirname)) {
    } else {
       mkdir("../GesDoc/Contratos/".$values['id_cont_fk'], 0777);
    }
//crea directorio sino existe
$dirname= "../GesDoc/Contratos/".$values['id_cont_fk']."/".$values['inf_id_fk'];
    if (is_dir($dirname)) {
    } else {
       mkdir("../GesDoc/Contratos/".$values['id_cont_fk']."/".$values['inf_id_fk'], 0777);
    }
//fin crear directorio

$fileArray = my_json_decode($values['anexo_file']);
 
// Renombrar adjuntos
for($i = 0; $i < count($fileArray); $i++)
{
  $fileName = $fileArray[$i]["name"];
  $newFileName = "../GesDoc/Contratos/".$values['id_cont_fk']."/".$values['inf_id_fk']."/".$values['inf_id_fk']."_".$values['id_cont_fk']."_".$values['ctrl']."_".$values['anexo_hash']."_".$i.".pdf";
  rename($fileName, getabspath($newFileName));
  $fileArray[$i]["name"] = $newFileName;
  $fileArray[$i]["usrName"] = $values['inf_id_fk']."_".$values['id_cont_fk']."_".$values['ctrl']."_".$values['anexo_hash']."_".$i.".pdf";
}
 
// actualizacion de archivo
$values['anexo_file'] = my_json_encode($fileArray);

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;		
} // function BeforeAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>
